### ISSUE TITLE
NuGet packaging bugs

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#11]
* You populate the lib\net45 folder but your projects actually target .NET 4.6. This will cause .NET 4.5 projects that install your packages to fail.
* You populate the lib folder with assemblies that you got from other NuGet packages instead of expressing a dependency on their package. This will cause projects to be unable to depend on these other packages and then add yours without errors.

**Comment by AArnott** [comment]
I'm working on a PR to fix this.

**Comment by AArnott** [comment]
What is the purpose of your nuget package though? I see it packages up your .exe, which probably doesn't make sense to reference from a consuming project. Should these all be in the tools folder instead  of the lib folder? That would make the fact that you bundled all your depenencies into one folder make sense.

**Comment by AArnott** [comment]
Ah, I see it's for squirrel. I'm reading up on that now.

**Comment by KirillOsenkov** [comment]
Keep in mind that Squirrel expects lib\net45 strict: 
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/2-packaging.md#packing

**Comment by AArnott** [comment]
Whoops. Then this issue should now track that the NuProj changeover made it lib\net46 instead. So we need to fix this back to net45.

**Comment by AArnott** [comment]
I'm working on fixing this, BTW.

**Comment by KirillOsenkov** [comment]
Thanks. After getting latest and git clean -xdf, I get this on nuget restore:

```
C:\MSBuildStructuredLog>nuget restore
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Feeds used:
  C:\Users\Kirill\AppData\Local\NuGet\Cache
  C:\Users\Kirill\.nuget\packages\
  https://api.nuget.org/v3/index.json

Restoring packages for C:\MSBuildStructuredLog\src\StructuredLogViewer\project.json...
Restoring packages for C:\MSBuildStructuredLog\src\StructuredLogger\project.json...
Restoring packages for C:\MSBuildStructuredLog\src\StructuredLogger.Tests\project.json...
Restoring packages for C:\MSBuildStructuredLog\src\MSBuildStructuredLogViewer\project.json...
Unable to resolve NuProj (≥ 0.10.48-beta-gea4a31bbc5) for .NETFramework,Version=v4.5.1.
Unable to resolve NuProj.Common (≥ 0.10.48-beta-gea4a31bbc5) for .NETFramework,Version=v4.6.
Unable to resolve NuProj.Common (≥ 0.10.48-beta-gea4a31bbc5) for .NETFramework,Version=v4.6.
Unable to resolve NuProj.Common (≥ 0.10.48-beta-gea4a31bbc5) for .NETFramework,Version=v4.6.
Generating MSBuild file StructuredLogger.Tests.nuget.props.
```

I'm still on Update 1, does it matter? Also I do have NuProj installed but it might be an old version. Do we need to specify NuProj in the Requirements section in readme?

**Comment by AArnott** [comment]
So net46 for a folder name seems to work just fine. Nothing to fix there.

I'll submit a PR to resolve the package restore failure.

**Comment by KirillOsenkov** [comment]
Did you try building the Squirrel installer and running that?

**Comment by AArnott** [comment]
yes. it worked great.
