### ISSUE TITLE
Lack of 'append' mode in BinaryLogger

### ISSUE THREAD

**Issue by codebyshankar** [KirillOsenkov/MSBuildStructuredLog#110]
Current State:
In certain cases build might involve many sln files. In such a case, it would be appropriate to have option to append all log entries to one binlog file.
This will allow one time comprehensive analysis using MSBuild Structured Log Viewer. By default the log option is overwrite. 

Note that default logger has Append option
/fileLoggerParameters:LogFile=MyLog.log;Append;
/l:FileLogger,Microsoft.Build.Engine;logfile=MyLog.log;append=true

Expected State:
Option to enable/disable append mode for BinaryLogger (StructuredLogger)

**Comment by KirillOsenkov** [comment]
I'm sorry I doubt I'll ever get to this due to how the file format works. I recommend you have a binlog per build, it'll be easier to analyzer that way.
