### ISSUE TITLE
TFS 2012 "The given assembly name or codebase was invalid."

### ISSUE THREAD

**Issue by brettenet** [KirillOsenkov/MSBuildStructuredLog#112]
Hello,

I am currently attempting to use this on TFS 2012. I have upgraded MSBuild as far as I can go on this server and am using the 14.0 build tools.

When I attempt to run a CI build using the following configuration I get a codabase invalid error.

/logger:StructuredLogger,"C:\Usersrandomguy\AppData\Local\Microsoft.Build.Logging.StructuredLogger.1.0.130\StructuredLogger.dll";"buildlog.xml"

MSBUILD : error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: StructuredLogger,C:\Users\randomguy\AppData\Local\Microsoft.Build.Logging.StructuredLogger.1.0.130\StructuredLogger.dll;buildlog.xml

Is it not possible to do this on my elderly server?

**Comment by KirillOsenkov** [comment]
Can you try using the latest version of StructuredLogger.dll? 1.0.130 is very old. Also try using the .buildlog extension instead of .xml (unless you're sure you want Xml).

Also, what's the .Net Framework version installed on the server?

**Comment by KirillOsenkov** [comment]
Do you have access to the machine? You can try debugging msbuild.exe with Visual Studio, attach, enable Break on all exceptions and see what is the underlying exception. Also try fuslogvw from admin cmd prompt to enable binding logs.

**Comment by KirillOsenkov** [comment]
Hi, I'm going to close this for now because there's nothing I can do about this issue. If you're still blocked with the latest version we can investigate further. The way to investigate would be to debug MSBuild (attach VS debugger to MSBuild.exe, enable first-chance exceptions and get the details from the exception when it happens).
