### ISSUE TITLE
The MSBuild dialog should include preview locations

### ISSUE THREAD

**Issue by onovotny** [KirillOsenkov/MSBuildStructuredLog#114]
Looking at the list here, it should also include preview locations: 
![image](https://user-images.githubusercontent.com/1427284/29692644-1a8bbe34-88ff-11e7-99c8-6c36c1cecad9.png)

**Comment by KirillOsenkov** [comment]
Good catch, I will fix this. As a workaround for now you can use the `...` button and browse to the MSBuild.exe of your choice.

**Comment by KirillOsenkov** [comment]
Fixed. Now using `vswhere.exe` to retrieve a list of installed VS 2017 instances.
