### ISSUE TITLE
Don't lock .binlog file and prompt to reload new file

### ISSUE THREAD

**Issue by flcdrg** [KirillOsenkov/MSBuildStructuredLog#115]
It would be nice if you could run a new build while the log viewer is examining an existing .binlog file.

Once the build finishes, the viewer could prompt to reload the updated file.

**Comment by KirillOsenkov** [comment]
Hmm, not sure how I feel about this. This would require an MSBuild change, and it would slightly complicate things there.

If you're using the viewer, you can already achieve this by pressing Shift+F6 (it will do a rebuild).

**Comment by flcdrg** [comment]
I was just thinking about the viewer. I'm closing this as it turns out it does seem to work this way for the most part. I thought I'd seen a build fail once because it couldn't write to .binlog but I haven't seen that again so it might have been unfortunate timing.
