### ISSUE TITLE
Failure to check for update if proxy requires authentication

### ISSUE THREAD

**Issue by thomaslevesque** [KirillOsenkov/MSBuildStructuredLog#118]
At work I'm behind an authenticated proxy. When I start MSBuildStructuredLog, I get the following error:

![image](https://user-images.githubusercontent.com/1864281/30031223-da5d8776-9190-11e7-972e-a29434635068.png)

There should be a way to enter credentials for the proxy.

**Comment by KirillOsenkov** [comment]
Interesting, I've never had to deal with this before, do you have any idea how to fix this?

**Comment by thomaslevesque** [comment]
Basically you need to catch the 407 error, prompt the user for proxy credentials, and retry. However, looking at the stack trace, it looks like the issue might be in Squirrel rather than MSBuildStructuredLog... Looking at the Squirrel code, it looks like it doesn't really do anything about proxies. All I can find is [this](https://github.com/Squirrel/Squirrel.Windows/blob/022a8053ad3a74257d869098d634a9f280b4a672/src/Squirrel/Utility.cs#L125-L129), and it's probably not related to this issue, because it creates a `WebClient` and the error above involves an `HttpClient`.

Anyway, since Squirrel doesn't set the proxy, it always uses the default proxy, so a possible solution for MSBuildStructuredLog would be this:

- catch the error during update and see if it's caused by a 407 response
- prompt the user for credentials and set `WebRequest.DefaultWebProxy.Credentials`
- retry the update

**Comment by thomaslevesque** [comment]
I have the beginning of a solution in [this branch](https://github.com/thomaslevesque/MSBuildStructuredLog/commits/issue118). However, when I build the app on my machine, I can't reproduce the issue. Also, Squirrel's behavior is weird when not running the installed app, so it's difficult to debug.

**Comment by KirillOsenkov** [comment]
I'll close this since I don't have a way to repro and it doesn't seem to be a problem.
