### ISSUE TITLE
Evaluation - add more levels

### ISSUE THREAD

**Issue by D0tNet4Fun** [KirillOsenkov/MSBuildStructuredLog#119]
All messages are displayed at the same level under Evaluation. It would be nice to know what happened during an import, and one way I can think of is to use another level. For instance:

Evaluation

* Importing project "C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.props" into project ...
   *  Property reassignment: $(MSBuildAllProjects)=...
* Project "$(MSBuildThisFileDirectory)Microsoft.NET.Sdk.VisualBasic.props" was not imported by ...
*  Importing project "C:\Program Files\dotnet\sdk\2.0.0\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets" ...
   *  Property reassignment: $(MSBuildAllProjects)=...
   * Overriding target "GetTargetFrameworkProperties" ...

This functionality, coupled with the search for a property, could be used to track the updates of a property as a result of importing projects.

**Comment by KirillOsenkov** [comment]
I don't think MSBuild gives us this information, although it's worth checking with them.

**Comment by KirillOsenkov** [comment]
See also https://github.com/Microsoft/msbuild/issues/2752

**Comment by KirillOsenkov** [comment]
This is now fixed.
