### ISSUE TITLE
Evaluation - colors for messages

### ISSUE THREAD

**Issue by D0tNet4Fun** [KirillOsenkov/MSBuildStructuredLog#120]
All messages under Evaluation are preceded by a gray icon. It would be easier to follow if different colors were used depending on the message. I.e.:

* use green icon for a successful import
* use red icon for a missed import
* use blue icon for a property reassignment
* use orange icon for target override
* use gray icon for a message that does not match any of the above

**Comment by KirillOsenkov** [comment]
this is a good idea

**Comment by KirillOsenkov** [comment]
FYI for now you can right-click on a project in the Evaluation section and choose Sort Children - it will sort them and group messages alphabetically. This may help a little bit.

**Comment by KirillOsenkov** [comment]
Evaluation looks neater now as most messages are now categorized in subfolders.
