### ISSUE TITLE
Chocolatey package for installing

### ISSUE THREAD

**Issue by flcdrg** [KirillOsenkov/MSBuildStructuredLog#121]
I've created a Chocolatey package to install the viewer.

https://chocolatey.org/packages/msbuild-structured-log-viewer

**Comment by flcdrg** [comment]
I am happy to maintain this package and keep it current, but another option would be to make it part of the build process (eg. if you've already automated pushing to nuget.org then it would be a similar process to that)

**Comment by KirillOsenkov** [comment]
Thanks!
Could you add me as a maintainer so I can upload? https://chocolatey.org/profiles/KirillOsenkov

What are the steps to upload a new version? Can you write a .cmd file that prepares a .nupkg given MSBuildStructuredLogViewer.exe?

If it was a simple .cmd I could run it myself every time I publish a new version.

**Comment by KirillOsenkov** [comment]
I've added the "Install from Chocolatey" badge on http://msbuildlog.com

**Comment by flcdrg** [comment]
I've added you as a maintainer.

If you're happy to push then I'll do another PR to include the package files and write a .ps1 (or .cmd if you really insist) to create a package

**Comment by KirillOsenkov** [comment]
.ps1 is fine :) Thanks!

**Comment by KirillOsenkov** [comment]
Cool, thanks for your help!

Now next time I'm making a release I will also upload `bin\Release\msbuild-structured-log-viewer.1.1.175.nupkg` to chocolatey.org.
