### ISSUE TITLE
High Contrast Theme in Windows 10

### ISSUE THREAD

**Issue by Mnuzz** [KirillOsenkov/MSBuildStructuredLog#129]
This app is unusable if you are using a high contrast theme in Windows 10. 

![image](https://user-images.githubusercontent.com/1613498/31313362-ed4c4bb4-ab95-11e7-8a10-55e77d74aace.png)

**Comment by KirillOsenkov** [comment]
I've added High Contrast support, please give it a try and let me know if I missed anything.

Thanks!
