### ISSUE TITLE
Investigate MSBuild task not logging its outputs

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#131]
MSBuild task seems to be special and we don't see Outputs of this task logged

**Comment by leonard-thieu** [comment]
Is there any workaround for this? Do you have any theories on what could be causing it?

**Comment by KirillOsenkov** [comment]
I didn't have time to investigate this yet. It's most likely an MSBuild issue. Not sure about a workaround.
