### ISSUE TITLE
Find location for initial property assignment

### ISSUE THREAD

**Issue by natemcmaster** [KirillOsenkov/MSBuildStructuredLog#133]
The logger makes it easy to find the location of property re-assignment ( #74 ), but what about the initial assignment? Is it possible to find the location setting the property for the first time? Currently trying to figure out why i'm getting an unexpected value for PlatformTarget, but can't figure out who is setting it (command line, environment, some errant file, etc.)

**Comment by KirillOsenkov** [comment]
I think this should be an MSBuild feature request. An initial set of all properties is printed when a project starts building (under the Properties folder). Currently there's no way to tell how a property appeared there.

**Comment by KirillOsenkov** [comment]
Filed https://github.com/Microsoft/msbuild/issues/2711

**Comment by natemcmaster** [comment]
Ok thanks!

**Comment by KirillOsenkov** [comment]
Closing for now as this is not a viewer bug. When MSBuild implements this and we need special viewer support, we can reactivate or file a new issue.
