### ISSUE TITLE
Update format to version 3: https://github.com/Microsoft/msbuild/pull/2722

### ISSUE THREAD

**Issue by cdmihai** [KirillOsenkov/MSBuildStructuredLog#134]

**Comment by nguerrera** [comment]
I hacked this to unblock myself on 15.6 investigation: https://github.com/KirillOsenkov/MSBuildStructuredLog/compare/master...nguerrera:version-3

**Comment by KirillOsenkov** [comment]
Ah, thanks. I should update it sooner than later...

**Comment by nguerrera** [comment]
cc @dsplaisted

**Comment by KirillOsenkov** [comment]
Committed to master, just need to release the Viewer app update.

**Comment by nguerrera** [comment]
Thanks!

**Comment by KirillOsenkov** [comment]
Deployed viewer 1.1.194.
