### ISSUE TITLE
Failed to show build log after build

### ISSUE THREAD

**Issue by gore01** [KirillOsenkov/MSBuildStructuredLog#135]
The error in the UI looks like
![image](https://user-images.githubusercontent.com/7627407/33021161-e97a265c-ce11-11e7-8276-fd96a98305cc.png)

This happens when I try to build in a single process mode (with flag **/m:1**)

**Comment by gore01** [comment]
Looks strange and it is possible that something is on my machine, because after reboot viewer is able to build and show log successfully.

**Comment by KirillOsenkov** [comment]
How did you build? From the Viewer app or from MSBuild command line?

**Comment by gore01** [comment]
Yep most of the time the error is reproduced if I build from the viewer. But sometimes it is also reproducible if I use MSBuild from the command line. In my case it is happen with single process build olnly when /m:1 flag is set.

**Comment by KirillOsenkov** [comment]
Could you build MSBuild Structured Log on your own machine? Comment out this line:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/master/src/StructuredLogViewer/HostedBuild.cs#L65

and after using it to build your project, if you see the error, send me the log file that is left after the build. I can try to investigate. Usually I delete the log file after building, but if you comment it out I should still see it.

**Comment by KirillOsenkov** [comment]
Alternatively, while it's building, copy the command line and use that command line from a console window. It will produce the log file which you can then send to me if it exhibits the problem.

**Comment by KirillOsenkov** [comment]
Also, `/m:1` is the default, you don't need to specify it explicitly. Only if you specify `/m` it will use the multi-proc build.
