### ISSUE TITLE
Parent projects triggered by the MSBuild task under that task

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#137]
@panopticoncentral do you have the logic I can reuse to correlate a project to its MSBuild task that triggered it?

**Comment by panopticoncentral** [comment]
You can take a look at the logic here: https://github.com/panopticoncentral/project-system-tools/blob/69165a9e07c47388d1b742677c266353be491421/src/ProjectSystemTools/LogModel/Builder/ModelBuilder.cs#L1008

Let me know if you want more context...

**Comment by KirillOsenkov** [comment]
This may be solved by https://github.com/microsoft/msbuild/pull/5013

**Comment by KirillOsenkov** [comment]
This is now fixed
