### ISSUE TITLE
Show the command-line used to launch the build

### ISSUE THREAD

**Issue by billti** [KirillOsenkov/MSBuildStructuredLog#142]
It would be very useful to see how the build was launched (e.g. what targets and properties were specified, etc.). Currently I only see the command-line for the tool itself, not for the actual build that created the log.

**Comment by KirillOsenkov** [comment]
MSBuild should log these, then they'll appear in all loggers, including the binary logger.

Filed an MSBuild issue here: 
https://github.com/Microsoft/msbuild/issues/2810

Thanks for the suggestion, it's a good idea!
