### ISSUE TITLE
Do not clear search text when reloading file

### ISSUE THREAD

**Issue by pakrym** [KirillOsenkov/MSBuildStructuredLog#143]
In edit run debug loop it's useful to keep search text.
It would be even more useful to expand the same node if possible.

**Comment by KirillOsenkov** [comment]
I've implemented preserving search text on Shift+F6 here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/7beb4d106838d68230559e5be80ef55d014c1fec

I wonder what is the unique identifier of a node that you could use it to locate an equivalent node in a different build?

**Comment by KirillOsenkov** [comment]
I'm going to close this one and filed a separate (much harder) issue about expanding the same node:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/145
