### ISSUE TITLE
System.InvalidOperationException when building a solution file and logging it to an XML format

### ISSUE THREAD

**Issue by jswanso** [KirillOsenkov/MSBuildStructuredLog#152]
When trying to build a solution file and log to an XML file format I get the following error:

System.InvalidOperationException: The Writer is closed or in error state.
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteEndElement()
   at Microsoft.Build.Logging.StructuredLogger.XmlLogWriter.WriteNode(Object node)
   at Microsoft.Build.Logging.StructuredLogger.XmlLogWriter.Write(Build build, String logFile)
   at Microsoft.Build.Logging.StructuredLogger.Serialization.Write(Build build, String filePath)
   at Microsoft.Build.Logging.StructuredLogger.StructuredLogger.Shutdown()

Only a small portion of the build log actually makes it into the XML file before the error occurs (i.e. only ~350 lines when I would expect thousands). Logging to a binary *.buildlog file works fine when building for the same solution. Logging to an XML file for a project level build works fine.

I suspect the XML writer is running into some unexpected data. Issue #30 provided some helpful insight, though it must be something else with the data since a fix exists for that issue.

This issue happens in both the GUI when saving to an XML file and when using a command line.

Here is the command line that I ran that created the error.

msbuild C:\Justin\vsprojects\BasicWebProject\BasicWebProject.sln /t:clean /v:diag /noconlog /logger:StructuredLogger,C:\Users\jjswanso\AppData\Local\MSBuildStructuredLogViewer\app-1.1.224\StructuredLogger.dll;MyBuild01.xml

Build Engine version 14.0.25420.1

The last piece of XML information written was the parameters for the MSBuild task under the clean target. It fails to write the Global Properties and everything thereafter. I would try to debug this through the code, but I don't have VS 2017 running on my machine ATM.

![image](https://user-images.githubusercontent.com/35145633/34789908-fa1b5822-f60d-11e7-9ecf-b7df206ccf8d.png)

**Comment by KirillOsenkov** [comment]
Logging directly to .xml isn't well tested at all. Ideally you should be using the latest MSBuild and the `/bl` (BinaryLogger) option. If you have to use MSBuild 14, you can still use the BinaryLogger, or the StructuredLogger and log to .buildlog (which is more supported). 

Logging directly to .xml will also significantly slow down your build.

If you'd like XML, just open the .binlog or .buildlog in the viewer, and use the Save As option to save as XML.

All that said, the bug is valid and I'll try to investigate to see what happens.

**Comment by KirillOsenkov** [comment]
Also, if you're saying that opening the .buildlog and then saving in the viewer as .xml crashes as well, would it be possible for you to share the .buildlog file so I can try to save it as XML to see the crash?

**Comment by jswanso** [comment]
Yes, opening up the .buildlog in the viewer and then saving it as .XML has the same issue. That build log has a lot of personal info...let me see if sending you it is going to be an issue.

**Comment by jswanso** [comment]
I emailed you the file.

**Comment by KirillOsenkov** [comment]
Thanks, found the problem and fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/9edb3e49ede233e3a17f87f7d46a9d986a9062a4
