### ISSUE TITLE
Sequence contains more than one element

### ISSUE THREAD

**Issue by FroggieFrog** [KirillOsenkov/MSBuildStructuredLog#153]
Error is not logged in "%localappdata%\Microsoft\MSBuildStructuredLog\LoggerExceptions.txt" and only shown in a message box, when opening a log.
The log nor the mesage box does contain a version number.
Language of system is german.
Version: 1.1.224

Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.InvalidOperationException: Die Sequenz enthält mehr als ein Element.

   bei System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)

   bei Microsoft.Build.Logging.StructuredLogger.MessageTaskAnalyzer.Analyze(Task task) in C:\MSBuildStructuredLog\src\StructuredLogViewer\Analyzers\MessageTaskAnalyzer.cs:Zeile 9.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 182.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 54.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 56.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 56.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 56.

   bei Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) in C:\MSBuildStructuredLog\src\StructuredLogViewer\BuildAnalyzer.cs:Zeile 31.

**Comment by KirillOsenkov** [comment]
Any chance you could share the log file? Per e-mail or here if it's not private.

**Comment by FroggieFrog** [comment]
As I said: There was no log file created. Only the pasted message in a message box.

**Comment by KirillOsenkov** [comment]
Thanks, I've fixed this in the latest commit. I will publish an update in a few days, you should see the fix there.
