### ISSUE TITLE
tmp_proj doesn't get evaluation Properties+Items folders

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#159]
In our vs-platform repo when I run `MSBuild vseditor.csproj /bl` and open the MSBuild.binlog file, the properties and items folders under the `*.tmp_proj` project are missing (but present for other projects). 
See here:
![image](https://user-images.githubusercontent.com/3548/36515748-c2dc8e10-172f-11e8-9adb-56c8b7f32d8a.png)

But when I use the older command syntax for logging (`"C:\Program Files (x86)\Microsoft Visual Studio\pubrelease\MSBuild\15.0\Bin\MSBuild.exe" D:\git\VS-Platform\src\Editor\Consolidated\VSEditor\VSEditor.csproj /t:Rebuild /v:diag /nologo /noconlog /logger:StructuredLogger,"C:\Users\andarno\AppData\Local\MSBuildStructuredLogViewer\app-1.2.5\StructuredLogger.dll";"C:\Users\andarno\AppData\Local\Temp\MSBuildStructuredLog-16600.buildlog"`, the properties and items folder *do* show up.

**Comment by KirillOsenkov** [comment]
I've seen this before but could never track it down. My hypothesis is that this is something in MSBuild, under some circumstances this is null:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/1b21660db7949d34057160e88d8c559412563e19/src/StructuredLogger/BinaryLogger/BuildEventArgsWriter.cs#L225

**Comment by KirillOsenkov** [comment]
Probably related to https://github.com/dotnet/msbuild/issues/3616

**Comment by KirillOsenkov** [comment]
This should be fixed by https://github.com/dotnet/msbuild/pull/6287

**Comment by KirillOsenkov** [comment]
Fixed and should appear in 16.10.
