### ISSUE TITLE
Build failure:

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#16]
@AArnott off the top of your head, do you know what's wrong here?

git clean, nuget restore, msbuild, I get this;

```
CreatePackage:
  C:\Users\Kirill\.nuget\packages\NuProj\0.10.48-beta-gea4a31bbc5\tools\NuGet.e
  xe pack obj\Debug\MSBuildStructuredLogViewer.nuspec -OutputDirectory obj\Debu
  g\ -NoPackageAnalysis -NoDefaultExcludes
C:\Users\Kirill\.nuget\packages\NuProj\0.10.48-beta-gea4a31bbc5\tools\NuProj.ta
rgets(525,5): error : The replacement token 'GitCommitIdShort' has no value. [C
:\MSBuildStructuredLog\src\MSBuildStructuredLogViewer\MSBuildStructuredLogViewe
r.nuproj]
```

**Comment by AArnott** [comment]
That would happen if NB.GV isn't imported, or if you've overridden a target or a property that NB.GV sets that provides this token's value.
[This](https://github.com/AArnott/Nerdbank.GitVersioning/blob/e01e97f3a3f4b564293ada38591b22f61ca4d291/src/Nerdbank.GitVersioning.NuGet/build/NerdBank.GitVersioning.targets#L143) is where that value is supported by NB.GV.

I can take a look tonight or tomorrow morning.

**Comment by KirillOsenkov** [comment]
What are .nuget.targets files? I see one for C:\MSBuildStructuredLog\src\StructuredLogger\StructuredLogger.nuget.targets
but I don't see one for the NuProj project. This would explain why NB.GV isn't working for NuProj?

Reminder: I'm on Update 1. Is this significant?

**Comment by AArnott** [comment]
NuGet restore automatically creates nuget.targets and nuget.props for project.json projects as its way to adding imports to your project.
For packages.config projects, imports are added directly to the project file, but project.json avoids this requirement by adding these files to the folder and then a NuGet extension to MSBuild picks them up automatically.
[NuGet.exe 3.4.3 has a bug](NuGet/Home#2711) where it doesn't generate these files for NuProj. I recommend you use NuGet 3.3.0. It's the latest version that works reliably well.

**Comment by AArnott** [comment]
The [appveyor build](https://ci.appveyor.com/project/AArnott/msbuildstructuredlog/build/1.0.1) confirms it works as-is. You're just using a broken version of nuget.exe.

**Comment by KirillOsenkov** [comment]
Wow, thanks. Appveyor is awesome. I'll wait for 3.4.4 to be released. I'll keep this issue open so that folks who run into this can see it.

**Comment by AArnott** [comment]
Yes, it is. You might consider adding an appveyor build status badge on your readme file.

**Comment by KirillOsenkov** [comment]
Added, thanks a lot for your help.

**Comment by KirillOsenkov** [comment]
Nuget was now updated to 3.4.4 so I'm closing this issue.
