### ISSUE TITLE
Preprocess view of a project with references shows imports that aren't real

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#160]
Similar to the repro in #159, in that this is an `MSBuild /bl vseditor.csproj` scenario, when I use the "Preprocess" command on VSEditor.csproj, I see _many_ imports that make no sense at all. It would seem that VSEditor.csproj is importing the `*.csproj.nuget.g.props` files from all the projects it references. But this is certainly not happening, as `MSBuild vseditor.csproj /pp:out.xml` will attest. It's clear that something in the log (or the viewer?) is messed up.

**Comment by KirillOsenkov** [comment]
The viewer is showing all the imports, regardless of whether they were actually imported during the build.

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/dbeba0b422e11dc05045afab914462e3f5512562

**Comment by KirillOsenkov** [comment]
Oops, wrong issue.

**Comment by KirillOsenkov** [comment]
I think I may have fixed this with https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/aa83ca34424c3c87bcd4fdda43cd443b24310749
