### ISSUE TITLE
Missing imported *.properties files in the Files view

### ISSUE THREAD

**Issue by GerhardSiemens** [KirillOsenkov/MSBuildStructuredLog#161]
We are importing some *.properties files and also some *.targets files in our Visual Studio *.csproj:

	<Import Project="$(CommonBuildHome)xxx.Common.CSharp.targets" />
	<Import Project="$(CommonBuildHome)xxx.yyy.properties" />

*.properties files are mostly used for defining some Properties like here:
	
	<PropertyGroup>
		<NewProperty>True</NewProperty>
	</PropertyGroup>

In the Files view we can see all the "*.targets" files but not the "*.properties" files. Also the Find in Files View does not search inside the *.properties files. Therefore we can not see why some property has not the value we await.

**Comment by KirillOsenkov** [comment]
I think the correct file extension is .props, not .properties. Could you try to rename one of your files to have the .props extension and see if it gets included?

**Comment by GerhardSiemens** [comment]
Hi Kirill,

I did rename one of my *.properties to *.props and have imported this file. I can see, that my running build did “execute” this file (because a see the property I added inside the log. But nevertheless I can see the *.props file inside the Files View and the Find In Files View does also not take care of this file.

You can see it in the screen shot.

In the screen shot you can also see, that there is a *SDKReverence.props. But that is not the the file I have renamed! And it is the only one I can see in the Files View.


[cid:image001.png@01D3BAE9.C4509CC0]


With best regards,

Gerhard Heijenga

Von: Kirill Osenkov [mailto:notifications@github.com]
Gesendet: Dienstag, 13. März 2018 16:14
An: KirillOsenkov/MSBuildStructuredLog
Cc: Heijenga, Gerhard (ext) (PD PA AE STS DH 3); Author
Betreff: Re: [KirillOsenkov/MSBuildStructuredLog] Missing imported *.properties files in the Files view (#161)


I think the correct file extension is .props, not .properties. Could you try to rename one of your files to have the .props extension and see if it gets included?

**Comment by KirillOsenkov** [comment]
Hmm, weird. I've made a simple repro on my machine and it works fine:
![image](https://user-images.githubusercontent.com/679326/37353738-3370e852-269d-11e8-9263-c220a238e6ca.png)

Could you try creating a simple test .proj like the above and test it on your machine?

```
<Project>
  <PropertyGroup>
    <X>-2010</X>
    <CommonBuildHome>C:\temp\</CommonBuildHome>
    <One>$(CommonBuildHome)1.properties</One>
  </PropertyGroup>
  <Import Project="$(CommonBuildHome)1.properties" />
  <Target Name="Build">
    <Message Text="$([System.Math]::Max($(X), 0))" Importance="high" />
  </Target>
</Project>
```

```
<Project>
  <PropertyGroup>
    <Prop>SET!!!</Prop>
  </PropertyGroup>
</Project>
```

**Comment by GerhardSiemens** [comment]
… I mad some changes to your test.proj because the Msbuild is crashing by the Math statement. Please, find the three proj’s attached to this eMail.

In the screen shots you can see the results:

[cid:image005.png@01D3BAF8.9DA728F0]

[cid:image001.png@01D3BAF8.04842060]


[cid:image002.png@01D3BAF8.04842060]

[cid:image003.png@01D3BAF8.5A0D6780]

[cid:image004.png@01D3BAF8.5A0D6780]





Von: Kirill Osenkov [mailto:notifications@github.com]
Gesendet: Dienstag, 13. März 2018 17:03
An: KirillOsenkov/MSBuildStructuredLog
Cc: Heijenga, Gerhard (ext) (PD PA AE STS DH 3); Author
Betreff: Re: [KirillOsenkov/MSBuildStructuredLog] Missing imported *.properties files in the Files view (#161)


Hmm, weird. I've made a simple repro on my machine and it works fine:
[image]<https://user-images.githubusercontent.com/679326/37353738-3370e852-269d-11e8-9263-c220a238e6ca.png>

Could you try creating a simple test .proj like the above and test it on your machine?

<Project>

  <PropertyGroup>

    <X>-2010</X>

    <CommonBuildHome>C:\temp\</CommonBuildHome>

    <One>$(CommonBuildHome)1.properties</One>

  </PropertyGroup>

  <Import Project="$(CommonBuildHome)1.properties" />

  <Target Name="Build">

    <Message Text="$([System.Math]::Max($(X), 0))" Importance="high" />

  </Target>

</Project>

<Project>

  <PropertyGroup>

    <Prop>SET!!!</Prop>

  </PropertyGroup>

</Project>

**Comment by KirillOsenkov** [comment]
Sorry just to let you know if you reply to GitHub per email your attachments are lost :)

Judging by the fact that your MSBuild crashes on that snippet I recommend you update to MSBuild 15.6 if possible. Basically update to the latest Visual Studio 2017.

**Comment by GerhardSiemens** [comment]
Because of restrictions in the environment here I can not update to MSBuild 15.6 :-(

But here is the code:
1.properties:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MyProp1>SET!!!</MyProp1>
  </PropertyGroup>
</Project>
```

2.props:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MyProp2>Also SET!!!</MyProp2>
  </PropertyGroup>
</Project>
```

StructurLoggerBug.csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <X>-2010</X>
    <CommonBuildHome>C:\GH\Temp\EPNuget\</CommonBuildHome>
    <One>$(CommonBuildHome)1.properties</One>
  </PropertyGroup>
  <Import Project="$(CommonBuildHome)1.properties" />
  <Import Project="$(CommonBuildHome)2.props" />
  <Target Name="Build">
	<Message Text="Trees that are slow to grow bear the best fruit - Moliere"></Message>
<!-- <Message Text="$([System.Math]::Max($(X), 0))" Importance="high" /> -->
  </Target>
</Project>
```
And here are the screenshots:
![image](https://user-images.githubusercontent.com/32329856/37392225-d5b3cdc0-276d-11e8-851d-9bd9a9fbfe56.png)

![image](https://user-images.githubusercontent.com/32329856/37392241-e02b69ca-276d-11e8-8762-a07957fd8592.png)

![image](https://user-images.githubusercontent.com/32329856/37392251-e9586822-276d-11e8-8c66-5057675be9cc.png)

**Comment by GerhardSiemens** [comment]
I have taken another try on a nother machine and the good news is, that with MSBuild 15.0 the *.props and also the *.properties files will be shown in the "Files View" and also be searchable in the "Find in Files View".

![image](https://user-images.githubusercontent.com/32329856/37510747-7df2b9e4-28fc-11e8-8766-907e7dbde18c.png)

But would be nice. if this would be also when MSBuild 14.x will be taken.

**Comment by KirillOsenkov** [comment]
Ah yes, now I understand. Yes, to properly embed all files at least MSBuild 15.3 is needed. Unfortunately it’s not possible to work around. MSBuild 14 just doesn’t have the right events.
