### ISSUE TITLE
Link log to timeline

### ISSUE THREAD

**Issue by dickvdm** [KirillOsenkov/MSBuildStructuredLog#162]
When you have selected for instance a project item in the Log section, and click on the Timeline, then the  same project item is selected in the Timeline section as well.

This is very helpful when you have a log file with many (parallel) projects in it. 

Btw, the link the other way around is there (when you click on for instance a project in the Timeline section, then the corresponding project in the Log section is highlighted)

**Comment by KirillOsenkov** [comment]
Good idea. I’ll do it when I have time.

**Comment by KirillOsenkov** [comment]
Done!
