### ISSUE TITLE
Allow opening partial binlogs

### ISSUE THREAD

**Issue by pakrym** [KirillOsenkov/MSBuildStructuredLog#165]
If msbuild crashed or hung trying to open binlog `System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'` message would be displayed without showing any events.

Displaying events that were already read might be useful to figure out the cause of the issue.

**Comment by KirillOsenkov** [comment]
Do you happen to have a .binlog that is corrupted like that? So I can experiment.

**Comment by KirillOsenkov** [comment]
This is now partially fixed, however the entire target graph for the project that crashed won't be displayed. Not sure if I can work around that.

**Comment by KirillOsenkov** [comment]
I doubt I can do much more if the binlog is truncated.
