### ISSUE TITLE
Preprocess order incorrect for SDK projects

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#173]
It seems like Sdk.targets should be inserted after the body of the project, but the preprocessed view shows it as before:

![image](https://user-images.githubusercontent.com/679326/40502734-b692a082-5f40-11e8-85f9-2aac4968dc1a.png)

**Comment by jeffkl** [comment]
Implicit imports don't actually exist in the project so we decided to set their location to null (0,0).  Our preprocessor has to fix up the order for it to look right.

https://github.com/Microsoft/msbuild/blob/b57bd10b51245b980f5e5ad16773ccc40cc9d1a5/src/Build/Evaluation/Preprocessor.cs#L186

https://github.com/Microsoft/msbuild/blob/b57bd10b51245b980f5e5ad16773ccc40cc9d1a5/src/Build/Evaluation/Preprocessor.cs#L212

**Comment by KirillOsenkov** [comment]
Oh good. Maybe I should just do the same thing.

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/dbeba0b422e11dc05045afab914462e3f5512562
