### ISSUE TITLE
MaxVersion metadata isn't desplayed on SuggestedBindingRedirects items

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#176]
I'm not sure what the general case is for this issue (ie when else it would occur), but I'm not getting the MaxVersion metadata displayed on SuggestedBindingRedirect items (as OutputItems for ResolveAssemblyReference or parameters to the GenerateBindingRedirects task).

From a verbose text log:

```
  Output Item(s): 
      SuggestedBindingRedirects=
          System.IO.Compression, Culture=neutral, PublicKeyToken=b77a5c561934e089
                  MaxVersion=4.2.0.0
          System.Diagnostics.StackTrace, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  MaxVersion=4.1.0.0
          System.Xml.XPath.XDocument, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  MaxVersion=4.1.0.0
          System.Diagnostics.Tracing, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                  MaxVersion=4.2.0.0
```

However, this is what I get in structured log viewer (the text is via "Copy Subtree" but this also matches what is displayed in the visual tree):

```
SuggestedBindingRedirects
    System.IO.Compression, Culture = neutral, PublicKeyToken=b77a5c561934e089
    System.Net.Http, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.IO.Compression.ZipFile, Culture = neutral, PublicKeyToken=b77a5c561934e089
    System.Runtime.Serialization.Primitives, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Diagnostics.Tracing, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Xml.XPath.XDocument, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Diagnostics.StackTrace, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Globalization.Extensions, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Net.Sockets, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Security.SecureString, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Threading.Overlapped, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Data.Common, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
    System.Security.Cryptography.Algorithms, Culture = neutral, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by KirillOsenkov** [comment]
Oh, I bet it's the parsing logic here: 
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/master/src/StructuredLogger/Construction/ItemGroupParser.cs#L68

Getting confused because the string with MaxVersion is indented 16 spaces, and the previous level is 8 spaces.

Can you send me the .binlog with this so I can debug? 

This is scary, who knows how much more info we're missing/hiding. Great catch! And I'm happy that it's likely a bug in the viewer, which means it'll be easy to fix.

**Comment by KirillOsenkov** [comment]
Fix available.

Before:
![image](https://user-images.githubusercontent.com/679326/41746448-32766de4-755f-11e8-90a4-a59e0de64509.png)

After:
![image](https://user-images.githubusercontent.com/679326/41746457-3db56728-755f-11e8-9016-5e11529d54a9.png)

**Comment by KirillOsenkov** [comment]
Wow, this was a bad bug. I imagine it took a lot of time and effort to investigate this and find that it's a viewer bug. Thanks for the effort @dsplaisted and I'm sorry if you wasted time on this.

It should be much better now, we were losing a lot of important metadata. Any time there was a `=` in the item name we were interpreting it as a property.

The fix should be deployed now. Start MSBuild Structured Viewer from the start menu and let it update to 1.2.17, then restart. Hope this helps!
