### ISSUE TITLE
Evaluation properties only displayed for first of several multi-targeting frameworks

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#178]
For a .NET SDK project that multitargets with `$(TargetFrameworks)`, only the *first* of these frameworks to build have a Properties folder that has MSBuild evaluation properties listed. The rest only have the Globals subfolder in them:

First target framework:
![image](https://user-images.githubusercontent.com/3548/42281749-57ce7600-7f59-11e8-8b2a-c5c3c73e9aec.png)

Subsequent target framework:
![image](https://user-images.githubusercontent.com/3548/42281769-64c3ca54-7f59-11e8-929c-2c3b1fc6ca54.png)

**Comment by KirillOsenkov** [comment]
May be related to https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/159

**Comment by KirillOsenkov** [comment]
It's most likely https://github.com/dotnet/msbuild/issues/3616

**Comment by KirillOsenkov** [comment]
This should be fixed by https://github.com/dotnet/msbuild/pull/6287
