### ISSUE TITLE
Ability to open logs that expand to > 2 GB

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#181]
See related https://github.com/Microsoft/msbuild/issues/3534

@xiangfan-ms mentions the `ReadRecords` method maybe needs to change to expand to disk instead of expanding in memory.

**Comment by xiangfan-ms** [comment]
I'm able to workaround the issue by using Replay :-)

**Comment by KirillOsenkov** [comment]
I think this should be fixed by now. If not, please send me a binlog privately and repro steps and I can investigate further.
