### ISSUE TITLE
Display TFM and other build dimensions next to the Project node

### ISSUE THREAD

**Issue by cdmihai** [KirillOsenkov/MSBuildStructuredLog#189]
There are some build dimension properties which greatly affect how a build goes. Showing these next to the project node would help a lot with log navigation.

Some build dimensions:
- $(TargetFramework) - this one would help a lot to distinguish inner and outer builds
- $(Configuration)
- $(Platform)
- $(RuntimeIdentifier)

**Comment by KirillOsenkov** [comment]
I displayed the TFM, but hesitant to add others, as it's already too crowded.

![image](https://user-images.githubusercontent.com/679326/103393062-9a2c0e00-4ad5-11eb-9178-5f3f3d43ff0d.png)
