### ISSUE TITLE
Receiving HttpRequestException "status code does not indicate success: 403" on launch

### ISSUE THREAD

**Issue by aapalm** [KirillOsenkov/MSBuildStructuredLog#194]
Receiving the following exception every time I open Msbuild Structured Log Viewer

![image](https://user-images.githubusercontent.com/39351273/45245359-e7ef2d80-b2b0-11e8-8070-6cf26c7b71b1.png)

Looks related to Squirrel... Also tried running as administrator with same exception

**Comment by aapalm** [comment]
Updating to 1.2.44 seems to have fixed this as well

**Comment by KirillOsenkov** [comment]
Thanks for letting me know! I'll close this but don't hesitate to let me know if something goes wrong.
