### ISSUE TITLE
Seems to have troubling building solutions that use different versions of MSBuild

### ISSUE THREAD

**Issue by davkean** [KirillOsenkov/MSBuildStructuredLog#2]
Built Roslyn.sln and then build ProjectSystem.sln from the UI, and get:

```
C:\Users\davkean\.nuget\packages\Microsoft.VisualStudio.ProjectSystem.SDK.Tools\15.0.183-pre\build\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets(53,5): error MSB4127: The "XamlRuleToCode" task could not be instantiated from the assembly "C:\Users\davkean\.nuget\packages\Microsoft.VisualStudio.ProjectSystem.SDK.Tools\15.0.183-pre\build\Microsoft.VisualStudio.ProjectSystem.Sdk.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.Build.NonShippingTasks.XamlRuleToCode' to type 'Microsoft.Build.Framework.ITask'. [C:\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
```

I'm guessing first MSBuild to load wins?

**Comment by leppie** [comment]
Not sure if related, but trying to build a VS2008 solution fails, where it does work fine from the command line using MSBuild from VS2015.

**Comment by KirillOsenkov** [comment]
Here's what I learned. The way I call MSBuild might be not working well.

I load MSBuild.exe from the GAC (and not from C:\Program Files(x86)\MSBuild\14.0\bin). In the GAC, there is no app.config with binding redirects. So I bring my own app.config with the same redirects as MSBuild 14.0. However these won't play nice with MSBuild 15.

Also if you use /m switch, MSBuild is going to start other MSBuild node processes from MSBuild.exe that's in the GAC, again missing all binding redirects.

I host MSBuild in-proc to get live access to the logger object so I can immediately get the data structure without flushing it to disk.

Maybe I should switch to starting MSBuild.exe process from the correct location, force the logger to flush the log to disk, wait for process to exit and then pick up the log from disk.

@leppie depending on what errors you're seeing you might be having a different issue. If interested to investigate further, feel free to file a separate issue.

**Comment by KirillOsenkov** [comment]
I've switched it to shell out to MSBuild.exe out-of-proc, so this issue should be solved.
Please reactivate if you still see problems.
