### ISSUE TITLE
[Feature Request] Check Inputs/Outputs timestamp invariant

### ISSUE THREAD

**Issue by garuma** [KirillOsenkov/MSBuildStructuredLog#204]
In the same fashion as the other analyzers, add an entry for targets that break their inputs/outputs invariant.

Those are cases where a target runs because some of its inputs are more recent than its outputs but by the end of the target the inputs are still more recent than the outputs (which should not be the case).

This is a widespread problem because a lot of targets authors use some variant of a `CopyIfChanged` mechanism that break this invariant.

**Comment by KirillOsenkov** [comment]
Unfortunately .binlog doesn't capture the timestamps of files, however this is something MSBuild itself could do during the build.

Filed https://github.com/Microsoft/msbuild/issues/3817 and closing this one.
