### ISSUE TITLE
Partly hidden label text for update

### ISSUE THREAD

**Issue by GerhardSiemens** [KirillOsenkov/MSBuildStructuredLog#215]
After starting Structured Log Viewer the program tries to download new version (if any). The label text, that new version will be installed after restart, is partly hidden.

![textlabelforversionupdateispartiallyhidden](https://user-images.githubusercontent.com/32329856/47620918-91ec7880-daf0-11e8-9bcc-7c4cb217a631.png)

**Comment by KirillOsenkov** [comment]
Thanks for logging. What's your monitor height?

**Comment by GerhardSiemens** [comment]
I have a monitor resolution 1920 x 1080

May be you can use a grid with a gridsplitter.

**Comment by KirillOsenkov** [comment]
This is now fixed.
