### ISSUE TITLE
Opening a .binlog file causes a hang

### ISSUE THREAD

**Issue by DrewScoggins** [KirillOsenkov/MSBuildStructuredLog#216]
I have a build that produces a .binlog that when I try and open it with the viewer I get a consistent hang. It happens after I have opened it, searched for anything, and then double click on it. It will try and navigate to the thing I was searching for and then after a while hang. I have the .binlog file that this occurs on and have seen the hang on several machines running the latest viewer version.

**Comment by KirillOsenkov** [comment]
When you start the viewer (without opening any logs), can you try and uncheck this checkbox:

![image](https://user-images.githubusercontent.com/679326/47753923-74d1ba00-dc56-11e8-9dfb-415b9f0547e4.png)

Would be interesting to see if the hang goes away.

**Comment by DrewScoggins** [comment]
It did make the hang go away. I noticed this right after I filed the issue.

**Comment by KirillOsenkov** [comment]
OK then I'm going to close this as a known bug in WPF that I unfortunately can do nothing about. Thanks!
