### ISSUE TITLE
Feature request: Double writes during compilation

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#217]
The double write logger mostly operates by looking at the invocations of `CopyTask`. That's very effective but misses out on tasks like `Csc` and `Vbc`. 

More than once I've gotten bitten because we messed up our build scripts and suddenly started writing build output (DLL, XML, PDB) to the same place during a multi-targeted build. Wanted to add logic to detect this. 

I'm unsure if this is the right place or not. `CopyTask` is a built-in task hence we know what `CopyTask` is and what semantics it has. The `Csc` task though is not built-in, although it's about as close as can be. Hence unsure if this is too specific for this repository.

Happy to do the work here BTW. If this isn't the right place I'm just going to add it to Roslyn directly :smile:

**Comment by KirillOsenkov** [comment]
This looks like a good place and a good idea! You can infer writes from the Csc task like you describe. PRs welcome!

**Comment by jaredpar** [comment]
Thinking more about this: should such a PR include adding a new Csc and Vbc type (similar to CopyTask). If the support is getting baked in for double writes this seems to make sense here.

**Comment by KirillOsenkov** [comment]
Either way. Long term I was thinking of introducing derived types for some well-known types as I go, but you'd have to add support in quite a few places. I think it'd be easier to skip it for now. Let me know if you need help.
