### ISSUE TITLE
Auto update does not work

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#218]
First there is this:

![image](https://user-images.githubusercontent.com/489792/48316514-a3cf2080-e5b2-11e8-94a0-9aeea7d8c512.png)

Next appears this:

![image](https://user-images.githubusercontent.com/489792/48316518-bfd2c200-e5b2-11e8-9c14-dbd25a6e4a0b.png)

I do not know what is the exact message, because it is obscured by the popup, but I can guess it says that the app will be upgraded to the version 2.0.54 on the restart, but it never happens - the app always starts in 2.0.46 and always promises to upgrade itself.

**Comment by KirillOsenkov** [comment]
This is probably you're starting it by double-clicking the .binlog file.

Try starting it from the Windows Start Menu (search for MSB). 

There are two known bugs associated with the unfortunate behavior you're seeing. I'll fix them eventually but for now hopefully the workaround will work. Thanks for reporting.

**Comment by MarkKharitonov** [comment]
I was actually double clicking the setup.exe. Stupid me. It works, of course.

**Comment by MarkKharitonov** [comment]
Hi, Kirill.

Is it possible to ask you a question about msbuild events?

**Comment by KirillOsenkov** [comment]
It is certainly possible :) If you're on Twitter or Stackoverflow it's perhaps better though.

**Comment by KirillOsenkov** [comment]
Feel free to post the link here, I don't check StackOverflow.

**Comment by MarkKharitonov** [comment]
https://stackoverflow.com/questions/53300711/given-two-msbuild-log-events-x-and-y-where-x-timestamp-y-timestamp-is-it-true

https://stackoverflow.com/questions/53301962/is-it-true-that-projectstartedeventargs-targetnames-is-identical-for-all-the-c

Thank you.
