### ISSUE TITLE
Add import hierarchy. 

### ISSUE THREAD

**Issue by ljcollins25** [KirillOsenkov/MSBuildStructuredLog#219]
It would be nice to see how specific imports get included. Tree view would start at root project/solution of the build and show its imports as children. Then the imports of those first-level imports would be the children and so on.

**Comment by ljcollins25** [comment]
Just noticed this basically appears in the main (center) tree view. I still think it would be nice as an explicit tab.

**Comment by KirillOsenkov** [comment]
I think this is now implemented.
