### ISSUE TITLE
Empty Items created when metadata spans multiple lines

### ISSUE THREAD

**Issue by rainersigwald** [KirillOsenkov/MSBuildStructuredLog#224]
_From @jachin84 on November 29, 2018 1:20_

I'm attempting to create an ItemGroup with some additional metadata and when the metadata spans multiple lines I get empty items created. 

### Steps to reproduce
**Project file**
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="BuildAll" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>

  <!-- This Item Group defines all the Web Projects that need to be built and deployed -->
  <ItemGroup>
    <ProjectsFiles Include="Project1" />
    <ProjectsFiles Include="Project2" />
    <ProjectsFiles Include="Project3" />
  </ItemGroup>

  <Target Name="BuildAll" >
    <Message Text="Building Projects" Importance="high"/>

    <!-- Work out the correct project properties -->
    <ItemGroup>
      <_ProjectsFiles Include="@(ProjectsFiles)">
        <AdditionalProperties>
        AutoParameterizationWebConfigConnectionStrings=false;
        _PackageTempDir=Out\Dir;
        </AdditionalProperties>
      </_ProjectsFiles>
    </ItemGroup>

    <MSBuild Projects="$(MSBuildThisFileFullPath)"
             BuildInParallel="true"
             ContinueOnError="false"
             Targets="OutputMessage"
             Properties="ProjectName=%(ProjectsFiles.Identity)" />

  </Target>

  <Target Name="OutputMessage">
    <Message Text="Building Project $(ProjectName)" Importance="high"/>
  </Target>
</Project>
```

### Expected  behavior
![image](https://user-images.githubusercontent.com/2740855/49192874-b7f38a00-f3c8-11e8-89a7-84ae814dea05.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/2740855/49192885-c2ae1f00-f3c8-11e8-9058-07e6cb5e2e3a.png)

### Environment data
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856

OS info:
Windows 10 1809

_Copied from original issue: Microsoft/msbuild#3966_

**Comment by rainersigwald** [comment]
_From @dasMulli on November 29, 2018 5:57_

I believe this is a bug in the log viewer rather than msbuild. cc @KirillOsenkov 

```xml
    <Message Importance="high" Text="@(_ProjectsFiles->'%(Identity): %(AdditionalMetadata)')" />
```
or similar are fine.

**Comment by rainersigwald** [comment]
_From @jachin84 on November 29, 2018 6:33_

I think you might be right.

**Comment by KirillOsenkov** [comment]
Fixed by https://github.com/dotnet/msbuild/pull/6155
