### ISSUE TITLE
Files can no longer be viewed

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#228]
This started happening just a few days ago, I can only explain it by an auto update with a broken code.

I am no longer able to view the captured files. Searching them works and I can see them in the left pane. But double clicking a file no longer opens it. Neither does double clicking the elements like tasks in the right pane.

Clicking Open File in the popup menu crashes the log viewer.

**Comment by KirillOsenkov** [comment]
Do you have a .binlog that you can share with me? You can email “github at osenkov dot com”. What version are you using? Make sure you’re on 2.0.64.

Also share the contents of %localappdata%\Microsoft\MSBuildStructuredLog\LoggerExceptions.txt.

Thanks!

**Comment by MarkKharitonov** [comment]
I think I get it. I opened the log through the registered application, and the registration does not get updated as the software auto upgraded.
Let me register the new version and recheck. This is likely a false alarm.

**Comment by MarkKharitonov** [comment]
Yup, false alarm.
Sorry.

**Comment by KirillOsenkov** [comment]
No problem. There's a known bug in the updater where it doesn't update file associations to the latest version. So if you only ever open the viewer by double-clicking the .binlog files you never get the updater a chance to update file associations.

Starting the viewer from the Start Menu fixes that.
