### ISSUE TITLE
Add $propertyname and $propertyvalue to only search property names or values respectively

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#232]

**Comment by kzu** [comment]
I'd also like shortcuts like `$prop` and `$value` (values other than properties aren't all that useful, I guess). Alternatively, `$propv` (for value)

Would be awesome to have some completion in that search box ;)

**Comment by KirillOsenkov** [comment]
What would `$prop` do? Same as `$property`? Or same as `$propertyname`? Right now `$property` searches both names and values.

**Comment by kzu** [comment]
So, $prop for both, $propv and $propn for value and name respectively?

**Comment by KirillOsenkov** [comment]
sure! now just to implement it... :)

**Comment by KirillOsenkov** [comment]
Here's where it populates the fields to search for each node. For properties it populates both the name and the value here:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/16a12fb709ee475fb854667999d44b4bcac63dc8/src/StructuredLogViewer.Core/NodeQueryMatcher.cs#L229-L237

Here's where we parse the special `$property` search keyword into `TypeKeyword`:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/16a12fb709ee475fb854667999d44b4bcac63dc8/src/StructuredLogViewer.Core/NodeQueryMatcher.cs#L58

Examine the usages of `TypeKeyword` to see how nodes are matched by type.

**Comment by KirillOsenkov** [comment]
Here's what I'm thinking about the syntax:

 * Adding `$property` to a query still filters to all properties
 * `$property name=foo` should filter down to where name contains `foo`
 * `$property value=bar` should filter down to where value contains `bar`
 * Same should apply for `$metadata` since metadata is also a `NameValueNode` -- `$metadata name=foo` and `$metadata value=bar`
 * You could compose: `$property name=foo value=bar`

Not sure if we need a `$name` and `$value` or just `name=` and `value=` should be enough.

Since name and value are not typical type keywords, they're going to have to bit special. Maybe like the `under(...)` syntax, not sure.

**Comment by KirillOsenkov** [comment]
This is now done, thanks @AlexanderKapitanovski!

The syntax is:

`$property name=foo` and `$metadata value=bar`

**Comment by kzu** [comment]
Awesome!!
