### ISSUE TITLE
msbuild env variables

### ISSUE THREAD

**Issue by Trass3r** [KirillOsenkov/MSBuildStructuredLog#24]
Another env variable for your wiki is MSBUILDDISABLENODEREUSE=1 to dispose MSBuild instances after use.
In particular prevents zombie situations with multiple sets of MSBuild processes running.

**Comment by KirillOsenkov** [comment]
There's actually a command line option for that: /nodeReuse:false or /nr:false. Added it to the Wiki. Thanks!

**Comment by Trass3r** [comment]
Yes but with the env variable you always get it, also when building from Visual Studio :)

**Comment by KirillOsenkov** [comment]
Ah! That I didn't know. Good point. Added to the wiki. Thanks!
