### ISSUE TITLE
Msbuild command-line options should be preserved as defaults

### ISSUE THREAD

**Issue by Scottj1s** [KirillOsenkov/MSBuildStructuredLog#241]
I often find myself typing in "/p:platform=x86;configuration=release" for a new sln before building.  It would be nice if the contents of the custom msbuild params editbox could be preserved as a default for future slns.

**Comment by KirillOsenkov** [comment]
It does preserve it per-solution, but if you're opening/creating new ones then yes, it will just populate the default. 

Are you constantly opening new solutions? I thought it's not common that people would want to open a new solution.

**Comment by Scottj1s** [comment]
You're probably right.  Maybe simply changing the default to include platform/configuration in addition to /t:Rebuild, as I'm sure it's a common scenario (and easier to delete than to type in).

**Comment by KirillOsenkov** [comment]
I did fix it so you should default to the last arguments you've used instead of the hardcoded `/t:Build` when building a project/solution that you haven't built before. I'll deploy the fix soonish.

**Comment by Scottj1s** [comment]
Thanks!  This is such a powerful tool.  The best thing to add to my Windows dev arsenal since Linqpad.
