### ISSUE TITLE
Virus Total flagging malware from two engines

### ISSUE THREAD

**Issue by BanksySan** [KirillOsenkov/MSBuildStructuredLog#245]
Running the file through Virus Total, two engines flag this:

https://www.virustotal.com/#/file/65bf83036a72c37b8086d52b2ace9030035ac4a8c12ad3ca0387fade124c8451/detection

| Engine | Warning |
|---------|-----------------|
| McAfee-GW-Edition | BehavesLike.Win32.MultiPlug.wc |
| Trapmine                  | suspicious.low.ml.score |

**Comment by KirillOsenkov** [comment]
Unfortunately I don't know what to do about this, but thanks anyway for reporting!
