### ISSUE TITLE
binlog produced by VS extension do not include enough detail ?

### ISSUE THREAD

**Issue by GoldenCrystal** [KirillOsenkov/MSBuildStructuredLog#250]
Hello,

Let me start by thanking you for this wonderful tool that helped me many times already.
I'm not sure if this is is the right repository to ask this question, so feel free to redirect me to the right place..

I tried to use the "Project System Tools" extension (1.0.1.1927902) to analyze a build triggered by Visual Studio 2019 (16.1.5), as advised on the homepage here: http://msbuildlog.com/. (My build works as expected outside of Visual Studio, and does not consistently succeed when run inside VS)

However, when I tried to compare the build from Visual Studio with one started from MSBuild Structured Log Viewer, I noticed that the one from VS lacked a lot of details. Notably, All details regarding tasks that were executed by MSBuild were absent from the log. (e.g. Parameters, OutputProperties)

From an empty project I created to reproduce the issue, the result looks like this: (binlog vs structured log)
![msbuild-bin-log](https://user-images.githubusercontent.com/8518235/61362418-742f9100-a882-11e9-8b9d-cb7b20af1972.png)
![msbuild-structured-log](https://user-images.githubusercontent.com/8518235/61362423-75f95480-a882-11e9-95ee-67dd3d5469a3.png)

After reading the homepage of the project, I was under the impression that MSBuild binlog was up to par with the StructuredLogger used by MSBuild Structured Log Viewer, but my experience seems to indicate otherwise.

Do you know, if there is a way to increase the level of detail of the log produced by the "Project System Tools" extension, or possibly use the external StructuredLogger inside Visual Studio ?

Thanks

**Comment by KirillOsenkov** [comment]
Hmm, is it Verbosity related? @panopticoncentral

https://github.com/dotnet/project-system-tools/issues

**Comment by GoldenCrystal** [comment]
I just set the logging level to "diagnostic" inside VS, and the results are quire surprising to me:

- It seems to have increased the verbosity in the binlog, but messages are not displayed properly by MSBuild Structured Log Viewer (Also, I can't tell if everything is present, but more is displayed)
- That could be because… All messages are in french ? 😮 (NB: My VS installation runs in french, so that most certainly why)

![msbuild-bin-log-diagnostic](https://user-images.githubusercontent.com/8518235/61381725-c802a000-a8ab-11e9-9e5b-1318d1b12f67.png)

All of this is very weird to me. 😅
I was under the impression that binlogs always contained the maximum amount of details. Is it that the logs also include raw text messages (which would explain why they now display here), or that the format is somehow influenced by localization ? 🤔

**Comment by KirillOsenkov** [comment]
Ah, that explains it. Unfortunately the viewer only supports displaying English binlogs. There are quite a few places where we have to parse english text to recover structure and we’ve never adapted it to support localized strings.

Sorry!

**Comment by KirillOsenkov** [comment]
Press Space when you see the `...` to view the raw message.

**Comment by GoldenCrystal** [comment]
That works for those items, but the tree is kinda messed up: Some task input / output parameters are not displayed under the task node. They may be somewhere else or just totally missing. (I see a lot of detached task parameters under the root node)

Is it possible then, that the use of StructuredLogger.dll forces log messages to be output in English, while the buil-in binary log does not ? (And isn't it a bug if binary logs are culture sensitive ? 😥)

**Comment by KirillOsenkov** [comment]
There’s an issue on MSBuild to add an option to force it into English. Binlog just uses whatever language MSBuild logs in, and MSBuild is localized.

I should fix the viewer to properly detect the binlog language and parse it well. I didn’t have time to do it yet, unfortunately.

**Comment by GoldenCrystal** [comment]
I looked at the code and the language-specific parts seem already well isolated. I'd be happy to help you on that, at least for the french locale. (I just wonder how you can detect the language of a binlog)

Language differences aside, I can still notice differences between binlog and buildlog:
![msbuild-log-differences](https://user-images.githubusercontent.com/8518235/61406471-33646600-a8dc-11e9-80c8-9344eb1b1f70.png)
Left: binlog (VS), Right: buildlog (StructuredLogger)
Look for "Items", "DependsOnTargets" and the message under the highlighted task.
It seems that the "buildlog" is still more detailed. 🤔 (Maybe because it includes the source of all projects ?)

NB: I actually wished to provide a possible counter example that I noticed earlier today in the english versions, but it seems that MSBuild on my personal computer is all in french 😕

**Comment by KirillOsenkov** [comment]
Hmm no idea honestly. I’m on vacation until August 12, but I can start taking more serious look at this after I get back. Certainly looks like something else is off, beside the loc issue.

**Comment by KirillOsenkov** [comment]
I also notice that the left screenshot is missing all of the Evaluation messages.

**Comment by drewnoakes** [comment]
> I also notice that the left screenshot is missing all of the Evaluation messages.

Aren't they just higher up?

**Comment by KirillOsenkov** [comment]
@drewnoakes d’oh!

**Comment by KirillOsenkov** [comment]
@panopticoncentral mentioned somewhere that the problem is because in VS evaluation happens separately from design-time builds, and so we don't get any `ProjectImportedEventArgs`, and so we don't know which files to embed. I can't find __where__ he mentions this though.

**Comment by KirillOsenkov** [comment]
Localized binlogs are now supported starting with version 2.1.174. Try opening french binlogs and see if the tree looks better now. Also we've learned that you can set the codepage in cmd.exe by running `chcp 437` before invoking msbuild.exe /bl.

Note that this requires a change in MSBuild that logs the culture of the binlog which will appear in Visual Studio 16.7. Here's the change on the MSBuild side: https://github.com/dotnet/msbuild/pull/5426
