### ISSUE TITLE
Preprocessed view includes content from other files

### ISSUE THREAD

**Issue by davkean** [KirillOsenkov/MSBuildStructuredLog#254]
1. Open attached build log
2. Navigate to Evaluation -> c:\project-system\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj id:55
3. Right-click on that project and choose Preprocess

**Expected:** 
Only the proprocessed view of vbproj and all of its imports, similar to `msbuild /pp`: https://gist.github.com/davkean/f26b2930aa78c12ffb6a48dc5092cf4f.

**Actual:**
Includes content from other projects, such as https://gist.github.com/davkean/51c7e818dfedd5f4ee7b7812354b1058#file-logviewerpreprocess-xml-L747-L760.

[Build.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/3523819/Build.zip)

**Comment by KirillOsenkov** [comment]
OK this looks related to #269 and #273, and I might have a partial fix in:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/17d1efbab4777704496fc57961e72d02b0ad48aa

If you have an easy repro, would you be willing to try pull the latest viewer source, build from source and try it out?

**Comment by KirillOsenkov** [comment]
I've published 2.0.159 which will hopefully alleviate the issue. Would be nice if you could verify when you have a moment, thanks!

**Comment by KirillOsenkov** [comment]
I tried your scenario and it seems to be fixed.

**Comment by KirillOsenkov** [comment]
I filed https://github.com/microsoft/msbuild/issues/4926 to allow fully correct preprocessing
