### ISSUE TITLE
Feature request: Add task execution start time and end time

### ISSUE THREAD

**Issue by pmisik** [KirillOsenkov/MSBuildStructuredLog#255]
It would be useful to see when the task started and ended.
This is especially useful in case you try to figure out issue in some tool and you do correlation with some other log file like ProcMon or Wireshark.
It would narrow the area where you need to search issue in the other log.

**Comment by KirillOsenkov** [comment]
I've added a tool tip on the task duration label:

![image](https://user-images.githubusercontent.com/679326/71752683-d2eac600-2e34-11ea-8886-31eb82e39546.png)

The start time, end time and duration is also available from the Timeline view:

![image](https://user-images.githubusercontent.com/679326/71752695-e4cc6900-2e34-11ea-9913-766ee3cad980.png)
