### ISSUE TITLE
Exception: Couldn't acquire lock, is another instance running

### ISSUE THREAD

**Issue by ahdung** [KirillOsenkov/MSBuildStructuredLog#261]
when i first start, i got this exception:
![image](https://user-images.githubusercontent.com/12094247/65365855-c066cb00-dc4f-11e9-903c-b3e21964766c.png)

**Comment by KirillOsenkov** [comment]
Could you please close all instances (via Task Manager), start a new instance from Start Menu, wait for it to auto-update to the latest version (2.0.112), then restart the app again?

I've seen this happen sometimes but I don't know why it happens.

**Comment by ahdung** [comment]
I don't think there has anothor instance.
I close and reopen it, no exception now, few seconds later, it update to 2.0.112, all looks fine, thank you.
