### ISSUE TITLE
Windows Defender SmartScreen problems

### ISSUE THREAD

**Issue by vatsan-madhavan** [KirillOsenkov/MSBuildStructuredLog#272]
I know this was reported previously in #47, but the SmartScreen block has become more cumbersome now - it is no longer merely a dialog box that has to be overcome. 

I just tried installing msbuild log viewer on a new pc that's running Edge Chromium,  and I was taken to https://feedback.smartscreen.microsoft.com/feedback.aspx, where I was asked to fill out this form: 

![image](https://user-images.githubusercontent.com/20246435/68550623-4504d880-03b9-11ea-8d84-ad783858f39e.png)

Then I had to convince the browser to let me keep the file. 

![image](https://user-images.githubusercontent.com/20246435/68550654-7aa9c180-03b9-11ea-8f1a-c44ca8239c26.png)

And then finally I had to ask Windows nicely to let me run the installer. 

![image](https://user-images.githubusercontent.com/20246435/68550664-957c3600-03b9-11ea-8385-e0c6954b8899.png)

This seems like the only useful viewer for `msbuild /bl` - is there any chance this could be signed so that it doesn't have to go through a whole lot of warnings?

**Comment by KirillOsenkov** [comment]
We're working on getting a certificate, thanks for the detailed report!

**Comment by KirillOsenkov** [comment]
The installer is now signed, this should alleviate some of the pain you're seeing above.
