### ISSUE TITLE
Add folder level for analyzers.

### ISSUE THREAD

**Issue by JohanLarsson** [KirillOsenkov/MSBuildStructuredLog#277]
When building with `/p:ReportAnalyzer=true` it would be awesome if there was a way to collapse the tree per analyzer package.

I mean:
![image](https://user-images.githubusercontent.com/1640096/69699695-e34aab00-10e8-11ea-80ad-ca0e8af15fe5.png)

In the picture above a folder for grouping analyzers from StyleCop would be nice.

This is a really nice tool, thank you for it!

**Comment by KirillOsenkov** [comment]
Do you have a simple sample project that I could build as an example? Ideally if you paste the minimal .csproj file with the necessary NuGet PackageReferences it would make my life easier to reproduce this.

**Comment by JohanLarsson** [comment]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.113" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

For ^ it would be nice if there were folders for `Microsoft.CodeAnalysis.FxCopAnalyzers` and `StyleCop.Analyzers` showing total time and when expanded the times for the individual analyzers.

**Comment by KirillOsenkov** [comment]
Ah yes, like this? 

![image](https://user-images.githubusercontent.com/679326/71773713-c9d22580-2f16-11ea-80d6-20be8522aa92.png)

;)

**Comment by JohanLarsson** [comment]
Beautiful!
