### ISSUE TITLE
Make app version more discoverable

### ISSUE THREAD

**Issue by RussKie** [KirillOsenkov/MSBuildStructuredLog#279]
It took me awhile to find the version of the app I had installed. 
I expected to see "About" (or something like that) under "Help" menu, and nothin was there... The version isn't shown in the title bar not status bar.
I had to start a new instance of the app without a log to see the version shown on the dashboard.

It would be good to have an "About" dialog that (amongst the usual legal stuff) has the app version. 
Short of that, would you consider adding the app version to the titlebar?

**Comment by KirillOsenkov** [comment]
Yes, I agree. Will fix.

**Comment by KirillOsenkov** [comment]
I've added Help -> About that displays the version:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/f9787f7ac8c3bcbde5ac81afd4cdeb7947a40fdb

Will publish this change a bit later, to batch it with some other fixes.

**Comment by RussKie** [comment]
👍
