### ISSUE TITLE
Finding StructuredLogViewer installation path

### ISSUE THREAD

**Issue by veleek** [KirillOsenkov/MSBuildStructuredLog#28]
I'm setting up a few scripts for my team to use StructuredLogViewer and I have added one additional parameter to our build function to use the StructuredLogger. 

After the build is complete, I want to launch the log viewer with the log, but I don't know how to find the install location.  Is there an easy way for me to do this?  I don't want to manually check-in the binaries if possible to make sure that auto updates work properly.  Should I just be searching the AppData folder for the most recent version?  Is there a way to run the installer and find the install path?

**Comment by KirillOsenkov** [comment]
Good question. I need to think about it.

For now you can try hardcoding the path something like this:
%localappdata%\MSBuildStructuredLogViewer\app-1.0.22\StructuredLogViewer.exe

Alternatively, we might need to investigate if https://github.com/Squirrel/Squirrel.Windows Update.exe has a way of launching the latest .exe.

**Comment by veleek** [comment]
Okay, I submitted an issue there to se if they have any suggestions, I'll follow up here with any updates.

https://github.com/Squirrel/Squirrel.Windows/issues/736

**Comment by veleek** [comment]
Squirrel supports opening the latest version of an app by running the squirrel update.exe.  The following works perfectly for this:

```
$update = Join-Path $env:LOCALAPPDATA "MSBuildStructuredLogViewer\Update.exe"
. $update --processStart StructuredLogViewer.exe
```
