### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by RussKie** [KirillOsenkov/MSBuildStructuredLog#280]
I tried to build the solution but having dramas.

The build process isn't documented, so perhaps I'm missing something.
I opened the solution in VS 2019 IntPreview, the NuGet restore option on the solution was never enabled. I dropped to the cli, and I am still failing to build.

I don't have access to the Andrew's myget, and I think that it's breaking the whole thing:
![image](https://user-images.githubusercontent.com/4403806/69899785-5e4ce380-13bf-11ea-8f01-e398afdca44c.png)

I'm not sure whether it is NuGet's or MSBuild's issue, but the build at this point hangs indefinitely...

**Comment by RussKie** [comment]
False alarm, I was too impatient. The restore took like 5 or 7 minutes (😱), and the solution has eventually built

**Comment by KirillOsenkov** [comment]
Usually for my repos a simple `msbuild /r` should work fine, maybe MyGet had a sad day.
