### ISSUE TITLE
Error opening build log for aspnet/AspNetCore

### ISSUE THREAD

**Issue by OdeToCode** [KirillOsenkov/MSBuildStructuredLog#281]
Building aspnet/AspNetCore from source and trying to open the binary log file from the artifacts/log folder:

```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
I verified that the AspNetCore build is using `msbuild.exe` from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin`. I set the log viewer MSBuild path to the same. 

Is there something else I can try?

**Comment by KirillOsenkov** [comment]
Could you update to latest? Start the viewer from the Start menu, wait for it to auto-update, then restart again.

**Comment by KirillOsenkov** [comment]
OK I have inadvertently shipped a bug in the previous few releases. It should be fixed in 2.0.164. Please try updating again?

**Comment by patriksvensson** [comment]
@KirillOsenkov I _just_ downloaded MSBuild Log Viewer on a new machine from http://msbuildlog.com/ and experiencing this error. The version that I downloaded is 2.0.161. Downloaded the latest version (2.0.164) from the GitHub releases and that worked 👍 

Does the site have to be updated as well to point to the right release or is it just lagging behind?

**Comment by KirillOsenkov** [comment]
Yes, thanks! Just updated the sites as well.
