### ISSUE TITLE
Split Exec tasks by target exe in "Top 10 most expensive tasks" report

### ISSUE THREAD

**Issue by tmat** [KirillOsenkov/MSBuildStructuredLog#284]
Currently the log is showing a single entry for all Exec tasks in "Top 10 most expensive tasks", but that's not that helpful if there are multiple different tools being invoked in the build. It would be nice to treat Exec tasks that invoke different tools as separate entities for the purpose of perf reporting.

**Comment by KirillOsenkov** [comment]
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/master/src/StructuredLogViewer.Core/BuildAnalyzer.cs#L167

**Comment by KirillOsenkov** [comment]
Would be nice to add subnodes under the "Exec" node, for each .exe file name and include cumulative duration for each .exe name.

**Comment by KirillOsenkov** [comment]
I think the way @rodo-r2r implemented it is even better, by grouping by parent target, since now you can just go to the offending target.
