### ISSUE TITLE
Generate pretty graph showing msbuild task calls

### ISSUE THREAD

**Issue by cdmihai** [KirillOsenkov/MSBuildStructuredLog#286]
I often need to understand the calling patterns between msbuild projects (which targets, between which projects, with which global properties). The current viewer is not adequate because it contains way more information than needed, and it's not a DAG, making multiple references to the same project hard to see, so the calling patterns are not obvious at all and a lot of scrolling and pen and paper are needed to tease the graph out.

It would be nice to have a separate pane showing a graph with the following definition:
```
Node: (project path, global properties)
Directed Edge: [<called targets>]
```

The graph would explode in complexity with more than a few nodes, but for simple examples (2-5 projects) it would be pretty illuminating on what's going on. Some filtering capabilities would also help with the information overload.

The graph can be generated with some graph layouting library, like [graphvis](https://github.com/graphp/graphviz).

**Comment by KirillOsenkov** [comment]
yup, or https://github.com/microsoft/automatic-graph-layout which has a WPF library
