### ISSUE TITLE
Add filtering for search

### ISSUE THREAD

**Issue by sbanni** [KirillOsenkov/MSBuildStructuredLog#288]
It would be useful if I could limit my search to items only excluding properties or vice versa.  Also being able to only search in one project instead of displaying results of all the projects.

**Comment by KirillOsenkov** [comment]
Try using the under syntax such as `$task csc under($project MyProjName)` -- this will only find Csc tasks under the MyProjName project.

Try searching for `$item ItemName` or `$property PropertyName`. The instructions are in the watermark: 

![image](https://user-images.githubusercontent.com/679326/73106361-170b3c80-3eb0-11ea-95e5-cbd0650f595b.png)

Let me know if these don't satisfy your requirements.

**Comment by sbanni** [comment]
Wow, I don't recall ever reading that watermark as the first time you search it goes away, it looks like that would work for me, although a UI filter would be a nice to have.
