### ISSUE TITLE
Command line UI

### ISSUE THREAD

**Issue by am11** [KirillOsenkov/MSBuildStructuredLog#292]
It would be quite handy if we could get to utilize MSBuildStructuredLog's core features via command line interface. It helps to find issues in CLI-only / base OS installations, without needing to move around log files.

Couple of options / ideas:

1. [non-interactive] simple cli options-based app using strongly-typed model (dragonfruit API) from: https://github.com/dotnet/command-line-api, so we could express queries like "track the value changes of MyVar"
2. [interactive] assuming it is possible to decouple the domain logic from UI in this project (to support other UI forms: cli, web in addition to wpf), the full command-line UI could be implemented using https://github.com/migueldeicaza/gui.cs to get for example, [slap](https://github.com/slap-editor/slap/blob/master/README.md)-like (aka sublime for cli) interface.
3. both of the above :)

**Comment by KirillOsenkov** [comment]
A global tool `binlogtool` is now available. You can install it using `dotnet tool update -g binlogtool`.

Source code is at:
https://github.com/KirillOsenkov/MSBuildStructuredLog/tree/main/src/BinlogTool
