### ISSUE TITLE
same build script on two machines, one binlog has double writes the other doesn't

### ISSUE THREAD

**Issue by voltcode** [KirillOsenkov/MSBuildStructuredLog#301]
I'm profiling our build using binlog and StructuredLogViewer. 
our build scripts consist of several .proj files that in total build 10s of solutions in order of dependency tree. 

When I run the script locally and open the binlog, I see at the bottom only "The Top 10 expensive tasks".

When I run the script on the build machine (either directly via RDP, or through our CI), the binlog contains warnings:
* Double writes
* Unused AssemblySearchPaths locations
* Used AssemblySearchPaths locations
* The Top 10 expensive tasks.

I am trying to reproduce the additional warnings on my local machine, but I can't. The two machines  differ in number of processors (my local has 6 cores, build machine has 12), so I played with disabling parallelization on the local machine, and on build machine to no avail (still - local machine no double writes, build machine with double writes). 
On both environments, the build script completes successfully.

I'd appreciate any hints that could lead me to finding out the differences in setup that affect the double writes.  I must admit, at least some of the reported ones look weird, as if msbuild did not recognize path as relative, and reported copying a file over itself. 

for example (from the build machine):

Copying file from "C:\SOMEPATHHERE\AA.BB\AA.BB\bin\Release\xx.dll" to "bin\Release\xx.dll".

Our build runs msbuild on multiple solutions using Restore;Rebuild as targets.

**Comment by KirillOsenkov** [comment]
It's difficult to guess what is going on without looking. 

If you'd like to share the binlogs with me privately I could take a look. My first name dot last name at Microsoft. You can send me the Dropbox link or something.

Also compare the versions of MSBuild on CI and locally. `msbuild.exe /?`
Also make sure that the log viewer is the same version (2.0.174 or newer).

I'd say you can ignore all of the above if the build completes successfully. Unused AssemblySearchPaths locations and Used AssemblySearchPaths locations are not warnings, they're just hints for you. 

Double writes can be false positives if the copy tool doesn't report the full file path.

**Comment by voltcode** [comment]
I found the issue - StructuredLogViewer seems to assume that the MSBuild is running with English language. Unfortunately, it outputs message in system language by default.

My local dev machine has Polish language version. Our build machine has English language set.

I googled how to change the MSBuild output messages language, it turned out that changing the codepage just before running MSBuild is sufficient:

before running my msbuild script, I ran:
 chcp 850


and the StructuredLogViewer has shown much more details on the English-language generated binlog than on the PL-generated one.

I can see double writes, etc. in the binlog generated on the local machine

It seems to me that this is something worth mentioning in the docs, perhaps the application could also detect and warn the user if the log was not generated with proper English codepage?

**Comment by KirillOsenkov** [comment]
Thanks, yes, that explains it. Unfortunately for now the log viewer only support English. It relies on English messages to parse some things as MSBuild doesn't give us enough structure in the log.

I should add this to the docs perhaps. Added an issue to do so: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/304

**Comment by KirillOsenkov** [comment]
Localized binlogs are now supported starting with version 2.1.174. Give it a try and please log new issues if you're still seeing problems. Thanks!
