### ISSUE TITLE
Preprocess command is missing

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#306]
In v2.1.50, I can't find the Preprocess command anywhere:
![image](https://user-images.githubusercontent.com/3548/75632887-8108b700-5bbd-11ea-9cc6-5526938def22.png)
![image](https://user-images.githubusercontent.com/3548/75632891-85cd6b00-5bbd-11ea-89b8-9983cee17e34.png)

**Comment by KirillOsenkov** [comment]
Can you send me the binlog?

**Comment by KirillOsenkov** [comment]
Published the fix in 2.1.52. Thanks for reporting.

**Comment by jnm2** [comment]
It's missing for me on 2.1.140+0581481207. [Buildlog.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/4776777/Buildlog.zip)

![image](https://user-images.githubusercontent.com/8040367/84597814-54a73c80-ae34-11ea-9e9c-f1c7427a639a.png)

**Comment by KirillOsenkov** [comment]
@jnm2 how did you obtain the log? Is it .binlog or .buildlog? If it comes from Project System Tools then it’s a known bug.

**Comment by jnm2** [comment]
I generated it by opening MSBuild Structured Log Viewer from the start menu, then browsing directly to a .sln (and later a .csproj) file, then running with the default `/t:Rebuild`. Project System Tools and VS were not involved.

**Comment by jnm2** [comment]
Ah, to answer your actual question, I obtained the log using File > Save As inside MSBuild Structured Log Viewer.

**Comment by KirillOsenkov** [comment]
Yes, unfortunately this workflow is not well supported. It produces an old format called .buildlog that predates .binlog. Try getting the .binlog by calling MSBuild.exe `/bl` - this should be well supported.

**Comment by KirillOsenkov** [comment]
I should still fix it though.

**Comment by jnm2** [comment]
Sorry about that! Here's `msbuild /v:diag /bl`: [binlog.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/4777586/binlog.zip)

**Comment by KirillOsenkov** [comment]
Try the preprocess command on this binlog - it works ;) Does it not work for you? Using 2.1.140?

**Comment by jnm2** [comment]
Yes, I see the command shows up if I open this binlog in MSBuild Structured Log Viewer. I don't want to have to use the CLI to produce the binlog every time I want to use MSBuild Structured Log Viewer and I might want to preprocess.

**Comment by KirillOsenkov** [comment]
It’s a bug, I’ll fix it. Just giving you a workaround.

**Comment by jnm2** [comment]
Oh, I see. Thanks!

**Comment by KirillOsenkov** [comment]
I've switched the building logic to produce a binlog instead of buildlog, this should fix it.
