### ISSUE TITLE
Error while analyzing build

### ISSUE THREAD

**Issue by voltcode** [KirillOsenkov/MSBuildStructuredLog#307]
---------------------------

---------------------------
Error while analyzing build. Sorry about that. Please Ctrl+C to copy this text and file an issue on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/new 

System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.

   w Microsoft.Build.Logging.StructuredLogger.CscTaskAnalyzer.Analyze(Task task) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\Analyzers\CscTaskAnalyzer.cs:wiersz 26

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeTask(Task task) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 239

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 72

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Visit(TreeNode node) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 80

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.Analyze() w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 60

   w Microsoft.Build.Logging.StructuredLogger.BuildAnalyzer.AnalyzeBuild(Build build) w C:\MSBuildStructuredLog\src\StructuredLogViewer.Core\BuildAnalyzer.cs:wiersz 34
---------------------------
OK   
---------------------------

**Comment by KirillOsenkov** [comment]
Published a workaround in 2.1.53. Sorry for the inconvenience.

Unfortunately localized binlogs are still not supported, but at least the viewer shouldn't crash when opening them.

**Comment by voltcode** [comment]
I didn't know this issue was also caused by localized binlog. I ran "chcp 850" before running msbuild and I still get some of the messages in PL language (perhaps from CSC? ) .
Do you know of a way to fix the language for msbuild including its child actions like csc or other msbuilds ?

**Comment by KirillOsenkov** [comment]
Yes the message in question is from Csc.

There's a bug on MSBuild to properly support this:
https://github.com/microsoft/msbuild/issues/1596

For Csc you can use the `-preferreduilang` command-line option which is mapped to the MSBuild `#(PreferredUILang)` property. You can try and set this in your Directory.Build.props or an environment variable:

```
<PreferredUILang>en-US</PreferredUILang>
```
