### ISSUE TITLE
Hang when loading large binlog file

### ISSUE THREAD

**Issue by jryckman** [KirillOsenkov/MSBuildStructuredLog#311]
I have a 750-950MB binlog file that I've been trying to load into the app. I have tried opening the file through the app as well as just double clicking the item on disk. 99% of the time, the loading hangs after about a minute or two. 1% of the time, it seems to load. I am using version 2.1.53.57461

I have created a aminidump without heaps of the hang. For quick reference, here's what the parallel stacks looks like:

![image](https://user-images.githubusercontent.com/4111629/75912315-9e848d80-5e16-11ea-9584-4c9416d3e3e2.png)

[StructuredLogViewerWithoutHeap.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/4289142/StructuredLogViewerWithoutHeap.zip)

**Comment by jryckman** [comment]
I just updated to 2.1.57 and it loaded the first time. I'll do it a few more times to see if it still hangs at all

**Comment by KirillOsenkov** [comment]
Yes, this was a known problem and is fixed in 2.1.57. Sorry about the inconvenience and thanks for reporting.
