### ISSUE TITLE
Package MSBuild Structured Log Viewer for macOS

### ISSUE THREAD

**Issue by slang25** [KirillOsenkov/MSBuildStructuredLog#322]
Now that macOS version works really well (I use it daily!) it would be great if it could be packaged up into a `.app`, or some appropriate way of distributing for macOS. Perhaps it's more suited to homebrew and not a `.app` 🤷‍♂️.

I was initially looking at this: https://github.com/egramtel/dotnet-bundle

Thought I would get some feedback before starting work.

**Comment by KirillOsenkov** [comment]
Yes, packaging for distribution would be wonderful. I'm going to do some research but feel free to get started, anything you learn will be valuable. https://github.com/egramtel/dotnet-bundle looks like the right way to do it.

I also found a couple examples:

https://github.com/VitalElement/AvalonStudio/blob/e4122e4a64576473143bb00600da17a2fc370262/packages/package-osx.sh
They have an Info.plist and they're just creating an archive here.

**Comment by kekekeks** [comment]
http://avaloniaui.net/docs/packing/macOS

**Comment by kekekeks** [comment]
Automatic updates can be done via Sparkle https://github.com/Deadpikle/macOS.SparkleUpdater.Avalonia

**Comment by KirillOsenkov** [comment]
From https://gitter.im/AvaloniaUI/Avalonia:

```
Deadpikle @Deadpikle 13:09
@KirillOsenkov If you want to use the popular Sparkle (https://github.com/sparkle-project/Sparkle) mechanism for updating your app, I've got directions on how to integrate that with Avalonia on a repo here: https://github.com/Deadpikle/macOS.SparkleUpdater.Avalonia
There are also instructions on packing a macOS app here: avaloniaui.net/docs/packing/macOS
If you want a cross-platform update mechanism, technically the latest dev branch of https://github.com/Deadpikle/NetSparkle would work with some effort on your part; notably, I don't have an Avalonia UI built out for it yet.
```

**Comment by KirillOsenkov** [comment]
I now have the Apple Developer account and I've exported the .p12 cert. See the discussion here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/686#issuecomment-2543403389

I'll close this issue and let's use the issue 686 for further discussion.
