### ISSUE TITLE
How to correlate project evaluation logs with executed projects?

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#328]
In the screenshot below, I see 3 evaluations occurred with unique id integers. But I can't tell which one goes with which build that happens further down.

![image](https://user-images.githubusercontent.com/3548/79011522-7c6ee100-7b21-11ea-87c4-47cb16a6dcc1.png)

**Comment by KirillOsenkov** [comment]
https://github.com/microsoft/msbuild/issues/4926

**Comment by AArnott** [comment]
Oh, thanks. I see that I've even already up-voted that issue. :)

**Comment by KirillOsenkov** [comment]
MSBuild issue has been fixed. We should see this in 16.9.
