### ISSUE TITLE
ArgumentNullException when opening a buildlog file

### ISSUE THREAD

**Issue by actionthomas** [KirillOsenkov/MSBuildStructuredLog#337]
Hi

I get this error while trying to open a binlog file (latest version, 2.1.117) :
System.ArgumentNullException: La valeur ne peut pas être null.

```
System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : key
   à System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   à System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   à System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   à Microsoft.Build.Logging.StructuredLogger.Serialization.CreateNode(String name) dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:ligne 162
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 80
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.ReadNode() dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 119
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.Read(Stream stream, Byte[] projectImportsArchive) dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 43
   à Microsoft.Build.Logging.StructuredLogger.BuildLogReader.Read(String filePath) dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Binary\BuildLogReader.cs:ligne 28
   à Microsoft.Build.Logging.StructuredLogger.Serialization.Read(String filePath) dans C:\MSBuildStructuredLog\src\StructuredLogger\Serialization\Serialization.cs:ligne 84
   à StructuredLogViewer.MainWindow.<>c__DisplayClass31_0.<OpenLogFile>b__2() dans C:\MSBuildStructuredLog\src\StructuredLogViewer\MainWindow.xaml.cs:ligne 418
```

Is there a way to get more info ? I tried to attach with Visual Studio, but I couldn't have the debugger to break on the exception.

**Comment by KirillOsenkov** [comment]
Is there a chance you could share the .binlog with me privately? E-mail me a Dropbox or OneDrive link to my first name dot last name at microsoft. Thanks!

**Comment by KirillOsenkov** [comment]
If you have the same issue when building a simple ConsoleApplication, you can send me the binlog from that instead.

**Comment by actionthomas** [comment]
> Is there a chance you could share the .binlog with me privately? E-mail me a Dropbox or OneDrive link to my first name dot last name at microsoft. Thanks!

Did you get my email?

**Comment by KirillOsenkov** [comment]
@actionthomas unfortunately I did not. Can you check the spelling? kirill . `osenkov` @ microsoft . com without the spaces.

**Comment by actionthomas** [comment]
I checked the address, it was correct... Is there any other way I can provide the link ? (Twitter DM, Lync/Teams, whatever) ?

**Comment by KirillOsenkov** [comment]
yes twitter DM works great, https://twitter.com/KirillOsenkov

**Comment by KirillOsenkov** [comment]
@actionthomas sorry I found your mail now. I had a rule that sorts out external mail and I forgot to check there. Thanks!

**Comment by actionthomas** [comment]
You're welcome :)

**Comment by KirillOsenkov** [comment]
I see it's a .buildlog format. There are two log formats: .binlog and .buildlog. MSBuild can only produce .binlog and it's the preferred format. .buildlog is only produced when you build in the viewer or when you Save As in the viewer.

I have to confess I haven't paid as much love to the .buildlog format and it does look like the format is now broken, from looking at your buildlog. 

How did you obtain the log? Did you build from the viewer?

Do you have the original .binlog file you can send me? This .buildlog you sent me appears corrupt. I can still do some forensics to try to understand what is going wrong but it'd be nice to have the original.

**Comment by KirillOsenkov** [comment]
Note to self: the `buildlog` is `MSBuildStructuredLog-23212.buildlog`

**Comment by KirillOsenkov** [comment]
I'll close this as it relates to buildlog files, which are now obsolete. Using .binlog files instead.
