### ISSUE TITLE
In 2.1.88+, search results are no longer highlighted in the main tree

### ISSUE THREAD

**Issue by dagood** [KirillOsenkov/MSBuildStructuredLog#339]
I noticed this on 2.1.117 and tried it out in some old versions, found that it started happening in 2.1.88. It doesn't seem to depend on binlog content to me, but let me know if this isn't enough info and I can provide one.

In **2.1.60**, the nodes were highlighted when there's a search result inside:

![image](https://user-images.githubusercontent.com/12819531/80025415-3a8d5580-84a6-11ea-9771-deaf504f37ed.png)

In **2.1.88** with the same binlog, the node are no longer highlighted:

![image](https://user-images.githubusercontent.com/12819531/80025435-45e08100-84a6-11ea-94a7-6f8ba11496dd.png)

I found the highlighting useful to quickly locate search results. Sometimes the left pane isn't quite as good at giving context where search results are relative to each other in the tree.

The 2.1.88 release notes mention search perf improvements, so hopefully this was just missed and isn't an ordeal to put back in. 🙂

**Comment by KirillOsenkov** [comment]
Start the viewer from the start menu, it's on the start page: :)

![image](https://user-images.githubusercontent.com/679326/80027356-7c170400-8498-11ea-8a1c-3e0835d45e4e.png)

Or go to File -> Start Page.

**Comment by dagood** [comment]
Ah, great! Thanks. 😄
