### ISSUE TITLE
Feature request - workspace folder with list of projects/solutions

### ISSUE THREAD

**Issue by modulexcite** [KirillOsenkov/MSBuildStructuredLog#35]
It would be nice to have a workspace folder view listing all the projects/solutions that I can build from.

**Comment by rahulpnath** [comment]
@modulexcite Did you mean all (recently) build projects or a scan of all projects in your hard-disk?

**Comment by modulexcite** [comment]
The app already has a list of recent projects/solutions that I can work with, I'd like to add a folder that has all my solutions/projects that I can build from displayed in a tree-view instead of opening one at a time.
My idea of the tree-view isFolder-->Solution-->Project(s).
Hope the above makes sense.

___________________________
Thanks.

**Comment by KirillOsenkov** [comment]
I'd like to clarify a few things:
1. what is it that you want to simplify? how will this help?
2. What exactly is displayed in the tree view? How do I discover the content? What's the root folder?
3. Is the content of the folder persisted somewhere or is it just discovered every time?

**Comment by modulexcite** [comment]
I love the application and thanks for sharing it with the rest of the world. You rock @KirillOsenkov ! 
Please let me know if any of the below is unclear or needs more explanation.

**What is it that you want to simplify? how will this help?**
I'm not sure about others but this is just my workflow. I tend to organize a bunch of projects under different folders and would love to be able to just open a folder to analyze any project under that folder without having to open each project by selecting File-->Build Solution/Project (F6) or using the command line. I think displaying a tree view of the solutions/projects under a folder would help simplify this.

**What's the root folder?**
User should be able to select a folder(s) where all the solutions/projects are stored under, perhaps an option under File-->Open Workspace Folder. Also, adding a separate menu item "Recent Workspace Folders" as an option to display folders used by the user recently would be helpful.

**What exactly is displayed in the tree view? How do I discover the content?**
Tree view should contain Folder-->Solution-->Project(s). For discovering the content, you can search for ".sln" files under the root folder and add any ".proj" files as child node to the ".sln" file similar to how Visual Studio displays the solution and it's projects in Solution Explorer.

**Is the content of the folder persisted somewhere or is it just discovered every time?**
I'm not sure about this one, there are pros and cons to both I suppose.

**Comment by KirillOsenkov** [comment]
Unfortunately I doubt I'll ever get to this. I think the established workflow now is double-clicking .binlog files, so the idea of building projects from the tool is no longer as relevant. I'll close this and sorry I never got around to it!
