### ISSUE TITLE
Lots NullReferenceExceptions when opening log file

### ISSUE THREAD

**Issue by bording** [KirillOsenkov/MSBuildStructuredLog#351]
While using the build log viewer to investigate a problem I've been having, I just hit something rather unexpected:

![image](https://user-images.githubusercontent.com/753669/81213096-e3a67680-8fa3-11ea-9b0e-f7cdae82410e.png)

The log file was created through the Project System Tools inside of VS. 

The really strange thing is that this project is nothing more than a new console app where I've changed the project file to be `<TargetFrameworks>net48;netcoreapp3.1</TargetFrameworks>` instead of the default.

I can send you the log file if that would be helpful.

LogViewer version: 2.1.117
Project System Tools version: 1.0.1.2010501
VS version: 16.5.4

**Comment by KirillOsenkov** [comment]
Yes please, send me the log file at kirill dot osenkov at microsoft, or via Twitter DM https://twitter.com/KirillOsenkov

**Comment by bording** [comment]
Sent you a link via twitter DM

**Comment by KirillOsenkov** [comment]
Fixed in 2.1.133 - please update the viewer. Thanks!
