### ISSUE TITLE
HttpRequestException when running offline

### ISSUE THREAD

**Issue by jasondavis11** [KirillOsenkov/MSBuildStructuredLog#356]
When running offline (which is always our use-case) an HttpRequestException occurs and displays on the main page.

Version 2.1.133+ddb0c80733

**Comment by KirillOsenkov** [comment]
Yes, the app is trying to update itself, I can tone it down.

**Comment by KirillOsenkov** [comment]
I've made a better error message that is not as obtrusive.

You can also turn off automatic updates entirely if you want by creating an (empty) .txt file:
`%localappdata%\Microsoft\MSBuildStructuredLog\DisableUpdates.txt`

If this file is present the app will not attempt to update.
