### ISSUE TITLE
WinGet support

### ISSUE THREAD

**Issue by azchohfi** [KirillOsenkov/MSBuildStructuredLog#357]
It would be awesome to be able to install this thru winget (https://github.com/microsoft/winget-pkgs).

**Comment by InKahootz** [comment]
I submitted a PR for the manifest: https://github.com/microsoft/winget-pkgs/pull/28191/

You should be able to find/install it once it auto-completes.

**Comment by InKahootz** [comment]
@KirillOsenkov It is now in the index. So I think this issue can be closed.

I'm sure we could automate the process but I didn't see automation for chocolately yet either. Another issue tracking that would be appropriate.

**Comment by KirillOsenkov** [comment]
Thanks!

**Comment by KirillOsenkov** [comment]
I’ll keep the issue open to remind myself to update it and see if it’s easy to automate.
