### ISSUE TITLE
Out of memory exception for very large log file

### ISSUE THREAD

**Issue by mfkl** [KirillOsenkov/MSBuildStructuredLog#359]
Hello,

I hit an out of memory exception with a 4GB `msbuild.binlog` file.

![oom-msbuildstructuredlog](https://user-images.githubusercontent.com/3928834/84568142-b789cc80-ad7d-11ea-99b2-1f4bd0e6e258.PNG)

_(Sorry about the picture, I could not copy/paste the text from the window)._

My machine has 16GB of RAM and MSBuildStructuredLog tries to open the log file for several minutes until there is no more RAM available.

![oom-status](https://user-images.githubusercontent.com/3928834/84568165-df793000-ad7d-11ea-834c-d9acea96d225.PNG)

I will try to find a free cloud service that will allow me to share that large file with you, but you can generate it easily locally.

- Clone https://github.com/mfkl/big-solution
This solution has been generated using [this script](https://github.com/dotnet/fsharp/blob/master/tests/projects/stress/gen.fsx) like so:
```
fsi.exe gen.fsx autogen-projects 400 true
```
- Generate the binlog on an incremental build.
```
msbuild /t:restore,build Dense.sln
msbuild Dense.sln /bl
```

Related https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/235

**Comment by KirillOsenkov** [comment]
Thanks for reporting, but I’d say this is not a bug, the system is behaving as designed. 4GB binlog is highly compressed and contains about 1TB of information. To display 1 TB of info in UI you need a lot of memory.

The largest binlog I’ve seen in a real life scenario is about 700MB and I had to get an Azure VM with 64GB RAM to open it.

We have some plans to further reduce binlog sizes, but the fundamental problem will always remain. I’m afraid there’s not much else we can do here.

**Comment by mfkl** [comment]
Ok, thank you.

**Comment by KirillOsenkov** [comment]
Also Ctrl+C usually works in message boxes like that to copy all text.

**Comment by mfkl** [comment]
> 
> 
> Also Ctrl+C usually works in message boxes like that to copy all text.

Yes, I tried to select the text with my cursor and since I couldn't and assumed it was the only way, I took a screenshot. Will try Ctrl+C with the window in focus next time. Didn't manage to repro, it just loads forever.

Thanks.
