### ISSUE TITLE
Pass log file to open to log viewer as command line argument

### ISSUE THREAD

**Issue by veleek** [KirillOsenkov/MSBuildStructuredLog#36]
I have a set of scripts to build using the structured logger and I'd like to launch the log viewer and load the log automatically.

Accepting just a file path should be enough.  In order to properly support launching the most recent version via Squirrel's update.exe, we'll need to investigate whether or not command line arguments can be pass through to the called app.

**Comment by KirillOsenkov** [comment]
This is now fixed. Let me know if it doesn't work as you expected.

You can experiment with processStartArgs in Squirrel:
https://github.com/Squirrel/Squirrel.Windows/blob/ee32fb469fc1ace0af6aef7edc389e27b8c063bb/src/Update/Program.cs#L93
