### ISSUE TITLE
Displaying Items passed to Tasks

### ISSUE THREAD

**Issue by tompazourek** [KirillOsenkov/MSBuildStructuredLog#362]
I'm using the MSBuild Structured Log Viewer and diagnosing the `PackTask` from the NuGet part of the SDK projects.

The `PackTask` has some parameters that are values, and some that are collections of items.

![image](https://user-images.githubusercontent.com/370699/85023340-e1276700-b174-11ea-8ec9-97dc39629d4a.png)

The viewer displays the "Parameters" when I find the task, but it **only displays the values passed**, not the item collections passed. For example, I can't see the `PackageFiles` value.

![image](https://user-images.githubusercontent.com/370699/85023389-f43a3700-b174-11ea-9be4-a2624303fab0.png)

---

**What would be a good way of investigating the items passed as the parameters?** I'm assuming it's a feature that's not available in MSBuildStructuredLog (maybe not even possible)... If it is possible (the information is available in the binlog), is there already some GH issue I can vote for, or even possibly contribute to?

Any help regarding this is appreciated. Thank you!

**Comment by KirillOsenkov** [comment]
I think everything's working as designed. `_PackageFiles` just appears to be empty.
`BuildOutputInPackage` seems to be displayed correctly.

**Comment by tompazourek** [comment]
You're right, **all the items parameters were actually empty in my case**. I can see that the items appear correctly now if I try it elsewhere, so everything is working as designed.

Sorry for wasting your time, I'm embarrassed.

It might be clearer if the parameter was listed there and just shown some grey `(empty)` value label. It might make it more clear, but I'm not sure if that is actually possible.

**Comment by KirillOsenkov** [comment]
No problem at all, it’s good to clarify. The problem we have is binlog sizes, so adding even more information that’s mostly redundant would add noise and bloat. Since you can correlate with the full list of task parameters specified in source I think you can recover this information manually if needed. Also MSBuild just doesn’t log empty parameters, so we wouldn’t be able to do it anyway.
