### ISSUE TITLE
The under keyword performs recursive search which often results in a lot of irrelevant results.

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#363]
For example, suppose Project A builds Project B builds Project C.
Then whenever we search with **under($project A)** we are going to get stuff under B and C as well, because they are **under($project A)** too.
This is not helpful at all.

If we cannot retroactively change the semantics of **under** (and I suppose we cannot) we should introduce a strict flavor of it, like **strictunder** where **strictunder($project A)** would return everything under A, but not under B or under C.

**Comment by KirillOsenkov** [comment]
You can do `under(A) notunder(B) notunder(C)`

Would that help?

The problem with strictunder is that from the algorithm’s point of view the projects are not special. It’s all tree nodes with strings. When you think about cones and subtrees it’s easy for a human to see whether something is directly under something else, but what does it mean strictly speaking? Not sure how to express what you want in an algorithm.

By adding notunder clauses you’re manually filtering out subtrees that you don’t care about.

I guess we could add something like “where nearest parent project is A”, this would filter out B and C without the need to mention them explicitly.

I’m thinking `directlyunder($project A)` would find all nodes where the nearest parent project matches A.

**Comment by KirillOsenkov** [comment]
I guess it’s important to explicitly specify the type of node (e.g. $project)

**Comment by MarkKharitonov** [comment]
So, specifying the project explicitly does not fly for big solutions. In my case the particular project has many projects under it. So, using notunder is not practical in general.

Do we already have **directlyunder** ? Because I have not noticed it in the help screen. I may need to upgrade. And yes, I am OK with specifying the scope **$project** explicitly.

**Comment by KirillOsenkov** [comment]
Nope, not yet. We'll have to build it.

**Comment by MarkKharitonov** [comment]
Yes, please. That is currently what prevents me from using under - too much noise.

**Comment by KirillOsenkov** [comment]
We just implemented the `project(...)` clause. It works like `under(...)` clause but ensures that the nearest parent project matches what's inside the parentheses.

Our initial design would be to do `directlyunder($project=...)` but I kept thinking how to make it shorter. Most times people want to search under projects and rarely under other types of nodes. So I decided instead to have a special clause for projects.

@MarkKharitonov would you try out the latest master branch and see if it works for you? I can deploy then if it works as expected.

**Comment by KirillOsenkov** [comment]
I'll close this but feel free to either reopen or open a new issue if this doesn't meet your expectations.

**Comment by MarkKharitonov** [comment]
Just to make sure I understand what to do. Is there a prebuilt binary or should I build from the source?

**Comment by KirillOsenkov** [comment]
yes for now please pull latest and build from source

**Comment by MarkKharitonov** [comment]
Hi.
Sorry for the belated response. I have cloned and ran locally. Seems to work fine.
However, curious thing. Searching for `$task csc under($project xyz)` does not work. And it seems to be broken in the released version.
What am I missing?

**Comment by KirillOsenkov** [comment]
Hmm, works fine here. Do you have better repro steps? Feel free to file a new bug. Thanks.

**Comment by MarkKharitonov** [comment]
No, it is good. Was my fault.

Can I search by some word exactly? For example, when looking for `$target Build` it returns all the targets containing Build. Sometimes it is OK, sometimes it is not. Is there a way to specify exact search?

**Comment by KirillOsenkov** [comment]
Not yet; I just filed https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/395

**Comment by MarkKharitonov** [comment]
Excellent, thank you.
