### ISSUE TITLE
"Previously built successfully" should link to the instance when the target actually ran

### ISSUE THREAD

**Issue by MeikTranel** [KirillOsenkov/MSBuildStructuredLog#373]
When debugging certain project reference combinations it is really crucial where stuff actually ran to get OutputItems etc.
![image](https://user-images.githubusercontent.com/6466560/86223445-da8eeb80-bb87-11ea-95f6-a6f2cbeb7d52.png)

Maybe we can link to the instance of the target execution that resulted in that target instance being skipped. Maybe its also a good idea to render results of targets even though they were skipped.

**Comment by KirillOsenkov** [comment]
It's a good idea, probably needs to be done on the MSBuild side. The logger doesn't get this information.

**Comment by MeikTranel** [comment]
So we would need an upstream issue in github.com/microsoft/msbuild ,right?

**Comment by KirillOsenkov** [comment]
I just filed one:
https://github.com/microsoft/msbuild/issues/5475

Leaving this issue open to add support in the viewer once MSBuild adds support on their side.

**Comment by KirillOsenkov** [comment]
Hey @MeikTranel check this out:
https://github.com/dotnet/msbuild/pull/6402#issuecomment-830999849

![NavigateToOriginalTarget](https://user-images.githubusercontent.com/679326/116838620-d3f44a80-ab83-11eb-96d1-a4db31ac4c74.gif)

**Comment by MeikTranel** [comment]
![tenor](https://user-images.githubusercontent.com/6466560/116923560-10dd4180-ac57-11eb-96fd-f21de776f785.gif)
