### ISSUE TITLE
"View" on a Task node should show me the task element, not the beginning of the target that includes it

### ISSUE THREAD

**Issue by dagood** [KirillOsenkov/MSBuildStructuredLog#380]
When I right click => "View" on a successful Task node (double-click), it brings me to the top of the Target that defines it, rather than the task itself. In a target that executes many of the same task type, this can make it hard to find which one in the source is responsible for that node. (It also might simply be a long enough target that scrolling through it to find the task every time I click on the node is an annoyance.)

(When a task hits an error, it works nicely: the error message includes the line number and "View" takes me there.)

I suspect this is a logging limitation--I don't see line numbers in the detailed XML file or `diag` logging. It also might not be worth it to push all this info all the way through the logs to the UI (file size, perf, etc). But, I figured I'd ask in case that's wrong. 🙂

**Comment by KirillOsenkov** [comment]
Exactly, there is nothing logged that would tell us where the Task is in the XML file. We infer that by finding the Target, and then looping over the tasks inside the target. If we find a single match, we use that. If we don't (like in your case where there are multiple tasks) we give up and just show you the target.

I think it would require a change on the MSBuild side to add information about the location of the task on the TaskStartedEventArgs.

**Comment by KirillOsenkov** [comment]
Let's leave it open, maybe I'll file an MSBuild bug someday.

**Comment by KirillOsenkov** [comment]
This may be fixed with https://github.com/dotnet/msbuild/pull/6399

**Comment by KirillOsenkov** [comment]
Also related: https://github.com/dotnet/msbuild/pull/6397

**Comment by KirillOsenkov** [comment]
I think the fix from https://github.com/dotnet/msbuild/pull/6399 should have propagated everywhere now, so this should be fixed in all recent binlogs.
