### ISSUE TITLE
Is it possible to see items returned by evaluation?

### ISSUE THREAD

**Issue by drewnoakes** [KirillOsenkov/MSBuildStructuredLog#385]
Right now the "Evaluation" node only shows evaluated properties. It would be useful to see the set of items obtained via evaluation.

(I'm not 100% sure that this makes sense though. In VS we evaluate the project and get items from it, and my assumption is that these items come from the evaluation directly without calling any targets.)

**Comment by KirillOsenkov** [comment]
Properties and Items should be displayed under a Project's actual build, not evaluation. Sometimes it's not displayed, and it's a bug that we need to figure out: 

https://github.com/dotnet/msbuild/issues/3616
https://github.com/dotnet/msbuild/issues/4926
https://github.com/dotnet/msbuild/issues/5316

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/msbuild/issues/4926 has now been fixed, so what's left is move the logging of properties and items from ProjectStarted to ProjectEvaluationFinished

**Comment by KirillOsenkov** [comment]
https://github.com/dotnet/msbuild/pull/6287 should fix this.

**Comment by KirillOsenkov** [comment]
This is fixed and will hopefully ship in 16.10.
