### ISSUE TITLE
Search for an exact word

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#395]
possibly use quotes

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/a3f1e436b5446cd5a1c38eda0397608ed1492c09

Will release soon. Hopefully this works for you.

**Comment by KirillOsenkov** [comment]
@MarkKharitonov

**Comment by MarkKharitonov** [comment]
I did not understand how the feature works. Please, observe:
![image](https://user-images.githubusercontent.com/489792/102653633-37ce2780-413d-11eb-8f26-dbd71fc80882.png)

Now trying to do exact search:
![image](https://user-images.githubusercontent.com/489792/102653675-487e9d80-413d-11eb-87c4-d218fac495a4.png)

![image](https://user-images.githubusercontent.com/489792/102653698-52080580-413d-11eb-8bb4-a1cb04621d6f.png)

![image](https://user-images.githubusercontent.com/489792/102653726-5df3c780-413d-11eb-98d7-18d817bffc29.png)

![image](https://user-images.githubusercontent.com/489792/102653740-664c0280-413d-11eb-8fe4-d0ddd3f32eac.png)

Help about:
![image](https://user-images.githubusercontent.com/489792/102653770-74018800-413d-11eb-948b-bf4e3f40b055.png)

Source code:
```
C:\work\MSBuildStructuredLog\bin\StructuredLogViewer\Debug\net472 [(a3f1e43...)]> git lg -1
a3f1e43 |  (HEAD) Support quotes for exact word search (no substring). (2 days ago) [Kirill Osenkov] (2020-12-16 19:49:13 -0800)
C:\work\MSBuildStructuredLog\bin\StructuredLogViewer\Debug\net472 [(a3f1e43...)]>          
```

**Comment by KirillOsenkov** [comment]
This is because the full name of the project is mot what you expect. It’s `Project “DataSvc.csproj” (default targets):`

I know it’s dumb and I’ll be fixing it

**Comment by KirillOsenkov** [comment]
I've fixed it just now.

The following should now all work:
`$target AssertHint under($project DataSvc.csproj)`
`$target AssertHint under($project "DataSvc.csproj")`
`$target AssertHint project(DataSvc.csproj)`
`$target AssertHint project("DataSvc.csproj")`

Again, I haven't released yet but the latest master branch has the fixes.

**Comment by KirillOsenkov** [comment]
@MarkKharitonov I'm done with the next batch of fixes I wanted to do.

Would you like to get the latest master branch sources, build it yourself and play around to see if everything is to your satisfaction? Specifically exact match in search by using "", such as:

`$property name="TargetFramework"` should no longer find properties such as TargetFrameworkMoniker etc.

Let me know if there's anything else you'd like to see fixed.

**Comment by KirillOsenkov** [comment]
@MarkKharitonov I've deployed everything so if you update the viewer you should have latest. No longer need to build from source.

**Comment by KirillOsenkov** [comment]
See the list of new features here:
https://twitter.com/KirillOsenkov/status/1344520698409099264

**Comment by MarkKharitonov** [comment]
Excellent, thank you very much.
