### ISSUE TITLE
Binlog Viewer Not Displaying Warnings

### ISSUE THREAD

**Issue by BenVillalobos** [KirillOsenkov/MSBuildStructuredLog#399]
## Context
We recently added a feature in MSBuild called Change Waves. The basic idea behind the feature is to set `MSBuildDisableFeaturesFromVersion` to some MSBuild version, and that would disable a set of features behind that version (and all future versions). The current versions are `16.8`, `16.10`, and `17.0`. The issue starts here: If a user sets `MSBuildDisableFeaturesFromVersion` to several types of invalid versions (like a garbage value) it throws a warning. [Here](https://github.com/dotnet/msbuild/blob/master/src/Build/Evaluation/Evaluator.cs#L1095) is the source for where this warning is thrown.

The problem is that this warning is shown in the output of a build (VS and cmd line), but it doesn't show up in the viewer. If you replay the binlog with diagnostic logging, you can see the warning in the generated `msbuild.log`

@rainersigwald and I have observed that it gets picked up in the viewer's `WarningRaised` function, but isn't drawn for some reason. 

See attached binlog.
[msbuild.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/5301615/msbuild.zip)

**Comment by KirillOsenkov** [comment]
Apparently we never had warnings under Evaluation before? Or we were throwing them away until now?

Anyway, here's how it looks now:
![image](https://user-images.githubusercontent.com/679326/94613202-186be080-0259-11eb-8a12-d8afa179bc74.png)

Does it look right to you?

**Comment by KirillOsenkov** [comment]
There's something still off. I'd expect three warnings in the binlog, but there are only two. But binlog viewer is off the hook now I think?

**Comment by KirillOsenkov** [comment]
Code review please: https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/61cd163a9c369d7184bad31a9230794b0c8d66b4

**Comment by KirillOsenkov** [comment]
Published the fix, please file a new issue if something is not right.

**Comment by BenVillalobos** [comment]
LGTM, thanks for the quick fix!
