### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by piotrpMSFT** [KirillOsenkov/MSBuildStructuredLog#40]
@KirillOsenkov any plans to make a portable version of this toolset? Looks like the current implementation expects to be run with desktop msbuild. I'd be particularly keen to get access to a portable logger. It'd be great to view the logs x-plat, but shuttling them to a Windows machine for analysis would be a great first step!

**Comment by KirillOsenkov** [comment]
I'd appreciate someone else contributing this since I have 0 experience with the portable/core world :)

**Comment by piotrpMSFT** [comment]
Looked briefly and saw that the project is mostly driven by csproj [why the project.json, btw]. I'll wait until we ship dotnet CLI with msbuild support to avoid doubling your project system overhead :)

**Comment by KirillOsenkov** [comment]
Good idea, thanks. Remember to come back when it's ready :)

**Comment by modulexcite** [comment]
I think the release date is very close for .NET core with msbuild and .csproj support according to the blog post below by Scott Hunter.
https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

**Comment by piotrpMSFT** [comment]
@modulexcite I was actually hoping to use this to get a deeper look into our builds on https://github.com/dotnet/cli :)

**Comment by natemcmaster** [comment]
👍 I'm interested in this as well for aspnet core. I think StructuredLogger will help a lot in our port from project.json to csproj

**Comment by piotrpMSFT** [comment]
@KirillOsenkov I'm starting on a port. Once it gets to a meaningful place I'll create a PR from my fork so you can follow along and give early feedback. My first step is to port to the .NET Core  csproj format and get build/test green on OS X. Once that's working we'll need to think about how this should be handled in CI and get Windows support working again. 

I expect we'll hit some blockers along the way. The first issue I ran into is https://github.com/AArnott/Nerdbank.GitVersioning/issues/56. I'm going to disable GitVersioning in my fork for the moment to see what else comes out. @AArnott perhaps you can help out with a GitVersioning port? or maybe @natemcmaster will want to help move this forward and create that PR?

I'll let folks know as I hit other blockers. Now I kinda wish those https://github.com/dotnet/cli guys would provide an "old-style" to .NET Core csproj migration utility :D

**Comment by piotrpMSFT** [comment]
@jonsequitur @livarcocc since they may both be interested.

**Comment by piotrpMSFT** [comment]
https://github.com/piotrpMSFT/MSBuildStructuredLog/tree/piotrpMSFT/issue40/netcoreport

This is a very rough port. Things learned:
- [ ] GitVersioning is not yet ported. Tracked by AArnott/Nerdbank.GitVersioning#56
- [ ] Crosstargetting is required to maintain current behaviors. @KirillOsenkov I think it would be better to move to a portable subset so folks can think of the behavior of this logger uniformly across platforms, but this will be a breaking change. Otherwise, we can cross-target to net46 with IFDEFs:
   - [ ] Windows-only Environment data like 
     - [ ] [Special Directories](https://github.com/piotrpMSFT/MSBuildStructuredLog/commit/f9006be7016cbeb76ed4fb97777623cdbc0f0981#diff-6efd59cab76972d42d34292083ca62b0L12)
     - [ ] [Command Line Arguments](https://github.com/piotrpMSFT/MSBuildStructuredLog/commit/f9006be7016cbeb76ed4fb97777623cdbc0f0981#diff-9db4a4d8cc91c7436c0c34c312542e63L51)
    - [ ] APIs missing on core
     - [ ] [Current Directory](https://github.com/piotrpMSFT/MSBuildStructuredLog/commit/f9006be7016cbeb76ed4fb97777623cdbc0f0981#diff-9db4a4d8cc91c7436c0c34c312542e63L52). This likely has an alternate available. 
     - [ ] [Executing Assembly](https://github.com/piotrpMSFT/MSBuildStructuredLog/commit/f9006be7016cbeb76ed4fb97777623cdbc0f0981#diff-8bf0d45773caae13ddc1c66fde38ea55L42). After searching dotnet/corefx I found that this is intentionally removed and don't see an intent to bring it back. Perhaps the workaround I added is sufficient?
 - [ ] The viewer app is clearly Windows Only. Looks like WPF, but I'm no expert on xaml use cases.
 - [ ] The project uses a Common.targets which seems to be intended to override some Microsoft.Common.targets behavior. that don't work super well with the current iteration of the `<Project Sdk=...` attribute as it is impossible at the moment to override targets defined in an SDK without jumping through some very inconvenient hoops. Those hoops are tracked by https://github.com/Microsoft/msbuild/issues/1400. My fork simply removed the target with no obvious side effects so perhaps this is a moot point. @KirillOsenkov likely understand the implication better than I am gleaning through code inspection.

**Comment by AArnott** [comment]
@piotrpMSFT Wow, this is great. Can I ask why AArnott/Nerdbank.GitVersioning#56 is a blocker for you? I can see it would be if your goal was to make this MSBuildStructuredLogger project build with CoreCLR. But if your goal is simply that you can _use_ MSBuildStructuredLogger with CoreCLR then it shouldn't be, since one can simply build MSBuildStructuredLogger on desktop CLR and then use it elsewhere. 

So is your goal to build this MSBuildStructuredLogger on CoreCLR as well? (if so, I'm curious why that's so important)

To be clear, I want AArnott/Nerdbank.GitVersioning#56 fixed as well. But at the moment, that is in turn blocked by https://github.com/libgit2/libgit2sharp/pull/1318

**Comment by KirillOsenkov** [comment]
Thanks for this work @piotrpMSFT!

Common.props is just a convenience (I use it in most my projects), to extract out duplicate parts from each project and share them in a single location. If it's in the way, it's OK to "inline" it.

I agree with @AArnott, the only project that we need to _run_ on CoreCLR is the StructuredLogger.dll. It's OK if it only builds on Windows, as long as you can produce a NuGet package that you can install on other OS and add to the non-Windows MSBuild process.

The viewer is WPF and hence Windows only.

**Comment by piotrpMSFT** [comment]
Thanks for taking a look guys!

You bring up great points regarding how the build should work once we're done. My intention going in [and remember, I work on the dotnet CLI during the day so I have some biases you're welcome to discourage:)] was to bring as much as I could onto the .NET Core tooling. To be productive cross-platform I think we want both StructuredLogger.dll and StructuredLogger.Tests.dll to be buildable and runnable cross-platform. We've hit e.g. Mac-only issues in other projects which may be difficult to diagnose if we can't run tests or debug on that platform. That really only leaves the WPF viewer that needs to stay on desktop CLR + Tooling.

I do think we can do as suggested by @AArnott and @KirillOsenkov and only enable real package builds on Windows, including real versioning. This will unblock me from waiting on AArnott/Nerdbank.GitVersioning#56. 

@KirillOsenkov I saw that the Common.props pulls in the SDK props on the first line of code, so it's not at all in the way. I simply removed Common.props' reference to the SDK. I've removed Common.targets.

One thing to note, which may impact the desirability of this change. Once it goes in, the project will require up-to-date tooling. From the command line this will be 'free', but the IDE experience will require VS2017. As to CI, we have two options. If VS2017 tooling [MSBuild, targets, etc] is available on AppVeyor [the RC version for the time being] then we can use it directly. Alternatively, I can try to get the whole project building atop dotnet CLI [I've not tried doing so with a WPF app thus far but am curious to see what issues are hit]. FWIW, I think that using CLI on CI is the `right` thing to do since it separates build pre-requisites from build machine setup and thus improves build determinism between the dev box and the build server. Happy to discuss this more.. it's a decision that @KirillOsenkov needs to make in the end.

**Comment by KirillOsenkov** [comment]
Thanks to help from @piotrpMSFT @jonsequitur @livarcocc I have produced a beta build of the portable logger:
https://www.nuget.org/packages/Microsoft.Build.Logging.StructuredLogger/1.0.115-beta

Usage: download the NuPkg and pass this to your msbuild:

```
msbuild ... /logger:StructuredLogger,Path\to\lib\netstandard15\StructuredLogger.dll;output.buildlog
```

Let me know if it works! Any feedback welcome!

For now this is in the `netcore` branch. I'll merge back into master after VS 2017 RTMs.

**Comment by thomaslevesque** [comment]
Hi @KirillOsenkov, VS 2017 is out now :)
Do you intend to release a version with .NET Core support?

**Comment by KirillOsenkov** [comment]
Oh! I forgot to mention. It's already released! The NuGet https://www.nuget.org/packages/Microsoft.Build.Logging.StructuredLogger/ will have both net46 and netstandard1.5 StructuredLogger.dll.

**Comment by thomaslevesque** [comment]
Ah, thanks! It didn't seem to work with the version I had. I'll try with the new one.

**Comment by KirillOsenkov** [comment]
Please let me know if you run into issues. This hasn't been tested much yet.
