### ISSUE TITLE
Structured log viewer opens, but often freezes

### ISSUE THREAD

**Issue by forrestcoward** [KirillOsenkov/MSBuildStructuredLog#400]
Hi,

I love the MSBuild structured log viewer, it's great - when it works.

However, a problem I consistently run into is the application constantly freezes. Loading the binlog is not an issue, but after scrolling in the application or just over time, the structured log viewer just stops working and is completely frozen. Sometimes this happens after 1 seconds, sometimes after a few minutes. From my experience, it will often freeze when scrolling quickly, although I have no idea if this is true or not. I often will reopen a binlog multiple times to get the information I need until I can use it enough before it freezes.

For me, this is not related to the size of the binlog. It happens on small and very large binlog files.

I find the structured log viewer works best when I immediately resize the window to be very small and never change its size.

Any ideas what is happening or has this been reported before?

**Comment by KirillOsenkov** [comment]
Yes, unfortunately you're running into https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/21

Good news is that you can just start the viewer and uncheck this checkbox:
![image](https://user-images.githubusercontent.com/679326/95371539-2fc95000-088f-11eb-88c3-e2c908aff07b.png)

If you continue to see hanging with this checkbox unchecked, please let me know and we'll investigate further. But I'm pretty sure this will fix it.

**Comment by KirillOsenkov** [comment]
Also try updating your Windows and .NET Framework to the latest version, a lot of such hangs have been fixed in the latest .NET Framework 4.8.

**Comment by forrestcoward** [comment]
Thank you. I will try that immediately :)

**Comment by forrestcoward** [comment]
This solution is working for me.
