### ISSUE TITLE
2.1.2018 does not look in MSBuild 2019 Path?

### ISSUE THREAD

**Issue by clairestreb** [KirillOsenkov/MSBuildStructuredLog#408]
I am running 2.1.208.
My Path environment variable is shown below, and MSBuild only appears once (C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin).
When I run this program, I see some output that says: Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Because of that output, it looks like this program is not using my path?

Path = C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VistA\Imaging\;C:\Program Files (x86)\Micro Focus\Reflection\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\HID Global\ActivClient\;C:\Program Files\HID Global\ActivClient\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\VistA\Imaging\Muse;C:\Program Files (x86)\VistA\Imaging\lib;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Webex\Plugins;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;U:\My Documents\Misc\Scripts;C:\Program Files\PolicyPak\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\TortoiseGit\bin;C:\Fortify\Fortify_SCA_and_Apps_20.1.0\bin;C:\Users\VHACANStrebC\AppData\Local\Microsoft\WindowsApps;C:\Users\VHACANStrebC\AppData\Local\Programs\Git\cmd;C:\Users\VHACANStrebC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\VHACANStrebC\.dotnet\tools;C:\Users\VHACANStrebC\AppData\Local\Yarn\bin;C:\Users\VHACANStrebC\AppData\Local\GitHubDesktop\bin

**Comment by KirillOsenkov** [comment]
It is recommended to obtain binlogs from a command-line build, e.g. `msbuild /r /m /bl MySolution.sln` will produce msbuild.binlog that you can then double-click to open in the viewer. 

That said, building projects from the viewer should still work. Can you screenshot what you see in the drop-down after you choose open project/solution?

![image](https://user-images.githubusercontent.com/679326/97479027-01c7b080-190f-11eb-993b-218e9c723917.png)

After the binlog opens, what do you see in the MSBuild path?
![image](https://user-images.githubusercontent.com/679326/97479162-291e7d80-190f-11eb-94e0-107d9eec851d.png)

**Comment by KirillOsenkov** [comment]
I'm guessing the viewer must be choosing a different (2017) MSBuild in the combobox, can you make sure you're choosing the 2019 MSBuild there?

**Comment by clairestreb** [comment]
Thank you for the quick response, and I definitely chose the wrong msbuild in the combobox. Sorry!
