### ISSUE TITLE
The package MSBuild.StructuredLogger depends on Microsoft.SourceLink.GitHub

### ISSUE THREAD

**Issue by inosik** [KirillOsenkov/MSBuildStructuredLog#409]
I have a project, which (transitively) depends on the package _MSBuild.StructuredLogger_. This dependency also pulls in _Microsoft.SourceLink.GitHub_. ~~I'm sure this isn't intended, because this dependency is [marked with `PrivateAssets="all"`](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/a0986c58698006412768b2202dd08409774510d4/src/StructuredLogger/StructuredLogger.csproj#L31).~~

I see this should have been fixed with #384, but this change wasn't released with this particular package yet. Do you mind publishing an update for _MSBuild.StructuredLogger_?

**Comment by KirillOsenkov** [comment]
Published https://www.nuget.org/packages/MSBuild.StructuredLogger/2.1.215, sorry I forgot to publish earlier.

You might want to explicitly add a PackageReference to this version to override the older version which was an indirect dependency. Direct dependencies take precedence over indirect dependencies.

**Comment by inosik** [comment]
Thanks!
