### ISSUE TITLE
CompilerInvocations and parsing command line executable

### ISSUE THREAD

**Issue by xoofx** [KirillOsenkov/MSBuildStructuredLog#413]
Hey,

I have found that the command line formatting and parsing in [CompilerInvocations](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/4b307e49dcf171f054239db07f6c9dbb01b36fd0/src/StructuredLogger/Analyzers/CompilerInvocations.cs#L158) is very brittle. On my machine for example I get the following on a dotnet net5.0 project:

```
C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Roslyn\bincore\csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,CS1591,1701,1702 /fullpaths ....
```

First, because the removal of csc.dll doesn't work (it matches `css.dll ` with a space at the end, likely it works on Linux but not on Windows)

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/4b307e49dcf171f054239db07f6c9dbb01b36fd0/src/StructuredLogger/Analyzers/CompilerInvocations.cs#L173-L180

The second problem more annoying is that the command `C:\Program Files\dotnet\dotnet.exe exec ` is not parse-able easily due to the lack of embraced by `"`. I'm worried that it is buried into msbuild logging and something we can't change...

Any ideas?

**Comment by KirillOsenkov** [comment]
@xoofx what do you think of this?
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/9595139c2c4fd41c8eeddc2b3643eed8f19f042c

If this solves your problem I can deploy and publish an updated NuGet package.

**Comment by xoofx** [comment]
It is certainly better, though still a bit fragile (e.g if you have your own csc exe that doesn't have necessarily this name). I'm wondering if this could also be fixed in msbuild output binlog so that it correctly escapes with `"..."`?

Side question also, I have noticed in my build of Roslyn this warning:

```
C:\code\Broslyn\src\Broslyn\Broslyn.csproj : warning NU1701: Package 'Microsoft.Build 16.4.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

It seems to originate from `MSBuildStructuredLog` which is netstandard2.0, but looks like Microsoft.Build doesn't... do you know what is wrong here?

**Comment by slang25** [comment]
Yeah that seems to be the issue here, `MSBuild.StructuredLogger` needs to target `netcoreapp2.1` or greater so that the `netcoreapp2.1` assembly is picker over the `net472` one, unfortunately there is no `netstandard` version of `Microsoft.Build` available.

**Comment by KirillOsenkov** [comment]
Sorry folks, I don't know what to do here.

Any ideas on what else I can do before I close the issue? Maybe just add NU1701 to the NoWarn list in the .csproj?

I'll close this issue but feel free to open new ones if you have concrete suggestions on either parsing command lines or NU1701.

**Comment by KirillOsenkov** [comment]
Aaah, I just now understood the targeting issue with NU1701. @jairbubbles has sent a PR to fix it:
https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/411/files#r516484413

I guess I'm a bit scared to do it but I'll think about it. At least now I understand what is going on!

**Comment by jairbubbles** [comment]
Why would you be scared of .NET Standard ? 😅

You can multitarget netcoreapp / net4xx if you prefer.

**Comment by xoofx** [comment]
So `Microsoft.Build` targets actually only [`netcoreapp2.1` and `net472`](https://www.nuget.org/packages/Microsoft.Build/16.8.0), so for the PR #411 it should probably better target `netcoreapp2.1` and not `netcoreapp3.1`, no?

**Comment by jairbubbles** [comment]
@xoofx  Well the aim is to run the application as a .NET Core application and it's only possible since .NET Core 3.1. But sure the lib could target `netcoreapp2.1` if you feel like it would bring more compatibility.

Lib =>  `net472;netcoreapp2.1` // To match exactly MsBuild
App =>  `net472;netcoreapp3.1` // WPF is only supported since 3.1

**Comment by xoofx** [comment]
Yeah, `netcoreapp2.1` only for the Lib, for the App, you can use whatever is more suitable
