### ISSUE TITLE
F-Secure blocks installation

### ISSUE THREAD

**Issue by japj** [KirillOsenkov/MSBuildStructuredLog#416]
I downloaded MSBuildLog from msbuildlog.com (version 2.1.215.0 signed on 29 October 2020 19:37:49)

During installation F-Secure blocked the installation:

![image](https://user-images.githubusercontent.com/512/100470850-53638680-30d9-11eb-8d86-672667ab1676.png)

Linking to https://www.f-secure.com/v-descs/heuristic.shtml
This is with F-Secure 17.8, not sure what additional information would be useful here.

The end result is:
![image](https://user-images.githubusercontent.com/512/100471072-ce2ca180-30d9-11eb-89e3-4de1975d1def.png)
[SquirrelSetup.log](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/5608959/SquirrelSetup.log)

**Comment by KirillOsenkov** [comment]
This is most likely a false positive that I can’t do much about. As a workaround you can build it from source yourself.

**Comment by KirillOsenkov** [comment]
Unfortunately I don't know what I could do to solve this on my end.
