### ISSUE TITLE
Neither under nor project instructions work when searching for imports

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#417]
Please, observe:
![image](https://user-images.githubusercontent.com/489792/100474081-d2db6080-30ad-11eb-8ea3-34e6a92e5116.png)

Removing the project instruction shows all the imports:
![image](https://user-images.githubusercontent.com/489792/100474173-074f1c80-30ae-11eb-8513-bea6d9132a10.png)

I realize that imports may not be reported by msbuild in the same way as other events, but I think the **under** and **project** instructions should still work, even if their implementation for imports might be completely different from other nodes.

Fixing this would be tremendously helpful.

**Comment by KirillOsenkov** [comment]
Yes, this is because imports are under a node of type ProjectEvaluation, which is not a Project. We may need to allow project() to also match project evaluations.

**Comment by KirillOsenkov** [comment]
Surprised under() doesn't work though.

**Comment by MarkKharitonov** [comment]
Here is a snapshot:
![image](https://user-images.githubusercontent.com/489792/100489392-f5876c80-30e1-11eb-8ac0-8556f30a5848.png)

**Comment by KirillOsenkov** [comment]
Ah, this is because $project doesn’t match the evaluation project root.

Try `$import under(ActivityPack)`

Not saying this isn’t a valid bug, just explaining why this is happening and suggesting a workaround.

**Comment by MarkKharitonov** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/489792/100490969-2372ae00-30ee-11eb-8aa1-5584608e1e26.png)

**Comment by KirillOsenkov** [comment]
lol this is even worse than I thought ;) Not a great experience indeed. I'll investigate how to make it better.

**Comment by KirillOsenkov** [comment]
no, hold on @MarkKharitonov, in your latest screenshot you're still not trying the query string I suggested:
https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/417#issuecomment-735017403

**Comment by MarkKharitonov** [comment]
Sorry, I pasted it on the unrefreshed thread, before I noticed your comment. You are right, it works:
![image](https://user-images.githubusercontent.com/489792/100523486-d4c12480-317e-11eb-8810-d8d06c20ed05.png)

However, there could be many projects containing the given keyword in addition to the single project which name is exactly this keyword.  In fact, on the snapshot above I was looking for the imports under the project named a8i and it returned all the imports under all the projects containing the word **a8i**

Please, prioritize https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/395

**Comment by KirillOsenkov** [comment]
A few things:

1. I made `project(...)` also match evaluations
2. You can use the `$projectevaluation` keyword just like you use the `$project` keyword, i.e. `$import under($projectevaluation ActivityPack.csproj)` should work fine
3. You can search for the evaluation ID (`id:18`) to uniquely identify an evaluation

I think we can close this one, but please open a new issue if something is not to your satisfaction

I will look at #395 soon

**Comment by MarkKharitonov** [comment]
Fantastic. Thank you.
