### ISSUE TITLE
Feature request: verification mode

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#42]
I'm using MSBuildStructuredLog to weed out a number of errors in the Roslyn build.  In particular a series of double write bugs.

Once I'm done I want to lock in these wins and ensure double writes don't come back again in the future.  I can do this today by running the structured logger in XML mode and dig through the resulting file for errors.  Very doable but requires writing a powershell script or building a small tool for the XML processing. 

My request is to have structured logger operate in a verification mode.   Essentially allow an extra parameter for an error log file.  This log file will only be created if there is an error detected during build.  That would allow for easy integration into build scripts:

``` cmd
msbuild/logger:StructuredLogger,StructuredLogger.dll;build.xml;error.xml
if EXIST error.xml (
  REM the build ... it's broken
)
```

**Comment by jaredpar** [comment]
Hmm, after looking through this more I'm not sure I had the right of it.  The log file is just that, a log.  It's the analysis phase which produces the double write diagnostics.  Perhaps instead I should be asking for the analysis to be available as a command line tool.

**Comment by KirillOsenkov** [comment]
Here's the PR that exposes the DoubleWriteAnalyzer as an API:
https://github.com/dotnet/roslyn/pull/20636

Here's the new API in StructuredLogger.dll:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/master/src/StructuredLogger/Analyzers/DoubleWritesAnalyzer.cs#L12-L17

**Comment by KirillOsenkov** [comment]
I decided against a generic analysis API for now and just hardcoded this one analyzer. In the future as we come up with more things to analyze, we can keep adding them and formulate a good API around them as we go. Right now it's hard to predict what shape that API should be.
