### ISSUE TITLE
WASM backend is unnecessarily a client/server app

### ISSUE THREAD

**Issue by Therzok** [KirillOsenkov/MSBuildStructuredLog#424]
The only usage of the server-side code is to do a get request for the sample binlog.

An idea worth trying is using WebAssemblyPrerendered as the rendering mode and having a way to distribute the binlog.

It could be an iframe loaded only when the user demands the sample, and probably the binlog would be served by a CDN - to avoid 500kb being sent on every page load if it's bundled with the app.

**Comment by KirillOsenkov** [comment]
@Therzok I've uploaded the sample.binlog to https://kirillosenkovfiles.blob.core.windows.net/kirillosenkovblob/sample.binlog

**Comment by KirillOsenkov** [comment]
Send more PRs ;)

**Comment by Therzok** [comment]
Yup, I'll do so once I get the chance. Should be one of these days.

**Comment by Therzok** [comment]
"How Blazor Performs Against Other Frameworks" https://www.telerik.com/amp/how-blazor-performs-against-other-frameworks/WEx1ZE1sRUVUWkE5S0dNbEhBNXJyUkU3T1Q4PQ2

Currently reconsidering it

**Comment by KirillOsenkov** [comment]
We dropped support for the wasm viewer :|
