### ISSUE TITLE
Contrast in dark theme

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#425]
https://twitter.com/clairernovotny/status/1335582115224752129?s=21

**Comment by KirillOsenkov** [comment]
Hopefully this is better?

![image](https://user-images.githubusercontent.com/679326/102296603-8e035680-3f02-11eb-9c0b-e1fb53d1ecc9.png)

**Comment by KirillOsenkov** [comment]
For reference this is what it used to be:
![image](https://user-images.githubusercontent.com/679326/102296645-a7a49e00-3f02-11eb-8d25-35bf462fc130.png)

**Comment by KirillOsenkov** [comment]
Fixed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/c75ea580bfe7e475e7ae40ba9f385ea152719075

**Comment by kg** [comment]
While you indeed improved it over how it was before, the contrast in dark mode is still pretty bad. Is there some way to make its brightness configurable? If not, maybe just crank it up a little bit more. Compared with (for example) GitHub's dark mode, the contrast is much lower.

This is what I'm seeing:
![image](https://user-images.githubusercontent.com/198130/119597912-cef77500-bd96-11eb-8f26-a147ae434249.png)

It's legible, but awkward enough that I went and turned dark mode back off.

**Comment by KirillOsenkov** [comment]
Yes I agree, will fix. PRs also welcome.

**Comment by KirillOsenkov** [comment]
I apologize for the delay.

I've made some fixes:
![image](https://user-images.githubusercontent.com/679326/130165765-b4c67a29-b4d2-4228-8d28-ca8bc56c1997.png)

Please send more screenshots of things that need fixing and I'll attend to those. Or review https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/9bdfcd91ece2f0db84dff579bfbc68ed78bdc57c and send PRs. 

The XAML and brush names are in Generic.xaml:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/9bdfcd91ece2f0db84dff579bfbc68ed78bdc57c/src/StructuredLogViewer/themes/Generic.xaml#L39-L56

The theme-specific colors are in ThemeManager.cs:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/9bdfcd91ece2f0db84dff579bfbc68ed78bdc57c/src/StructuredLogViewer/themes/ThemeManager.cs#L91-L133
