### ISSUE TITLE
'Build and View Log' from 'Solution Explorer' context menu

### ISSUE THREAD

**Issue by jcansdale** [KirillOsenkov/MSBuildStructuredLog#43]
It would be great if I could right click on a solution or project inside the 'Solution Explorer' and 'Build and View Log'. MSBuildStructuredLog could be distributed as a Visual Studio package and always be at my fingertips. 😄 

Just launching the application form Visual Studio would be handy, it needn't be anything fancy.

**Comment by modulexcite** [comment]
@jcansdale, I use the "External Tools" option to open a solution MSBuildStructuredLog from Visual Studio.

Go to Tools-->External Tools and click on Add and use the following options to open the solution in MSBuildStructuredLog.

![vs-msbuildstructuredlog](https://cloud.githubusercontent.com/assets/12729391/20180585/0ae8806a-a729-11e6-991d-e0c05c0093cb.png)

For Arguments, type the following:
/c %LocalAppData%\MSBuildStructuredLogViewer\Update.exe --processStart StructuredLogViewer.exe --process-start-args "$(SolutionDir)\$(SolutionFileName)"


You can modify the above arguments to "Build and View" if you like.

**Comment by jcansdale** [comment]
Works great, thanks for the tip!

**Comment by KirillOsenkov** [comment]
Note that http://www.panopticoncentral.net/2017/10/19/getting-visibility-into-design-time-builds/ is now available.
