### ISSUE TITLE
Project nodes should not be under project nodes

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#432]
Please, observe:
![image](https://user-images.githubusercontent.com/489792/103392582-a374a500-4aec-11eb-8447-15b16831ea81.png)

How come there are project nodes under the DataSvc.csproj node? Shouldn't they be under some `$task MSBuild` ?

**Comment by KirillOsenkov** [comment]
Yes, this is a bug in MSBuild: 
https://github.com/dotnet/msbuild/issues/5473

**Comment by MarkKharitonov** [comment]
All of the projects in the solution in question are non SDK projects. Is the issue still relevant to them?

**Comment by KirillOsenkov** [comment]
I don't know whether SDK-ness is relevant here. Will have to investigate into MSBuild.

https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/358 is the same underlying issue.

**Comment by MarkKharitonov** [comment]
I still do not get it. Shouldn't https://github.com/dotnet/msbuild/issues/3939 have resolved it?

**Comment by KirillOsenkov** [comment]
Yes, but there's still a bug. It works most of the time, but not always. I need to find time to investigate why.

https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/137 is also a dupe.

**Comment by KirillOsenkov** [comment]
MSBuild has now been fixed and we should see it in 16.9.

**Comment by MarkKharitonov** [comment]
Extra prima good.
