### ISSUE TITLE
CLI option for finding double-writes

### ISSUE THREAD

**Issue by jakubsuchybio** [KirillOsenkov/MSBuildStructuredLog#440]
Hi,
it would be great, if we could parse binary log with MSBuildStructuredLog to get out only double-writes.
I'd like to add this step for checking double-writes into our build pipeline and this would be a great help to get them in like xml or json format.

I think this kinda relates to #292, but this is much smaller.

Thanks!
Btw great software!

**Comment by KirillOsenkov** [comment]
Yup, that's planned. For now you can reference StructuredLogger.dll yourself and write a simple console app that calls this API:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/87232c03da870e1eacdaed18785bc756b9e459e2/src/StructuredLogger/Analyzers/DoubleWritesAnalyzer.cs#L12

Read here for more API examples:
https://msbuildlog.com/#api

**Comment by KirillOsenkov** [comment]
In fact I think Roslyn already does this here:
https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Tools/BuildBoss/StructuredLoggerCheckerUtil.cs

**Comment by jakubsuchybio** [comment]
This is better than I expected! Thank you! I think this more than solves my problem, so closing the issue.
