### ISSUE TITLE
Memory leaks when running standalone application

### ISSUE THREAD

**Issue by jefernn-ms** [KirillOsenkov/MSBuildStructuredLog#441]
Executing more than one build increases memory usage when running the application as standalone. The GC doesn't seem to be able to collect this memory until the application is closed.

This hints at memory leaks and becomes increasingly noticeable when a few dozen projects are built. Building the projects a few times easily reaches 3-4GB in memory.

**Comment by KirillOsenkov** [comment]
Thanks, fixed in 2.1.305.

Note that the app is using Server GC so you may see around 1 GB reserved after you open and close a large binlog. But it should stop holding onto previous binlogs as you open new ones.
