### ISSUE TITLE
Crashes when trying to open a log file on Linux Fedora 33

### ISSUE THREAD

**Issue by omajid** [KirillOsenkov/MSBuildStructuredLog#445]
Following the advice on https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/444, I managed to get this building. But trying to open a log crashes immediately:

https://user-images.githubusercontent.com/174451/107392967-38919300-6ac8-11eb-8589-0fb7075efbea.mp4

Is there some way to show the logs or the exception stack trace?

**Comment by KirillOsenkov** [comment]
What OS is this? Perhaps try using VSCode to debug?

**Comment by dagood** [comment]
That's Fedora 33 (details in https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/444), and I get the same result on Fedora 31. I also tried RHEL 8, where it worked fine for me. I don't have easy access to my repro right now, so I can't try to grab more info, but wanted to mention the OS if someone else wants to try.

**Comment by omajid** [comment]
Adding a few `Console.WriteLine` shows that it crashes here:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/ea577d4a91e7b3e6001d24220eba4e523ee8b456/src/StructuredLogViewer.Avalonia/MainWindow.xaml.cs#L410

The error sounds quite a bit like https://github.com/AvaloniaUI/Avalonia/issues/3248. 

I manually updated the project to `0.10.0` and that leads to a bunch of other errors, but I can at least open a log file after these changes: https://gist.github.com/omajid/db178282f662eb5dec8f9347900b09e7.
