### ISSUE TITLE
Please, include project.assets.json in the binary log

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#449]
This is not a bug, but a feature request.

Having  project.assets.json is crucial to troubleshoot nuget related issues. Would be a great addition to the binary log.

**Comment by KirillOsenkov** [comment]
I have a plan to fix this here https://github.com/dotnet/msbuild/issues/3529

**Comment by MarkKharitonov** [comment]
Oh, you have it already. Feel free to close this one.
