### ISSUE TITLE
StackOverflow when right clicking on search result

### ISSUE THREAD

**Issue by hokb** [KirillOsenkov/MSBuildStructuredLog#453]
Steps to reproduce: 
1) open binlog (don't know if it is specific to our binlog. Ours includes multiple projects as project dependencies. The main project failed to build.)
2) search for something which leads to search result items in the main (failed) project: "ProjectFile" 
3) Right-click on any entry displayed in the search results of the failed project. 
_> Many MessageBoxes pop up. Eventually: StackOverflowException

Notes: This happens deterministically when clicking on such search results associated with the failed project log. It does not happen when clicking on search results for other projects in the binlog. I don't know if this is important, though. 

Sorry, but due to the SO exception I cannot copy the text from the message box. Neither have I been able to acquire a useful stacktrace, except by the following screenshot:

![2021-03-11 13_12_13-Crash Screenshop Stackoverflow Exception - MSBuild S](https://user-images.githubusercontent.com/1593284/110785891-c13c5400-826b-11eb-95ae-f3d257304fe0.png)

**Comment by KirillOsenkov** [comment]
Do you have all the Windows updates installed? There was a bug in WPF that was fixed in January via Windows Update

**Comment by KirillOsenkov** [comment]
I've attempted to fix this in 2.1.364. Would you mind updating the viewer to latest and seeing if this goes away? Thanks!

**Comment by hokb** [comment]
I first tried updating Windows as your suggestion. This already removed the error completely on my setup. Thank you!!
