### ISSUE TITLE
Windows 10 warns when running setup

### ISSUE THREAD

**Issue by jeremymeng** [KirillOsenkov/MSBuildStructuredLog#47]
![image](https://cloud.githubusercontent.com/assets/7583839/20686679/7d6fcdac-b56e-11e6-9e80-12e7d8305a79.png)

**Comment by KirillOsenkov** [comment]
Thanks, this is expected. The SmartScreen engine wasn't trained that this file was downloaded a lot yet. Just click Run anyway ;) Nothing else I can do about this :)

**Comment by gentoo90** [comment]
Windows adds a special flag to files that were downloaded from the Internet, which prevents them from running. You can remove it by clicking `Unblock` in the files properties.
![default](https://user-images.githubusercontent.com/1297574/42804153-c02d5408-89b0-11e8-8aba-6424baf3383f.png)
Also, this should probably be added to `README`.

**Comment by KirillOsenkov** [comment]
The installer is now signed, so there should be less friction during installation.
