### ISSUE TITLE
[REGRESSION] Searching the log is broken.

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#486]
I am using the version 2.1.472
Binary log is attached (rename the extension back to binlog).
Try searching for `$task csc` - nothing is found, yet it is there:

![image](https://user-images.githubusercontent.com/489792/116793429-b85e4680-aa94-11eb-98ec-751a3a31e2a5.png)

[msbuild.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/6410200/msbuild.zip)

**Comment by KirillOsenkov** [comment]
Fixed, thanks. Try updating to 2.1.476.

**Comment by MarkKharitonov** [comment]
I confirm it works. Thank you.
