### ISSUE TITLE
Closing MSBuild Structured Log Viewer Issue

### ISSUE THREAD

**Issue by MaherJendoubi** [KirillOsenkov/MSBuildStructuredLog#5]
Hi,

I get the following dialog box when I close MSBuild Structured Log Viewer:

![image](https://cloud.githubusercontent.com/assets/1798510/15264131/69ec4124-1970-11e6-8ea5-48e4eb1b28b2.png)

Thanks.

**Comment by KirillOsenkov** [comment]
Can you please look in %localappdata%\Microsoft\MSBuildStructuredLog\Log.txt and send the contents? I wonder what exception is that.

**Comment by MaherJendoubi** [comment]
@KirillOsenkov There is no Log.txt file in %localappdata%\Microsoft\MSBuildStructuredLog :
![image](https://cloud.githubusercontent.com/assets/1798510/15267263/213039ac-19bd-11e6-9d42-f9363e02c513.png)

**Comment by MaherJendoubi** [comment]
It crashes without logging.

**Comment by KirillOsenkov** [comment]
You're not under Microsoft folder :) Carefully check the path I mentioned above.

**Comment by KirillOsenkov** [comment]
Also, in the dialog in your screenshot, if you scroll a little bit, under Signature du problem 09: what are you seeing? 

Is it AbandonedMutexException? "Leaked a Mutex!"?

What if you uninstall MSBuildStructuredLog through Add/Remove Programs and then try running it again?

**Comment by KirillOsenkov** [comment]
OK if I'm continuing to guess here, can you check if perhaps your TEMP path is full? If it has more than ~65000 files you'll start experiencing errors in many apps, not just this one.

**Comment by KirillOsenkov** [comment]
No, it's likely not the TEMP folder full.

I'm guessing you're running into this issue in Squirrel:
https://github.com/Squirrel/Squirrel.Windows/issues/587

Squirrel is the installer library I'm using.

**Comment by MaherJendoubi** [comment]
@KirillOsenkov I really apologize to reply so late. Here is what I find the Log.txt:

System.Threading.AbandonedMutexException: Leaked a Mutex!
   à Squirrel.SingleGlobalInstance.Finalize()

Thanks.

**Comment by KirillOsenkov** [comment]
This is a Squirrel bug. I'm going to close this bug and after Squirrel is fixed I'll update my version of Squirrel, hopefully fixing the issue then.

Thanks again for reporting!
