### ISSUE TITLE
Feature Request:  Framework 1.0 - 3.5

### ISSUE THREAD

**Issue by tonkajuris** [KirillOsenkov/MSBuildStructuredLog#50]
I tried this out today to build older version of .Net framework.  This seems like a great tool to help with that.  Could we select the version of the framework to target and then build?
Nice Work thanks!

**Comment by KirillOsenkov** [comment]
You can try to pass /p:TargetFrameworkVersion=v2.0 like this:
![image](https://cloud.githubusercontent.com/assets/679326/21625187/5d93c3a4-d1bf-11e6-94ff-78242f5c1459.png)

**Comment by tonkajuris** [comment]
Yeah oops apologies.  I didn't realize it was that easy :+1: 
Thanks!
