### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by joperezr** [KirillOsenkov/MSBuildStructuredLog#502]
This is mostly just an appreciation issue but couldn't find a better way to send it out.

My day-to-day job has the fun perk of having to diagnose a whole bunch of different and weird build issues, and you have no idea of how much more productive I am ever since I started using `/bl` magic. Thanks to @KirillOsenkov and everybody else that contributes to this repo, the features going in to newer versions of the tool like the improvements on search for project evaluation as well as improvements on searching properties and items are just time savers, and help immensely in quickly diagnosing hard problems every day. Thanks for making so many devs much more efficient!

**Comment by KirillOsenkov** [comment]
Love to hear it’s helpful!
