### ISSUE TITLE
Project Items not displayed with metadata

### ISSUE THREAD

**Issue by AArnott** [KirillOsenkov/MSBuildStructuredLog#529]
I thought this used to work, but I'm not seeing metadata under items here:
![image](https://user-images.githubusercontent.com/3548/130628055-a0962fb3-912c-4af5-a7ff-e5fa4b9f40c9.png)

I'm sure there is metadata on that item. I don't see any metadata on any of them.

**Comment by KirillOsenkov** [comment]
Fixed in 2.1.561, thanks for reporting!
