### ISSUE TITLE
MSBuildStructuredLogViewer crash when clicking "Open Log File"

### ISSUE THREAD

**Issue by daxian-dbw** [KirillOsenkov/MSBuildStructuredLog#54]
I installed the version 1.0.123 and found it crashes when I click "Open Log File". The file `LoggerExceptions.txt` is attached. The OS is windows 10 Home, with .NET 4.6.2 installed.

[LoggerExceptions.txt](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/853947/LoggerExceptions.txt)

**Comment by KirillOsenkov** [comment]
Thanks for the detailed report. I've published an update (1.0.127), can you start the app again and wait for it to update, then restart to see if this fixes your problem? If not, provide LoggerExceptions.txt like you did earlier. Thanks!

**Comment by daxian-dbw** [comment]
The version 1.0.127 works fine on my machine. This is a great tool and it helps me a lot. Thank you!
