### ISSUE TITLE
Question - what does BuildAnalyzer do exactly?

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#541]
I am trying to figure out how to work programmatically with a binary log. I understand I can read all the records using the `BinLogReader.ReadRecords` low level API. I wonder what are the capabilities of the higher level API, for example `BuildAnalyzer.AnalyzeBuild` - what does it do exactly?

**Comment by KirillOsenkov** [comment]
I wrote a doc page about it here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Reading-binlog-files-programmatically#analyzebuild

**Comment by MarkKharitonov** [comment]
Thanks, That answers my question.
