### ISSUE TITLE
How can I filter to view only the project nodes that were invoked with the specific target/task that was actually executed, rather than skipped?

### ISSUE THREAD

**Issue by MarkKharitonov** [KirillOsenkov/MSBuildStructuredLog#544]
E.g., when filtering by `$project` we can get something like that:

![image](https://user-images.githubusercontent.com/489792/143784654-dc1494fa-d485-48b2-b2be-ce6d112404db.png)

These are all project nodes alright, but the problem is that the same project was invoked many times with different targets. I am interested in the invocations associated with the specific target.

Suppose I want to see all the project nodes that correspond to the Build target? Or better - Csc task. Because Build target may have been skipped. 

I can try to view the Build target alone:

![image](https://user-images.githubusercontent.com/489792/143784863-56b95d3a-4ae1-4463-b764-6e75570fd8ec.png)

Alas:

- it does not focus on the Build target only.
- it shows all the Build targets, even those that were skipped.

To see the projects that were actually built one can search for `$csc`:

![image](https://user-images.githubusercontent.com/489792/143784947-c5f049f6-1ee6-4297-ad96-0f5154a3aae0.png)

However, the filter is for the task nodes, not projects and so if I want to stick `$time`, then it would measure the task duration, not the project.

![image](https://user-images.githubusercontent.com/489792/143784998-591b8c6e-1e8e-4802-8e05-20de06e13601.png)

Is there a way to do what the title asks?

**Comment by KirillOsenkov** [comment]
Adding $time is very limited right now, so you can only do that for simple results.

**Comment by KirillOsenkov** [comment]
If you want to filter projects that have a Csc task you can search for `$csc project(filter for projects goes here)`

**Comment by MarkKharitonov** [comment]
Yes, I am aware. But the question is in general about projects. If we could filter projects by targets executed by them (really, not just skipped) then we could combine it with `$time` and get really useful insights.

**Comment by KirillOsenkov** [comment]
Yes, there's an open issue to get $time to work with all search results and in more circumstances: https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/534

As always, the current workaround is to write a simple console tool that reads the binlog programmatically and does what you want using the API.

**Comment by MarkKharitonov** [comment]
Got it.
Thanks.
