### ISSUE TITLE
Add support for binlog 14

### ISSUE THREAD

**Issue by GeertvanHorrik** [KirillOsenkov/MSBuildStructuredLog#545]
_I tried searching for existing issues, but couldn't find any_

When publishing a .NET 6 project (with Blazor project), it tells me the version is not supported:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/1246444/144042971-f8aea284-62f9-49f0-b22b-c237d6c7de76.png">

To generate this log, I use this command line:

```
C:\Program Files\dotnet\sdk\6.0.100\MSBuild.dll ... /binarylogger:C:\source\myproject\output\Release\MsBuild_myproject_pack.binlog;ProjectImports=Embed
```

Is there a way to add support for version 14 *or* a way to output a different version?

**Comment by KirillOsenkov** [comment]
It is supported, just update the viewer app to 2.1.561. It usually auto-updates when you restart the app.

**Comment by GeertvanHorrik** [comment]
That is fantastic news, thanks! I downloaded this via Chocolatey, maybe that is an outdated version?

**Comment by KirillOsenkov** [comment]
Yes, I need to push the latest installer to choco, sorry about that.

**Comment by GeertvanHorrik** [comment]
No problem, I can confirm that the one via Squirrel works. Thanks for your response, it's much appreciated!
