### ISSUE TITLE
I can't find release artifacts for Avalonia.

### ISSUE THREAD

**Issue by mfilippov** [KirillOsenkov/MSBuildStructuredLog#550]
I found a guide about macOS builds: https://github.com/KirillOsenkov/MSBuildStructuredLog#building--running-the-avalonia-version-on-mac, but I can't find zip artefact on Releases.

**Comment by slang25** [comment]
They can be found on the AppVeyor outputs, however recently they have stopped working for me on macOS, I think it's because they are built for M1 only, I have to build locally today.

**Comment by KirillOsenkov** [comment]
Yes I suppose I should be including the Mac artifacts when publishing a Release. Ideally we'd build both Intel and M1 bits.

**Comment by slang25** [comment]
It looks like both are being built, however the last one wins because they will both output to the same path.

I've looked at building a universal app, but I don't think it's simple today with .NET, I've tried using lipo manually to combine the two outputs, but it's not just the hostapp process that needs to change between architectures, for now we might just need 2 separate artifacts.

**Comment by KirillOsenkov** [comment]
Hmm, do I need to build on Mac? I built on Windows and didn’t see any zip files. How do I obtain a zip file to publish to Releases?

**Comment by slang25** [comment]
If you run the cake build script it will produce the macOS builds and zip them up, you don't need a mac to do it as the sdk will generate the apphost mac process that will bootstrap the app, the rest is all typical dotnet artifacts.

**Comment by slang25** [comment]
What do you think about switching to GitHub Actions? I need to update how versioning works and select the appropriate artifacts:
https://github.com/slang25/MSBuildStructuredLog/pull/1

**Comment by slang25** [comment]
In that PR I'm building both architectures for mac

**Comment by KirillOsenkov** [comment]
Ah, OK, I haven't looked into the Cake bit at all yet. Yeah I suppose it's time to move to GitHub Actions.

**Comment by jjmanton** [comment]
@slang25 @KirillOsenkov Does a new release need to be triggered somehow? I am interested in the Mac artifacts as well, and see the PR above was merged.

**Comment by KirillOsenkov** [comment]
I'm not sure what I should do locally to produce the artifacts to publish to the release

**Comment by slang25** [comment]
You can grab the macOS per-architecture builds from the CI artifacts here:
https://ci.appveyor.com/project/KirillOsenkov/msbuildstructuredlog/builds/42050519/artifacts

I'm still interested in adding GitHub Actions as I think it would be easier to build on macOS/linux for the mac build, that way the user won't need to `chmod +x` the executable before it's usable.

There are a few outstanding things I'd need to solve/understand
- The version number today is dictated by AppVeyor, if we wanted to move the build, or build on both platforms (I think that would be a good stepping-stone) then we might need to adopt something like [GitVersion](https://gitversion.net/) or [MinVer](https://github.com/adamralph/minver)
- What's the integration process with SignPath, is that just for the Windows build, and what happens after the webhook is triggered? If it is Windows only then we can defer this while moving the macOS build to GitHub Actions.

**Comment by KirillOsenkov** [comment]
OK cool, I have uploaded both zips to the latest Release.

We should rename both zips to not have spaces, since GitHub Release replaces them with dots.
