### ISSUE TITLE
Differentiates items and item metadata nodes by colour

### ISSUE THREAD

**Issue by drewnoakes** [KirillOsenkov/MSBuildStructuredLog#557]
Currently, in the dark theme at least, both items and their metadata have the same colour. Metadata items are prefixed with the work "Metadata", but it's not as easy to notice as a colour change.

My vote would be to make metadata notes a darker version that green, and leave the item colour alone.

What do people think? Would this be helpful?

## Current

![image](https://user-images.githubusercontent.com/350947/151732227-9d680caa-4253-4070-9fe9-0314221d8d9f.png)

## Darker metadata

This image shows the bits I'd change, and helps visualise that.

![image](https://user-images.githubusercontent.com/350947/151732720-1f485b69-9c54-49f1-b037-3ba3a849c843.png)

I'm not attached to the particular style used. Perhaps a new hue could be used for metadata. I just want to be able to distinguish item metadata nodes a bit more, and differentiate between property names and their values.

**Comment by KirillOsenkov** [comment]
I'd be OK with that. The dark theme looks OK, wanna pick something for light theme too?

**Comment by KirillOsenkov** [comment]
How about this:

![image](https://user-images.githubusercontent.com/679326/151739729-30b107f4-b998-4d7f-aebe-20384fa4ba33.png)

**Comment by KirillOsenkov** [comment]
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/c31b7572c96f490cbb8b33a4f0116367b7b6b411

Dark theme:

![image](https://user-images.githubusercontent.com/679326/151739885-6e531325-173c-4359-b8a8-5b2c55a6b004.png)

**Comment by drewnoakes** [comment]
That looks great to me! Much easier to read. Thanks @KirillOsenkov.
