### ISSUE TITLE
Collection was modified

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#558]
https://github.com/xoofx/dotnet-releaser/issues/5#issuecomment-1026067671

**Comment by KirillOsenkov** [comment]
@rgwood I have a potential fix here: https://www.nuget.org/packages/MSBuild.StructuredLogger/2.1.624

I'm flying blind as I couldn't repro the bug on my machine.

Could you please give it a try? Just replace StructuredLogger.dll from the NuGet above in dotnet-releaser and see if the intermittent logger crashes go away. If it's not easy to replace we can ask @xoofx to bump to 2.1.624 again. But of course I'd prefer to validate first before bumping it over and over again.

**Comment by KirillOsenkov** [comment]
I wrote some reflection against generic types blindly without testing or debugging, so my confidence in the fix is... humble. But let's give it a shot.

**Comment by rgwood** [comment]
Thanks! I’m on vacation and might not be able to rest for a few days but I’ll set a reminder.

**Comment by rgwood** [comment]
Had some time in the airport, cloned the latest dotnet-releaser and ran it 5x but unfortunately (fortunately?) I couldn’t reproduce this exception.

**Comment by KirillOsenkov** [comment]
I'll close this for now but feel free to reopen if you still see any issues with 2.1.624.

Thanks!
