### ISSUE TITLE
When there are build errors, it's impossible to see what led to it

### ISSUE THREAD

**Issue by kzu** [KirillOsenkov/MSBuildStructuredLog#56]
Open the attached log, which contains a failed build. I need to diagnose why, but all the UI shows is the error, and none of the actual executions :(

![image](https://cloud.githubusercontent.com/assets/169707/24803037/56db5e9a-1b80-11e7-801d-a6e5ea4345a4.png)

[ios.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/905760/ios.zip)

**Comment by KirillOsenkov** [comment]
This should be fixed now.
