### ISSUE TITLE
Save window position

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#566]

**Comment by RussKie** [comment]
...and geometry (i.e., the size of the window when it was closed). And do no open in the maximized state by default.

Thank you

**Comment by ltrzesniewski** [comment]
> And do not open in the maximized state by default.

I always use it maximized. I'd like it to be maximized if it was maximized last time I used it.

**Comment by KirillOsenkov** [comment]
Definitely, we’ll preserve the window state as well

**Comment by RussKie** [comment]
Thank you!
