### ISSUE TITLE
Search results show wrong TFM

### ISSUE THREAD

**Issue by gix** [KirillOsenkov/MSBuildStructuredLog#567]
In a project with multiple target frameworks, top-level nodes in the search results show the wrong TFM. Clicking the result selects the correct project node in the log.

![image](https://user-images.githubusercontent.com/51795/153240635-bb1961d9-01db-4fb0-8257-56283c952881.png)

Edit: It looks like the search result tree does not distinguish by TFM as I can see targets belonging to different TFMs below the same project node.

**Comment by KirillOsenkov** [comment]
I think we coalesce under the same project, ignoring the TFM. I’ll see if we can start including the TFM in the project identity.

**Comment by KirillOsenkov** [comment]
I think I fixed this recently
