### ISSUE TITLE
Find in Timeline/Tracing

### ISSUE THREAD

**Issue by reznet** [KirillOsenkov/MSBuildStructuredLog#572]
Is there a way to find a log in the Timeline or Tracing view?  I'm debugging a race condition in a muli-core build and would like to see what other tasks are running at the same time.  I have an error line selected in the Search Log view and would like the find the corresponding timestamp/record in the Timeline or Tracing view, with Tracing view being preferred.  However, there doesn't seem to be a way to find anything in the Tracing view without scrolling and visually searching.  Is there already a way to select a record in the Log view and find the corresponding record in the Tracing view?  Would this be possible?

suggested label: enhancement

**Comment by KirillOsenkov** [comment]
You can right-click on a node in the tree and say Go To Timeline. Not sure this is implemented for tracing.

From the timeline, you can go back to the tree by double-clicking a rectangle.

**Comment by KirillOsenkov** [comment]
thanks, I'd love to take a look someday, but not sure when I will find time. If you submit a PR, I'll remember to look into it when I have time. Thanks!

**Comment by reznet** [comment]
submitted #573

**Comment by KirillOsenkov** [comment]
I've figured out why the scrolling to the item didn't work the first time. The sizes of the blocks weren't calculated yet, so we don't know to which location to scroll to. If we call GoTo after a layout has happened, we get the real coordinates.
