### ISSUE TITLE
Items not shown

### ISSUE THREAD

**Issue by uecasm** [KirillOsenkov/MSBuildStructuredLog#575]
* You have the latest version: 2.1.627

A log of a .NET 6 app compiled using VS2022 and Project System Tools (via Open Logs External) is showing Targets and Properties but absolutely no Items at all (which makes interpreting the logs difficult); neither at the top level nor inside Targets.  Search also does not report them.

(Also, when trying to use the integrated "Open Logs" within VS2022, it just reports a "value cannot be null" exception.  But I guess that's a different project?)

When using VS2017, Items appear in the logs as expected, both in and out of VS.

```
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.1.0.7609
```

**Comment by KirillOsenkov** [comment]
Unfortunately this is a known problem with the VS extension and not something I can fix

**Comment by KirillOsenkov** [comment]
Consider using https://msbuildlog.com/#MSBUILDDEBUGENGINE to get binlogs from VS instead of the legacy Project System Tools extension.
