### ISSUE TITLE
Skipped targets are not displayed in the expected order

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#58]
Build the following project with the `/bl` option and open the log in the structured log viewer:

```xml
<Project DefaultTargets="Build">
  <Target Name="Build" DependsOnTargets="SkippedTarget">
    <Message Text="Build" Importance="high" />
  </Target>
  <Target Name="SkippedTarget" Condition="'true' == 'false'">
    <Message Text="SkippedTarget" Importance="high" />
  </Target>
  <Target Name="MessageTarget" BeforeTargets="SkippedTarget">
    <Message Text="MessageTarget" Importance="high" />
  </Target>
</Project>
```

**EXPECTED:** The `MessageTarget` target is nested somewhere under the `Build` target, before the Message task from the `Build` target, indicating it ran first.  Something like the following, except with `SkippedTarget` grayed out:

![image](https://cloud.githubusercontent.com/assets/145043/24990800/505a6be8-1fcb-11e7-8ef0-28e68cf30069.png)

**ACTUAL:** The `MessageTarget` is displayed nested under `SkippedTarget`, which is after the `Build` target, giving the impression that the `MessageTarget` ran after Build instead of before it.

![image](https://cloud.githubusercontent.com/assets/145043/24990822/735bd30c-1fcb-11e7-8f9f-0c451924884d.png)

**Comment by eerhardt** [comment]
I just hit this as well.  SUPER confusing.

![image](https://cloud.githubusercontent.com/assets/8291187/26514028/ad0707b2-4234-11e7-862e-218de6935d03.png)

`ResolvePackageDependenciesForBuild` runs before `ResolveAssemblyReferences`, but looking at this view, it really looks like `ResolvePackageDependenciesForBuild` ran after `ResolveAssemblyReferences`.

**Comment by KirillOsenkov** [comment]
Sorry about that. It's actually an MSBuild issue and I have a plan on how to fix this.

**Comment by KirillOsenkov** [comment]
Thanks for the repro case. The new behavior is now:
![image](https://user-images.githubusercontent.com/679326/27212949-879dfdf2-5218-11e7-9e17-359aacb2e15c.png)
