### ISSUE TITLE
Sort Evaluated Property with Case Insensitive 

### ISSUE THREAD

**Issue by yuehuang010** [KirillOsenkov/MSBuildStructuredLog#581]
I am not sure if it is by design or not.  The Property Evaluations are sorted with case sensitive.  MSBuild treats properties as insensitive, I suggest the result should also be sorted as insensitive as well.

**Comment by KirillOsenkov** [comment]
Sure, like this?
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/2281e390e0ff977297d36525be178f100056e437
