### ISSUE TITLE
Moving to net6.0

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#586]
Several projects in the code base target `net5.0` which is going out of support in four days (May 10th).

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Are there any reasons why we can't move the projects forward to `net6.0`? Happy to send a PR that does this but wanted to check before sending the PR.

**Comment by KirillOsenkov** [comment]
yes, feel free to update from net5.0 to net6.0, I just never had time
