### ISSUE TITLE
Compiler server messages showing up under Analyzer Summary node

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#587]
A few releases ago the C# / VB MSBuild task began outputting diagnostic messages for the compiler server. This was done to better enable detecting cases where the server was failing, restarting due to analyzer conflicts, etc ... Effectively make binlogs significantly more actionable for compiler developers. 

Unfortunately these messages are showing up under the "Analyzer Summary" node which is unexpected. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/146967/167178359-fafdb762-daea-4421-b711-4a5041feffce.png)

These messages all start with `CompilerServer:` and should be filtered away in [CscTaskAnalyzer](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/src/StructuredLogger/Analyzers/CscTaskAnalyzer.cs).

**Comment by jaredpar** [comment]
BTW: i'm planning on fixing this but wanted to file an issue vs. sending a PR without an issue.

**Comment by KirillOsenkov** [comment]
Cool, you probably want to look at this location somewhere:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/dab479efbaf581ae785e2f0158809b45be378193/src/StructuredLogger/Analyzers/CscTaskAnalyzer.cs#L17
