### ISSUE TITLE
Property reassignment messages clutter up the view

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#59]
Build a simple project with the `/bl` option and open its binary log in the structured log viewer.  You will mostly see a bunch of "Property Reassignment" messages.  For more complex projects (for example, building the .NET CLI repo), there will be an overwhelming amount of these messages, making it hard to browse through the log.

Ideally these messages would be nested under the Properties node of the project where the reassignment occurred.  If that's not currently possible, it would at least help to put them all under a single top-level node.

**Comment by KirillOsenkov** [comment]
This should now be fixed.
