### ISSUE TITLE
Get a list of all known properties and items in given context

### ISSUE THREAD

**Issue by magol** [KirillOsenkov/MSBuildStructuredLog#591]
I want to have a new window that show all known properties and items for selected node in the log. 
In the window, I also want to make it possible to make a properties/items as favorite, so that it is always on the top. 
I want to be able to select a property/item and find the location in the log where it get its current value.

**Comment by KirillOsenkov** [comment]
Have you checked the Properties and items tab in the bottom left?

Finding where a property is initially assigned is tricky because MSBuild doesn't log this information.

For items, you can search for `$additem Compile` to see where items get added.
