### ISSUE TITLE
How to get items and properties from api?

### ISSUE THREAD

**Issue by Genuineh** [KirillOsenkov/MSBuildStructuredLog#597]
This is a nice project, thanks for your contribution.

I wanted to get items or properties like reading invocations from api, but i didn't konw how to do that.

**Comment by KirillOsenkov** [comment]
Here's a sample that implements searching in the binlog using the command line:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/src/BinlogTool/Search.cs

Once you have the tree data structure you can programmatically iterate over it, find what you need, and then inspect the properties and items for that project.

Here's how the Properties and Items tab works in the actual viewer:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/src/StructuredLogger/Search/PropertiesAndItemsSearch.cs

**Comment by Genuineh** [comment]
Thanks!
