### ISSUE TITLE
Styles for Live Blazor website

### ISSUE THREAD

**Issue by kant2002** [KirillOsenkov/MSBuildStructuredLog#598]
I notice some glitches in UI on Desktop in the tree view, so I take liberty and play with Chrome to improve status

This small snippet should vertically align icon in the tree with text representing the tree.
```
.ui-treenode-content div {
    vertical-align: middle;
}

img {
    padding: 0 6px 3px 0;
}
```
If you add this style `margin-bottom: 0.5rem;` directly to `Dark Mode` button, I think gap from bottom and from top would be same, and consistent with other 3 buttons.

I see that icons in the tree do not aligned between nodes with children, and child-less nodes. Have no fix for that.

**Comment by kant2002** [comment]
@KirillOsenkov any chance this would be applied? or it is already?

**Comment by KirillOsenkov** [comment]
So sorry, I forgot about this. Been super busy. I’ll try to take a look soon. Meanwhile, if you want, you could send a PR with before and after screenshots, might make it faster for me  to merge.

**Comment by kant2002** [comment]
I did not find source code for website, otherwise I would just send PR. Can you point me on sources?
