### ISSUE TITLE
Long messages should not be truncated in the lower "details" pane

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#60]
Long messages are currently truncated with the message "(Ctrl+C to copy full text)".  There should be a way to view the full message without having to copy it to an external editor.  Probably a good way to do this would be to show the untruncated text word-wrapped in the yellow pane at the bottom.

![image](https://cloud.githubusercontent.com/assets/145043/24991055/27647e16-1fcd-11e7-8b12-685aac9cb74f.png)

**Comment by KirillOsenkov** [comment]
Yes I need to fix this.

**Comment by KirillOsenkov** [comment]
I've now implemented this. Press SPACE, ENTER or double-click on a node with long text to open the built-in text editor with that text.
