### ISSUE TITLE
Support searching based on node hierarchy

### ISSUE THREAD

**Issue by dsplaisted** [KirillOsenkov/MSBuildStructuredLog#61]
It would be useful to be able to search for items based on their parent or ancestor nodes.  For example, it would be useful to be able to filter results to those that occurred when running a particular target.  One possible syntax for this would be something like `$target _HandlePackageFileConflicts \ System.IO.dll` to search for System.IO.dll under the `_HandlePackageFileConflicts` target.  Since targets that a target depends on are nested under the target, it would also be helpful to be able to specify whether to search only under the specified target or under any other targets that are shown nested within it.

**Comment by KirillOsenkov** [comment]
I've chosen the under() clause for the syntax:
`System.IO.dll under($target _HandlePackageFileConflicts)`
