### ISSUE TITLE
(not an issue) Need some tips to extract information from binlog file

### ISSUE THREAD

**Issue by munerf** [KirillOsenkov/MSBuildStructuredLog#617]
Hello,

Thank you for your awesome project, /bl is a life saver! 

I wrote a very basic binlogger based on yours to retrieve some build information, timings, messages, etc. But I want to deprecate it and use yours then programmatically extract the information I need.

Is it possible for me to extract information about project build time, solution build time, and error messages? 
I've looked at [this](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/ddea3ae1d287ad199cc08b2d7465ba12af57ebfd/src/BinlogTool/Search.cs#L53), but i'm not sure how to get, i.e: error message from a build or event all the runtime of each target of a build.

Could you share some tips? 
Thanks!

**Comment by KirillOsenkov** [comment]
Here's a page about reading binlog files programmatically:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/Reading-binlog-files-programmatically

**Comment by yuehuang010** [comment]
Plug.  If you think your feature can be helpful to others, then consider contributing to binlog viewer itself.
