### ISSUE TITLE
The application “StructuredLogViewer.app” can’t be opened.

### ISSUE THREAD

**Issue by RbBtSn0w** [KirillOsenkov/MSBuildStructuredLog#639]
When I download "StructuredLogViewer-arm64.zip" from GitHub.

and open it was wrong. 

was something happing? I need your help.

Env:

❯ dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/bin/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by KirillOsenkov** [comment]
What exactly was wrong? Was there an error message? Can you include a screenshot?

There are some instructions here for making it work on a Mac, have you tried these?
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/README.md#building--running-the-avalonia-version-on-mac

**Comment by RbBtSn0w** [comment]
> 
![image](https://user-images.githubusercontent.com/1135031/207278569-4a258ab8-584a-49c1-93bc-14ea8f22da58.png)
![image](https://user-images.githubusercontent.com/1135031/207278604-fd64db4a-2d20-4a30-a097-b4dd22b15d94.png)

**Comment by KirillOsenkov** [comment]
Oh, sorry, I just realized there are a couple of extra steps involved:

https://github.com/KirillOsenkov/MSBuildStructuredLog#installing-the-avalonia-version-on-mac
