### ISSUE TITLE
Latest supported version is 14, the log file has version 15.

### ISSUE THREAD

**Issue by drewnoakes** [KirillOsenkov/MSBuildStructuredLog#643]
Looks like MSBuild has upped the version to 15 now.

https://github.com/dotnet/msbuild/blob/ffdbe69315a91c06dfa852bfd2cb781821a5a05b/src/Build/Logging/BinaryLogger/BinaryLogger.cs#L56-L58

**Comment by drewnoakes** [comment]
https://github.com/dotnet/msbuild/pull/8146

**Comment by KirillOsenkov** [comment]
Published version 2.1.758
