### ISSUE TITLE
Bug: DurationDisplay formats several durations wrong

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [KirillOsenkov/MSBuildStructuredLog#646]
`TextUtilities.DisplayDuration` formats at least these duration values in a way, that the results are misleading:

* 60 sec -> 0.000 s
* 1 hour -> 0:00.000
* 2 days -> 0:00:00
* 1 second -> 0 ms

**Comment by KirillOsenkov** [comment]
Thanks!
