### ISSUE TITLE
Analyze Property And Item Evaluation Phase Performace

### ISSUE THREAD

**Issue by TFTomSun** [KirillOsenkov/MSBuildStructuredLog#648]
We have the situation that some builds seem to take quite long, but we can't really figure out why they are slow. The structured log viewer shows the top ten tasks already
![image](https://user-images.githubusercontent.com/5387192/212157460-b3839734-bf5f-44a9-8fbf-7365869986de.png)
But Tasks seem not to be the root cause for the overall build time of over one second. 
Is it possible to analyze the performance beyond the pure task execution time? Does the structure logger have some feature that could support such analysis?

Edit:
I found now a clear indicator that the evaluation phase it what takes so long:
![image](https://user-images.githubusercontent.com/5387192/212158589-7b47ece7-d2b3-4153-b508-f39fa8421286.png)
But can I dig there more into the details, what actually takes so long?

Edit 2:
Another issue I recognized are builds like this one:
![image](https://user-images.githubusercontent.com/5387192/212163799-1b3cecc8-a882-4aa8-871e-1489b25a8dcc.png)

It takes 16 seconds in total (thats also the total duration) but after 10 seconds it seems to be done. In the tracing is nothing visible after 10 seconds.

**Comment by KirillOsenkov** [comment]
You can run `msbuild /bl /profileevaluation` and it will show the perf in the tree:

![image](https://user-images.githubusercontent.com/679326/212168297-e3636d24-16f5-4bdb-a34b-a776dfef9c48.png)

Read more details at:
https://github.com/dotnet/msbuild/blob/main/documentation/evaluation-profiling.md

**Comment by TFTomSun** [comment]
cool, that will be helpful. Is it possible to activate that profiling for build logs that are produced by VisualStudio and the Build Logging Extensions as well?

Any ideas how those 6 seconds of idle at the end of the build can happen?

**Comment by KirillOsenkov** [comment]
Yes, see here for a better way to get good binlogs from Visual Studio without needing the Extension:
https://msbuildlog.com/#MSBUILDDEBUGENGINE

**Comment by KirillOsenkov** [comment]
Slowdowns in evaluation are usually to glob expansion (like you have `**\*` somewhere), it scans the disk and can take a long time for large folders.

**Comment by TFTomSun** [comment]
I identified already an issue with a large number of web assets and razorclasslibraries and created an issue here:
https://github.com/dotnet/razor/issues/8130

 However even with MSBUILDDEBUGENGINE=1, I don't see what is happen at the end of the build. I assume it's related to the web asset size, but I would like to see something.
![image](https://user-images.githubusercontent.com/5387192/212270277-3ed52cc5-6147-4a2d-8a48-53dec38ba3b1.png)

![image](https://user-images.githubusercontent.com/5387192/212270428-dc267372-efc1-4682-9389-ba0afe87e489.png)

**Comment by KirillOsenkov** [comment]
Don't think there's anything else I can do here on the viewer side, so closing.
