### ISSUE TITLE
Consider removing the `Microsoft.Build` package dependency, and the `TargetGraph` class.

### ISSUE THREAD

**Issue by teo-tsirpanis** [KirillOsenkov/MSBuildStructuredLog#649]
The `StructuredLogger.MSBuild` package depends on `Microsoft.Build` which is incompatible with .NET Standard 2.0 ("works" via the compatibility shim), weighs almost 4MB and brings quite many dependencies. It would be nice if we stopped depending on it.

Fortunately the only place where it is used is in [`TargetGraph`](https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/src/StructuredLogger/Construction/TargetGraph.cs), a class with relatively simple logic that is nowhere else used in this repro. Depending on your assessment of its importance and your appetite for breaking changes, we can:

* Just remove it.
* Obsolete it and remove it after a couple months/releases.
* Do nothing.

(and thank you very much for this project, it has allowed me to pierce inside `dotnet build`'s inner workings and helped me do lots of stuff with MSBuild!)

**Comment by teo-tsirpanis** [comment]
That's a nice tool, didn't know about it, thanks.

Only `Microsoft.Build` poses the problem; `Microsoft.Build.Framework` and `Micrsofot.Build.Utilities.Core` are fine.

And I noticed that `Microsoft.Build.Tasks.Core` is entirely unused; opened #650 to remove it.

**Comment by KirillOsenkov** [comment]
Cool, I have disabled TargetGraph.cs in this commit:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/f1a8e8b5fdaa8170a8818e47984ca01e2f06401a

Now you can remove Microsoft.Build too:
![image](https://user-images.githubusercontent.com/679326/215228704-f322fe72-9637-4492-9df8-2e1c31c32bbd.png)

**Comment by teo-tsirpanis** [comment]
OK, I will continue on #650.

**Comment by KirillOsenkov** [comment]
@teo-tsirpanis thanks!

Published https://www.nuget.org/packages/MSBuild.StructuredLogger/2.1.768
