### ISSUE TITLE
What is TaskRunner link for?

### ISSUE THREAD

**Issue by erdembayar** [KirillOsenkov/MSBuildStructuredLog#651]
Thank you for great tool.
I can see new TaskRunner link added to my desktop. But couldn't figure out what it's for? Is there any docs or how to use info? Probably 
I'm missing out something important.
![image](https://user-images.githubusercontent.com/8766776/216672349-d4de1d67-24e1-43d8-956b-af70dcd00ab7.png)

**Comment by KirillOsenkov** [comment]
You can delete it. It's an unfortunate artifact of how the installer works. It creates a shortcut for all .exe files and since we ship TaskRunner.exe (to run tasks), it creates a shortcut.

You can delete it.
