### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by bramborman** [KirillOsenkov/MSBuildStructuredLog#659]
Hi, I'd like to use this tool in an enterprise environment, but for it to be approved for use, it would be much easier, maybe even required, for it to have some kind of privacy policy - info about if the data are processed locally, or in cloud, etc.

Would it be possible to add such an information somewhere?

**Comment by KirillOsenkov** [comment]
How's this?

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/main/PRIVACY.md

**Comment by bramborman** [comment]
This should do, thanks a lot for such a quick response :)
