### ISSUE TITLE
NullReferenceException in viewer UI

### ISSUE THREAD

**Issue by layomia** [KirillOsenkov/MSBuildStructuredLog#662]
I was working on new targets in the dotnet/runtime repo (https://github.com/dotnet/runtime/pull/82179/commits/490c00d71f11c145e74280621fb8c2915d855543) and noticed that the viewer was showing a null ref when I opened the binlog produced when building my project. I was using a recent nightly build of the .NET 8 sdk  (8.0.100-preview.3.23156.3-win-x64) and the latest version of the viewer (2.1.787). cc @ericstj

[msbuild.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/10959871/msbuild.zip)

**Comment by ericstj** [comment]
Callstack of NRE:
```
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.Build.Logging.StructuredLogger.MessageProcessor.Process(BuildMessageEventArgs args) in C:\src\KirillOsenkov\MSBuildStructuredLog\src\StructuredLogger\Construction\MessageProcessor.cs:line 50

   at Microsoft.Build.Logging.StructuredLogger.Construction.MessageRaised(Object sender, BuildMessageEventArgs args) in C:\src\KirillOsenkov\MSBuildStructuredLog\src\StructuredLogger\Construction\Construction.cs:line 455
```
https://github.com/ericstj/MSBuildStructuredLog/blob/512f69518c40347e5a3dd87e5999aa96984b8de5/src/StructuredLogger/Construction/MessageProcessor.cs#L50

It would seem that BuildEventContext here is null.

**Comment by KirillOsenkov** [comment]
can you email me the binlog?

**Comment by KirillOsenkov** [comment]
Oops, never mind, I was on the phone and didn't see it.

**Comment by KirillOsenkov** [comment]
I will publish the fix soon and will discuss with the MSBuild team, I feel like they should not be logging a message with a null BuildEventContext.

**Comment by rainersigwald** [comment]
Indeed we shouldn't have been: https://github.com/dotnet/msbuild/pull/8509.
