### ISSUE TITLE
Wrong `Assembly` path displayed when one assembly is NOT strong named and the other is

### ISSUE THREAD

**Issue by mattleibow** [KirillOsenkov/MSBuildStructuredLog#669]
While testing my PR for strong naming build tasks in https://github.com/dotnet/maui/pull/14080, I noticed that the Assembly listed in the binlog was the wrong path. I am almost 100% sure that if it was not the case, then the task could not have run at all as the parameters - the REQUIRED parameters - are different in each version.

In my case, I have 2 versions:
 - 7.0 which is NOT strong named
 - 8.0 which IS strong named

I got a binlog to check:
 
[MauiApp99_Debug_AnyCPU_Build_2023-03-31T00_35_14.1900661+02_00.zip](https://github.com/dotnet/maui/files/11116688/MauiApp99_Debug_AnyCPU_Build_2023-03-31T00_35_14.1900661%2B02_00.zip)

Here is the build for net7: 
![image](https://user-images.githubusercontent.com/1096616/228979176-2d84cadf-32ba-4a9c-a111-8d90c5795a62.png)

Here is the build for net8:
![image](https://user-images.githubusercontent.com/1096616/228979307-806291ba-8a94-4956-aa52-622e4277ffad.png)

This is all in a single project, I duplicated the TFMs:

```xml
<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst;net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0;net8.0-windows10.0.19041.0</TargetFrameworks>
```

**Comment by KirillOsenkov** [comment]
Good catch! Fixed.
