### ISSUE TITLE
"The magic number in GZip header is not correct."

### ISSUE THREAD

**Issue by Porges** [KirillOsenkov/MSBuildStructuredLog#68]
I'm getting this error when trying to open a `.binlog` file created by the logger from the nuget package (1.1.130). The viewer is the same version. MSBuild itself is 14.0.

I did Ctrl-C the build partway through. Does this break the log files?

**Comment by Porges** [comment]
User error: I was using StructuredLogger but writing `.binlog` files. But it would be nice if the viewer would automatically detect the format (and warn if you've got the wrong extension?)

**Comment by KirillOsenkov** [comment]
I agree, there's plenty opportunity for confusion here :) I'm going to use this issue to track detecting format if the extension doesn't match. Thanks!
