### ISSUE TITLE
Add mention about SignPath Foundation and free code certificate in Readme.md

### ISSUE THREAD

**Issue by SabotageAndi** [KirillOsenkov/MSBuildStructuredLog#681]
Hi

First, thanks for maintaining this tool! I used it a lot in the past!

Now I am the Developer Evangelist from SignPath and I noticed that there is no mention of us in the readme. 
Could you please add this to your Readme:

```
## Code Signing
This program uses free code signing provided by [SignPath.io](https://signpath.io?utm_source=foundation&utm_medium=github&utm_campaign=MSBuildStructuredLog), and a free code signing certificate by the [SignPath Foundation](https://signpath.org?utm_source=foundation&utm_medium=github&utm_campaign=MSBuildStructuredLog)
```

If you want, I can send a Pull Request.

Thanks!

**Comment by KirillOsenkov** [comment]
There is a mention at the end of the first paragraph:

Thanks to https://signpath.io/ for generously providing a certificate to sign the installer.

**Comment by KirillOsenkov** [comment]
Feel free to send a PR to make edits if you like.

**Comment by SabotageAndi** [comment]
> There is a mention at the end of the first paragraph:
> 
> Thanks to https://signpath.io/ for generously providing a certificate to sign the installer.

Oops. I didn't notice that.

I submitted PR #683 to adjust the mention a little bit.
