### ISSUE TITLE
Retire our copies of some MSBuild types

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#698]
```
xamarin-macios/tests/common/BinLog.cs(76,10): error CS0433: The type 'TargetSkipReason' exists in both 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'StructuredLogger, Version=2.1.0.0, Culture=neutral, PublicKeyToken=d4c7181801cb6448' [xamarin-macios/tests/msbuild/Xamarin.MacDev.Tests/Xamarin.MacDev.Tests.csproj]
```

**Comment by rolfbjarne** [comment]
This turns out to be rather annoying to work around, because we have projects built with `xbuild` (from Mono), which doesn't understand aliases in package references :/

Would it be possible to get it fixed?

**Comment by KirillOsenkov** [comment]
Can you remind me on Aug 26? On vacation now. Hope I won’t forget!

**Comment by KirillOsenkov** [comment]
@rolfbjarne could you try updating to https://www.nuget.org/packages/MSBuild.StructuredLogger/2.1.846 and see if it fixes it for you?

**Comment by rolfbjarne** [comment]
thanks, that's working!
