### ISSUE TITLE
chocolatey and winget packages outdated

### ISSUE THREAD

**Issue by johannes-schmitt** [KirillOsenkov/MSBuildStructuredLog#707]
https://msbuildlog.com/ mentions install instructions for winget and choco. Unfortunately, the packages there are outdated. Most of the time, the self-update should handle this case.
I personally faced this when I tried to open a v16 log with the viewer directly after installing the viewer via choco. In that case, the self-update wasn't executed yet.

It would be great if new versions can be pushed to winget and choco.

**Comment by KirillOsenkov** [comment]
WinGet and scoop.sh update automatically, I've just pushed the Choco package.

Thanks!

**Comment by alteredego** [comment]
@KirillOsenkov - any chance you could push the latest to Chocolatey, please?

**Comment by KirillOsenkov** [comment]
pushed:
https://community.chocolatey.org/packages/msbuild-structured-log-viewer#versionhistory
