### ISSUE TITLE
Allow binlogtool to run on newer major releases of .NET

### ISSUE THREAD

**Issue by JanKrivanek** [KirillOsenkov/MSBuildStructuredLog#721]
### Context
https://github.com/dotnet/arcade/pull/13991#discussion_r1389571783
By default dotnet tools allow only the minor version rollforward. Major version rollforwad need to be opt-in at the execution time (and for the dotnet tools this can only be done via env var - https://github.com/dotnet/sdk/issues/10375) or it can be opted in via the tool itself.
If we want the tool to be used in the internal engineering builds, the default major rollforward should be seriously considered

### Downsides
This means appearing to support newer runtime that is not available for testing together with the tool at the time of publishing the tool - so an issue can occure in the future that would not be discoverable at the time of publishing.
However this is just a theoretical option, while not being able to run on newer runtime version is existing complication

**Comment by JanKrivanek** [comment]
@KirillOsenkov feel free to assign to me for fixing.

I just first wanted to see if you do not have strong concerns with this

**Comment by KirillOsenkov** [comment]
It's done:
https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/e1e75b3b5c23cb646fa5139d0258a9afd206227e

and published:
https://www.nuget.org/packages/binlogtool/1.0.8
