### ISSUE TITLE
Filter entries that are too old or too new?

### ISSUE THREAD

**Issue by Seikilos** [KirillOsenkov/MSBuildStructuredLog#722]
I have a log file that is very large and a build-error that indicates that something else is accessing the resource at the time.

Now I know that the failed task started at `2023-11-14 16:36:49.6033103` and ended at `2023-11-14 16:36:50.2594049`.
Is there a way to get only tasks whose start is < `startDate` and whose end date is > `endDate` ?

I have trouble to create the proper filter and do not know, whether I lack documentation or knowledge or whether the structure log does not support it.

**Comment by KirillOsenkov** [comment]
Right now we only have a way of listing tasks with their start and/or end times. You can append `$start`, `$end` or `$time` to any query to display start or end times or duration for projects, targets or tasks. 

For example:
`$task $start`

Sounds like a good idea to include date/time comparisons like you're suggesting.

**Comment by KirillOsenkov** [comment]
OK I implemented the following syntax:

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/679326/2d37e299-1524-4792-9762-1d9b48f3b1dc)

You can use any combination of `start<`, `start>`, `end<` and `end>`:
```
start<"2023-11-17 16:56:20.6915121"
start>"2023-11-17 16:56:20.6915121"
end<"2023-11-17 16:56:20.6915121"
end>"2023-11-17 16:56:20.6915121"
```

**Comment by KirillOsenkov** [comment]
I will deploy this new feature in the coming days, but if you wanted to try it out sooner, you can build the latest main branch yourself.

**Comment by KirillOsenkov** [comment]
I dunno, should I add proper support for `<` and `<=`, because currently the syntax is `<` and the semantics are `<=`. But seems like this covers the real-world cases, not sure I want to make this complicated.

**Comment by Seikilos** [comment]
> I dunno, should I add proper support for `<` and `<=`, because currently the syntax is `<` and the semantics are `<=`. But seems like this covers the real-world cases, not sure I want to make this complicated.

I would pick one of them and make syntax and semantics consistent. This avoids needless questions about why it behaves different than expected

**Comment by KirillOsenkov** [comment]
I published an update with this functionality now.
