### ISSUE TITLE
Support for project.assets.json

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/MSBuildStructuredLog#725]

**Comment by drewnoakes** [comment]
If this file embedded in binlogs?

**Comment by KirillOsenkov** [comment]
Yes I've been thinking things like "what is the chain of dependencies that results in this package being referenced by this project?", "which Nuget package caused this .dll reference or this file to be copied to output"?

**Comment by KirillOsenkov** [comment]
Some progress!

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/679326/b456ec09-e868-4164-bfcc-f1fc502bbdf2)

**Comment by drewnoakes** [comment]
Looking good! Could be interesting to list build files under packages too. That info is in the assets file.

**Comment by KirillOsenkov** [comment]
Yup, it is now able to search for files, and also show which dependency chain resulted in the package being included:

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/679326/5e2e70e2-c70c-4ac6-92bc-f718fc83d043)
