### ISSUE TITLE
`TreeViewExtensions.OnRequestBringIntoView` NRE

### ISSUE THREAD

**Issue by Youssef1313** [KirillOsenkov/MSBuildStructuredLog#758]
![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/31348972/0397b21c-c1d2-40bf-9356-e40eed552ec8)

Unfortunately, I have no repro steps. Looks like it was a one-off for me, but thought it might be still helpful to report.

**Comment by Youssef1313** [comment]
Nope, it doesn't seem a one-ff

**Comment by Youssef1313** [comment]
@KirillOsenkov I tried to debug this, looks like trying to get `_tv_scrollviewer_` is returning null.

I looked into template child names, and interestingly the scroll viewer is named `1_T`:

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/31348972/a5f56e21-edc5-432f-a469-b1b516c771de)


So, changing `_tv_scrollviewer_` to `1_T` fixes it, but that doesn't make sense to me.

The other thing is this:

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/39f61e3ae023e25e716eed7e7841f1e73cde9205/src/StructuredLogViewer/Controls/TreeViewExtensions.cs#L90-L93

Why this is looking at ancestors? Changing this to `FindVisualChild` works for me.

**Comment by KirillOsenkov** [comment]
I think this regressed in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/9a131c0e4584e720c636dd24dda9a56d4296703b

RequestBringIntoView had the code to just return if scrollViewer is null

**Comment by Youssef1313** [comment]
@KirillOsenkov My thought is that it shouldn't be null in the first place. I opened #759 to look into children instead of ancestors. But what I don't understand is why WPF is returning null when trying to find `_tv_scrollviewer_` and what this `1_T` come from. The TreeView template from WPF repo has `_tv_scrollviewer_`: https://github.com/dotnet/wpf/blob/3f3c5c3af19ca8f6fcd64b87905358a5e704136c/src/Microsoft.DotNet.Wpf/src/Themes/XAML/TreeView.xaml#L44

**Comment by KirillOsenkov** [comment]
Very interesting, thanks for investigating! Are you running this on net472? or .NET? I have no idea where `1_T` would be coming from.

It was looking for FindAncestor for an unrelated scenario that doesn't apply to this repo. I had this code in another place where it was possible that a re-templated treeview didn't have a scroll viewer, because it was itself inside another scroll viewer. That way FindAncestor worked. But this was only a fallback path. Our tree always contains a scroll viewer.

Weird.

**Comment by KirillOsenkov** [comment]
oh, are you using the dark theme? I think it retemplates the TreeView.

**Comment by Youssef1313** [comment]
Yes, I'm using dark theme!

**Comment by KirillOsenkov** [comment]
I see, thanks! I decided to be a bit more defensive in https://github.com/KirillOsenkov/MSBuildStructuredLog/commit/670ced2367fbdd3865442357e079e3ac2fc27412

**Comment by KirillOsenkov** [comment]
Could you please check if this works fine for you? I searched https://github.com/benruehl/adonis-ui/tree/1.16 for 1_T but I still can't find it there.

**Comment by Youssef1313** [comment]
@KirillOsenkov Yes, it does work.

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/31348972/4ddfcef7-fc00-4199-aac2-9f81dd727495)

**Comment by KirillOsenkov** [comment]
OK great, I'm publishing an update then.

**Comment by KirillOsenkov** [comment]
I'm guessing if this ScrollViewer has no name, 1_T is assigned automatically?

https://github.com/benruehl/adonis-ui/blob/535a89c666c99e679738d1e38ed09a1b7a9caa16/src/AdonisUI.ClassicTheme/DefaultStyles/TreeView.xaml#L254

**Comment by Youssef1313** [comment]
That could be it. Because accessing `.Name` returns empty string. And getting the style setters, they appear to be the same that you linked

**Comment by KirillOsenkov** [comment]
Published 2.2.207, thanks!
