### ISSUE TITLE
Evalutation node sort by id

### ISSUE THREAD

**Issue by workgroupengineering** [KirillOsenkov/MSBuildStructuredLog#761]
I would like to suggest the possibility of sorting the child nodes of the Evaluation node by id order instead of alphabetical order.

**Comment by KirillOsenkov** [comment]
They're sorted by name first, then by id, but I can add sort by id too.

**Comment by KirillOsenkov** [comment]
just curious, why do you need this? what is the scenario? 

you can search for `id:42` to find a specific eval and all builds that use it

**Comment by workgroupengineering** [comment]
If I haven't misunderstood, id represents the order in which the projects are evaluated.  If you need to track how a property changes, it's easier if the projects are in id order.  The ideal would be to view the projects by dependency but it would be more complicated.

**Comment by KirillOsenkov** [comment]
No, the id is random, and multiple projects can be evaluated and built in parallel. The value of properties is not shared across evaluations, each evaluation derives its own values for properties and items and they do not impact other evaluations in any way.
