### ISSUE TITLE
Add support for task assembly location

### ISSUE THREAD

**Issue by MichalPavlik** [KirillOsenkov/MSBuildStructuredLog#771]
Binlog will have a new value for task. It identifies assembly where the task is implemented.

I can do it after PR merge in MSBuild: https://github.com/dotnet/msbuild/pull/9948

Any ideas how/where should be visualize the new field?

**Comment by KirillOsenkov** [comment]
We'll need to do this without incrementing the version of MSBuild assemblies we reference.

We usually create our own TaskStartedEventArgs2, add the new property, and use that throughout.

At some point in the future, we update to the latest MSBuild and delete our forked copy of TaskStartedEventArgs2.

Let me know if you need any help here. Thanks!

**Comment by KirillOsenkov** [comment]
When you have a PR ready, you can send me a binlog of version 20 privately, so I can test it as well.
