### ISSUE TITLE
MSB4011 could be shown nested in the import tree

### ISSUE THREAD

**Issue by rainersigwald** [KirillOsenkov/MSBuildStructuredLog#774]
[MSB4011.zip](https://github.com/KirillOsenkov/MSBuildStructuredLog/files/15013447/MSB4011.zip) renders like this:

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/3347530/009c3009-c7af-458e-a96b-d0fbaaf45494)

I think it would be helpful to have that warning under the associated file node, that is nest it under the "location" value of the warning rather than (or maybe in addition to?) the "evaluation warnings for this project" node.

Text log rendering shows this structure slightly better than the viewer today since it interleaves the warnings with the imports, showing their context.

**Comment by KirillOsenkov** [comment]
Here ya go:

![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/679326/13dbc79f-9c6b-4bcb-b792-a2ee57214b87)

**Comment by rainersigwald** [comment]
I love it, thanks!
