### ISSUE TITLE
The Online Log Viewer and VSCode log viewer package do not work with MSBuild 17.9

### ISSUE THREAD

**Issue by hknielsen** [KirillOsenkov/MSBuildStructuredLog#776]
After upgrading to dotnet 8, I cant open up binlogs anymore with the vscode package, or load it in the MSBuild Online Log Viewer.

**Comment by KirillOsenkov** [comment]
I think @lambdageek may own the VSCode package, it might be as simple as updating to the latest version.

For the online log viewer it's a bit more involved. We'd need to merge the latest main into the 'live' branch and there are conflicts and I'm not sure I have the time for this.

**Comment by lambdageek** [comment]
Yea, sorry, I haven't touched the VS Code package in about a half a year. I'll try to find some time to pull in the latest from `main`.  Potentially it will run into the same issues that @KirillOsenkov mentions with the online viewer - we had to make some changes to support single-threaded execution and it's possible that stuff conflicts with `main` now

**Comment by KirillOsenkov** [comment]
I'm thinking of deprecating the online viewer, I just don't have the resources to maintain it

**Comment by KirillOsenkov** [comment]
Unfortunately the MSBuild team has made massive changes to binlog reading and writing, so there are a ton of conflicts

**Comment by hknielsen** [comment]
Yeah I think thats better if you dont intend to update it.
I only found out because the vscode one didnt work :)

**Comment by lambdageek** [comment]
Pushed https://marketplace.visualstudio.com/items?itemName=lambdageek.msbuild-structured-log-viewer v0.0.6 which should work with .NET 8 projects

**Comment by hknielsen** [comment]
@lambdageek it works thanks!

@KirillOsenkov should I close this issue, or do you want to keep it for the Online Log viewer depreciation?

**Comment by KirillOsenkov** [comment]
Closed, thanks
