### ISSUE TITLE
Unbounded memory consumption when viewing log files causes system unresponsive / crash

### ISSUE THREAD

**Issue by jhennessey** [KirillOsenkov/MSBuildStructuredLog#783]
Opening log files is consistently causing unbounded memory consumption which eventually leads to an unresponsive system / machine crash.

Most recently this occurred with a log file that was ~ 130MB in size. The process consumed over 14GB in memory before it was killed (letting it run will eventually cause unresponsiveness / machine crash). This has happened on multiple occasions and makes the application unusable for troubleshooting purposes.

Note that the `Enable tree virtualization` option (along with all others) was not enabled and this occurred using version `2.2.248`. The log contains sensitive data so I can't share it. But I'm happy to troubleshoot or provide any additional details that may be useful.

Thanks for all the work on this application!

**Comment by KirillOsenkov** [comment]
Unfortunately I don't think I'll be able to do anything about this, sorry.

**Comment by jhennessey** [comment]
> Unfortunately I don't think I'll be able to do anything about this, sorry.

No worries. In your experience, is this size log file just too large for the viewer to handle?

**Comment by KirillOsenkov** [comment]
yes, logs that are 300MB in size need 64GB RAM to open. The format is highly compressed and expands to consume gigabytes. When it does open it prints the stats about memory at the bottom. If you want you can send me your binlog privately at my first name dot last name at microsoft com and I can see if there are ways to make it smaller. You can use File -> Statistics to see what takes up space.

**Comment by KirillOsenkov** [comment]
how much RAM do you have on your machine? do you have a machine with >= 64 GB RAM?

**Comment by jhennessey** [comment]
I was able to open it on a machine with 64 GB :). The previous machine only had 16GB and the process was at ~30 GB after opening.

Here are the statistics (if interested):
![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/3958568/4bc651c4-423c-4b0a-830e-b54428aa352f)

Thanks!
