### ISSUE TITLE
[Suggestion] Allow to add negative searches to narrow down search results

### ISSUE THREAD

**Issue by FrankHeimes** [KirillOsenkov/MSBuildStructuredLog#788]
The msbuild log keeps buring me in piles of search results.
Unless I know exactly the message I'm looking for, it's realy hard to find the interesting events.

For example, a search for `"out of date"` may yield these results:
1. `Source "Foo.h" is out of date.`
2. `No resources are out of date with respect to their source files. Skipping resource generation.`

Since only a few instances of message 1 but gazillions of messages 2 may appear, it's close to impossible to spot message 1.

Please add an explicit negation operators (`"NOT"` or `!`) that allows to narrow down search results by adding exclusion terms, e.g.
`"out of date" NOT("No resources are")` or `"out of date" !("No resources are")`

IMHO, this would make the search function so much more useful.

**Comment by KirillOsenkov** [comment]
![image](https://github.com/KirillOsenkov/MSBuildStructuredLog/assets/679326/67e1d4c1-faa8-4598-b56d-cb2a9f2e5264)

**Comment by KirillOsenkov** [comment]
I implemented it. The syntax is `"out of date" not("no resources are")`.

**Comment by FrankHeimes** [comment]
Thanks a lot! This is so helpful!
Best, Frank

Von: Kirill Osenkov ***@***.***>
Gesendet: Donnerstag, 20. Juni 2024 02:04
An: KirillOsenkov/MSBuildStructuredLog ***@***.***>
Cc: Dr. Frank Heimes ***@***.***>; Author ***@***.***>
Betreff: Re: [KirillOsenkov/MSBuildStructuredLog] [Suggestion] Allow to add negative searches to narrow down search results (Issue #788)


I implemented it. The syntax is "out of date" not("no resources are").
