### ISSUE TITLE
Help > About shows "Locally built version"

### ISSUE THREAD

**Issue by pascalberger** [KirillOsenkov/MSBuildStructuredLog#802]
When going to "Help" > "About" in version 2.2.318 a message box with "Locally built version" is shown. I would have expected it to show the actual version instead.

**Comment by KirillOsenkov** [comment]
did you install via chocolatey?

**Comment by KirillOsenkov** [comment]
I screwed up and published a choco version that's newer than what's on github. Next time I publish a GitHub release it will fix itself.

**Comment by pascalberger** [comment]
> did you install via chocolatey?

Yes, was through Chocolatey

**Comment by KirillOsenkov** [comment]
Is this fixed now?
