### ISSUE TITLE
Use updated DotUtils to avoid lots of expensive Stream.ReadByte calls

### ISSUE THREAD

**Issue by stephentoub** [KirillOsenkov/MSBuildStructuredLog#820]
The DotUtils library provides some Stream types used here. Lots of calls end up getting made to those Stream's ReadByte methods, but it hasn't overridden them, such that the (expensive) base implementations are used. I submitted https://github.com/dotutils/streamutils/pull/2 to add those overrides. If/when that's merged and a new package is created that has the updated code, this project should be updated to use the newer version.

**Comment by KirillOsenkov** [comment]
Original:
![image](https://github.com/user-attachments/assets/741d6b46-ebf6-4782-8e29-b2f997bde108)

Low-hanging fruit removed:
![image](https://github.com/user-attachments/assets/116fad1e-b84f-4f2b-abae-8a2a3100bdc2)

This PR:
![image](https://github.com/user-attachments/assets/b4fdec15-4b38-46b7-8d5a-fdb75ac18f2d)
