### ISSUE TITLE
Visualization of MSB3277 doesn't include the assemblies involved

### ISSUE THREAD

**Issue by jaredpar** [KirillOsenkov/MSBuildStructuredLog#84]
Example of MSB3277 

> "E:\code\roslyn\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerExtension\SyntaxVisualizerExtension.csproj" (default target) (1) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1984,5): warning MSB3277: Found conf licts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbo sity is set to detailed. [E:\code\roslyn\src\Tools\Source\SyntaxVisualizer\SyntaxVisualizerExtension\SyntaxVisualizerExtension.csproj]

This message is frustrating because it's about ambiguity between assemblies during resolution but it doesn't actually list the assemblies involved. To find them you need to run a diagnostic log and then dig through it to find the assemblies involved. It's annoying but generally I know where to look in the log to find them at this point. 

Viewing this in structured logger though I can't seem to find a way to see the assemblies involved. I can use the search to find the warning but can't seem to find the assemblies involved here. 

Is there a way to view the assemblies with structured logger?

**Comment by jaredpar** [comment]
Ah I found it. You have to search for "conflict" singular above the "conflicts" warning. That will reveal it.

**Comment by KirillOsenkov** [comment]
Yes, the help watermark in the left search pane has "There was a conflict" as one template for the search. 

Do you have any ideas perhaps if I could make the experience better in the logger? Perhaps a special MSB3277 analyzer? It comes up pretty often and is a common source of confusion.

**Comment by jaredpar** [comment]
> Perhaps a special MSB3277 analyzer? It comes up pretty often and is a common source of confusion.

That would be great. It's such a frustrating warning to track down and happens all the time due to the prevalence of NuGet now.
