### ISSUE TITLE
Duration format in TimedNode is incorrect

### ISSUE THREAD

**Issue by DrivenByHim** [KirillOsenkov/MSBuildStructuredLog#86]
The issue is that if a Task took say 40 minutes, the resulting Timespan is {0:40:00}, which is formatted like seconds.

In TimedNode:
    Duration.ToString(@"s\.fff");

should be:
    Duration.TotalSeconds.ToString(@"#.###");

Alternatively, we could output a better converted string such as:
    string durationString;
    if (Duration.TotalSeconds >= 60)
        durationString = Duration.TotalMinutes.ToString(@"#.##m"));
    else if (Duration.TotalMinutes >= 60)
        durationString = Duration.TotalHours.ToString(@"#.##h"));
    else
        durationString = Duration.TotalSeconds.ToString(@"#.###s"));

Or maybe there's a better way to do that, I'm not sure.
I'll try to spend some time to fix this myself and issue a pull request.

**Comment by KirillOsenkov** [comment]
This should now be fixed.

Could you review this:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/master/src/StructuredLogger/ObjectModel/TimedNode.cs#L14

and let me know if this works as you expect?

**Comment by DrivenByHim** [comment]
Awesome thanks.  I just brought down version 1.1.224 today (still on 2015).

I'll get it on our build servers soon and check it out.
