### ISSUE TITLE
Ctrl+F should move focus to the opened "Text to find" input box

### ISSUE THREAD

**Issue by VladimirReshetnikov** [KirillOsenkov/MSBuildStructuredLog#88]

**Comment by AArnott** [comment]
When in the text viewer, Ctrl+F first opens and sets focus to the in-editor Find box, but then the search results pane at left immediately takes focus from the in-editor find box.

**Comment by KirillOsenkov** [comment]
I think this has been fixed.

**Comment by asklar** [comment]
thanks, I just tried it, looks like it works now 👍

**Comment by AArnott** [comment]
Yes, it works great. Thank you!
